<?
$item = $this->item;
$title = $item['id'] ? 'Edit Event' : 'Create Event';
$title = $this->_($title);
$method = $item['id'] ? 'put' : 'post';
$this->headTitle($title, 'SET');

if($this->form){
	$form = $this->form;
} else {
    if($item['id']) {
        $form = new Epic\Form\EventEditForm();
        $form->setAction($this->uri('/events/edit/'));

    } else {
        $form = new Epic\Form\EventCreateForm();
        $form->setAction($this->uri('/events/create/'));
    }
}
$form->useSubFormGroup()
     ->setMethod($item['id'] ? 'put' : 'post')
     ->setView($this)
     ->bind($item)
     ->prepare();

?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span6">
                                <div class="page-main-header">
                                    <a href="<?=$this->uri('/events/create/')?>" class="btn btn-small btn-orange pull-right"><i class="icon-pencil"></i> Create Event</a>
                                    <h3><?=$this->_($title)?></h3>
                                </div>
                                <div class="blog-list vlist">
                                    <form <?=$this->formAttr($form)?> class="form event-create-form">
                                        <?=$form->restful();?>
                                        <?=$form->helper('id');?>

                                        <fieldset class="row">
                                            <div class="control-group <?=$form->isError('title') ? 'error' : '';?>">
                                                <?=$form->helper('title', 'label', array('class' => 'control-label'))?>
                                                <div class="controls docs-input-sizes">
                                                    <?=$form->helper('title', array('class' => 'span6'))?>
                                                    <div class="help-block"><?=$form->helper('title', 'formElementErrors')?></div>
                                                </div>
                                            </div>

                                             <div class="control-group <?=$form->isError('location') ? 'error' : '';?>">
                                                <?=$form->helper('location', 'label', array('class' => 'control-label'))?>
                                                <div class="controls">
                                                    <?=$form->helper('location', array('class' => 'span5'))?>        
                                                    <div class="help-block"><?=$form->helper('location', 'formElementErrors')?></div>
                                                </div>
                                            </div>  

                                            <div class="control-group span4">
                                                <?=$this->widget('File', 'file/upload')?>
                                            </div>  

                                            <div class="control-group <?=$form->isError('startDay') ? 'error' : '';?> span3">
                                                <?=$form->helper('startDay', 'label', array('class' => 'control-label'))?>
                                                <div class="controls">
                                                    <?=$form->helper('startDay', array('class' => 'datepicker', 'data-date-format' => 'yyyy-mm-dd'))?>        
                                                    <div class="help-block"><?=$form->helper('startDay', 'formElementErrors')?></div>
                                                </div>
                                            </div>
                                            <div class="control-group <?=$form->isError('startTime') ? 'error' : '';?> span2">
                                                <?=$form->helper('startTime', 'label', array('class' => 'control-label'))?>
                                                <div class="controls">
                                                    <?=$form->helper('startTime', array('class' => 'timepicker', 'data-date-format' => 'yyyy-mm-dd'))?>        
                                                    <div class="help-block"><?=$form->helper('startTime', 'formElementErrors')?></div>
                                                </div>
                                            </div>
                                            
                                            <div class="control-group <?=$form->isError('endDay') ? 'error' : '';?> span3">
                                                <?=$form->helper('endDay', 'label', array('class' => 'control-label'))?>
                                                <div class="controls">
                                                    <?=$form->helper('endDay', array('class' => 'datepicker', 'data-date-format' => 'yyyy-mm-dd'))?>        
                                                    <div class="help-block"><?=$form->helper('endDay', 'formElementErrors')?></div>
                                                </div>
                                            </div>
                                            <div class="control-group <?=$form->isError('endTime') ? 'error' : '';?> span2">
                                                <?=$form->helper('endTime', 'label', array('class' => 'control-label'))?>
                                                <div class="controls">
                                                    <?=$form->helper('endTime', array('class' => 'timepicker', 'data-date-format' => 'yyyy-mm-dd'))?>        
                                                    <div class="help-block"><?=$form->helper('endTime', 'formElementErrors')?></div>
                                                </div>
                                            </div>

                                            
                                        </fieldset>

                                        <fieldset class="">
                                            <div class="control-group <?=$form->isError('timezone') ? 'error' : '';?>">
                                                <?=$form->helper('timezone', 'label', array('class' => 'control-label'))?>
                                                <div class="controls">
                                                    <?=$form->helper('timezone', array('class' => 'span1'))?>        
                                                    <div class="help-block"><?=$form->helper('timezone', 'formElementErrors')?></div>
                                                </div>
                                            </div> 
                                            <div class="control-group <?=$form->isError(array('Text', 'content')) ? 'error' : '';?>">
                                                <div id="editor-left" class="controls">
                                                    <?=$form->helper(array('Text', 'content'), 'formTextarea', array('class' => 'span6', 'rows' => '15',))?>
                                                </div>
                                                <div id="editor-right" class="markdown-preview"></div>
                                                <div class="help-block"><?=$form->helper(array('Text', 'content'), 'formElementErrors')?></div>

                                            </div>
                                        </fieldset>
                                        
                                        <fieldset class="">
                                             <div class="control-group <?=$form->isError('eventStatus') ? 'error' : '';?> hide">
                                                <?=$form->helper('eventStatus', 'label', array('class' => 'control-label'))?>
                                                <div class="controls">
                                                    <?=$form->helper('eventStatus', 'formSelect', array('class' => ''))?>
                                                    <div class="help-block"><?=$form->helper('eventStatus', 'formElementErrors')?></div>
                                                </div>
                                            </div>

                                            <div class="control-group <?=$form->isError('visibility') ? 'error' : '';?> hide">
                                                <?=$form->helper('visibility', 'label', array('class' => 'control-label'))?>
                                                <div class="controls">
                                                    <?=$form->helper('visibility', 'formSelect', array('class' => ''))?>
                                                    <div class="help-block"><?=$form->helper('visibility', 'formElementErrors')?></div>
                                                </div>
                                            </div>
                    
                                            <div class="control-group <?=$form->isError('longitude') ? 'error' : '';?> hide">
                                                <?=$form->helper('longitude', 'label', array('class' => 'control-label'))?>
                                                <div class="controls">
                                                    <?=$form->helper('longitude', array('class' => 'span3'))?>        
                                                    <div class="help-block"><?=$form->helper('longitude', 'formElementErrors')?></div>
                                                </div>
                                            </div>  
                    
                                            <div class="control-group <?=$form->isError('latitude') ? 'error' : '';?> hide">
                                                <?=$form->helper('latitude', 'label', array('class' => 'control-label'))?>
                                                <div class="controls">
                                                    <?=$form->helper('latitude', array('class' => 'span3'))?>        
                                                    <div class="help-block"><?=$form->helper('latitude', 'formElementErrors')?></div>
                                                </div>
                                            </div> 
                                            
                                            <div class="control-group <?=$form->isError('urlName') ? 'error' : '';?> hide">
                                                <?=$form->helper('urlName', 'label', array('class' => 'control-label'))?>
                                                <div class="controls">
                                                    <?=$form->helper('urlName', array('class' => ''))?>        
                                                    <div class="help-block"><?=$form->helper('urlName', 'formElementErrors')?></div>
                                                </div>
                                            </div>   
                                        </fieldset>

                                        <fieldset class="">
                                            <?if($this->hasModule('File')):?>
                                                <?=$form->helper(array('EventFile', 'file_id'), '')?>
                                            <?endif?>
                                        </fieldset>
                                        <div class="form-actions">
                                            <button type="submit" class="btn btn-info btn-large"><?=$this->_('Publish');?></button>
                                        </div>
                                    </form>
                                </div><!--main form end-->

                            </div><!--page main left end-->
                            <div class="span3">
                                <div class="page-extra">
                                    <?=$this->widget('Epic', 'widgets/userextra', $this->vars())?>
                                </div>
                            </div><!--page main right end-->
                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside', $this->vars())?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->

<script>
    var form = $(".event-create-form");
    var uploader = $('#singlefileupload');
    uploader.bind('fileuploaddone', function (e, data) {
            var file = data.result[0];
            form.find('input[name="EventFile[file_id]"]').val(file.id);
    });
</script>
