<?
$title = 'Events';
$this->headTitle($title, 'SET');
$user = $this->user;
$items = $this->items;
$viewAsGuest = $this->viewAsGuest;


$form = new Activity\Form\MessageCreateForm();
$form->useSubFormGroup()
     ->setMethod('post')
     ->setView($this)
     ->setAction($this->uri('/event/feed/'))
     ->prepare();
?>

<div class="container">
    <div class="page-bg">
        <div class="row">
            <div class="span4">
                <div class="event-side">
                    <div class="usercard media">
                        <a class="pull-left" href="#">
                            <img alt="userface" src="<?=$this->gravatar($user['email'], 120)?>" width="120" height="120" class="media-object"/>
                        </a>
                        <div class="media-body">
                            <h4 class="media-heading"><?=$user['userName']?></h4>
                            <h5>Joined Events: <span class="highlight">1234</span></h5>
                            <div class="media">
                                <a href="<?=$this->uri('/events/create/')?>" class="btn btn-gray"><i class="icon-plus"></i> Start New Event</a>
                                <p class="lowlight">Share your life</p>
                            </div>
                        </div>
                    </div>


                    <div class="event-subscription">
                        <p>Receive free new event notifications:</p>
                        <form>
                            <button class="btn btn-orange"><i class="icon-mini icon-envelope-alt"></i> Subscription Newsletters</button>
                        </form>
                    </div>


                    <script id="side-blog-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/blog/', array('user_id' => $this->user['id']))?>">
                        <div class="page-header border-header">
                            <h4>Best Event Promoters ({% if(o.paginator) { %}{%=o.paginator.rowCount%}{% } else { %} 0 {% } %})</h4>
                        </div>
                        <div class="side-blog-list">
                            {% if(o.items.length > 0) { %}
                                {% for (var i=0, item; item=o.items[i]; i++) { %}
                                    <div class="item">
                                        <a href="<?=$this->uri('/user/')?>{%=item.User.userName%}" title="" class="item-absolute imgdelay figure userface"><img src="http://www.gravatar.com/avatar/{%=item.User.EmailHash%}?size=50" alt="" class="img-rounded" width="50" height="50" /></a>
                                        <div class="item-inline item-text">
                                            <div class="text-content">
                                                <div class="item-title">
                                                    <a href="<?=$this->uri('/user/')?>{%=item.User.userName%}/blog/{%=item.urlName%}">{%=item.title%}</a>
                                                </div>
                                                <p>{%=item.Text.Preview%}</p>
                                            </div>
                                        </div>
                                    </div>
                                    {% } %}
                                {% } %}
                        </div>
                    </script>
                    <div class="side-ad-list">
                        <a href="#" class="pull-right"><img src="<?=$this->link('/src/epic/css/img/ad-2.jpg')?>" alt=""></a>
                        <a href="#" class="pull-left"><img src="<?=$this->link('/src/epic/css/img/ad-1.jpg')?>" alt=""></a>
                    </div>
                </div>
            </div><!--page main right end-->
            <div class="span8">
                <div class="event-main">

                    <div class="event-detail media">
                        <a class="pull-left" href="#">
                            <img class="media-object" src="https://lh5.googleusercontent.com/-x3r23ub6kmI/UJY4NRadtrI/AAAAAAAACi4/Q17gfO-yHIo/s240-p/Sculptures%252520By%252520The%252520Sea-24.jpg" width="240" />
                        </a>
                        <div class="media-body">
                            <h4 class="media-heading"><a href=""><?=$item['title'];?></a></h4>
                            <div class="media typo">
                                <dl class="dl-horizontal">
                                    <dt>Start Time:</dt>
                                    <dd>A description list is perfect for defining terms.</dd>
                                    <dt>End Time:</dt>
                                    <dd>Vestibulum id ligula porta felis euismod semper eget lacinia odio sem nec elit.</dd>
                                    <dt>Event Owner</dt>
                                    <dd>Etiam porta sem malesuada magna mollis euismod.</dd>
                                    <dd></dd>
                                </dl>
                                <p><span class="highlight">123</span> Members Joined</p>
                                <p><a href="" class="btn btn-orange"><i class="icon-user"></i> Join Now</a></p>
                            </div>
                        </div>
                    </div>

                    <div class="page-header border-header">
                        <h3>Event Members</h3>
                    </div>

                    <div class="side-user-list">
                        <ul class="thumbnails">
                            <?for($i = 0; $i < 32; $i++):?>
                            <li>
                            <a class="thumbnail" href="#">
                                <img src="<?=$this->link('/src/epic/css/img/face-04.jpg')?>" alt="" class="img-rounded" width="30" height="30" />
                            </a>
                            </li>
                            <?endfor;?>
                        </ul>
                    </div>

                    <div class="page-header border-header">
                        <h3>Event Description</h3>
                    </div>


                    <article class="typo typocn">
                    <?=$item['Text']['content']?>
                    </article>

                    <div class="page-header border-header">
                        <small class="pull-right"><a href="" class="btn btn-small btn-gray"><i class="icon-plus"></i>Add image</a></small>
                        <h3>Event Images</h3>
                    </div>


                    <div>
                        <ul class="thumbnails">
                            <?for($i=0;$i<8;$i++):?>
                            <li class="thumbnail"><a href="#"><img src="https://lh4.googleusercontent.com/-24AS3_MK3m0/UKLldhEDMoI/AAAAAAAARCM/u_zXkKeb9vo/s144-p/DSC_0065.jpg" alt=""></a></li>
                            <?endfor?>
                        </ul>
                    </div>

                    <div class="page-header border-header">
                        <h3>Event Talking</h3>
                    </div>


                    <div class="event-activities">
                        <div class="row">
                            <form id="activity-form" <?=$this->formAttr($form)?> class="activity-box span7">
                                <?=$form->helper('messageType', 'formHidden', array('class' => ''))?>        
                                <?=$form->helper('reference_id', array('class' => ''))?>
                                <?=$form->helper(array('MessageFile', 'file_id'), 'formHidden', array('class' => ''))?>
                                <input type="hidden" name="event_id" value="<?=$this->item['id']?>"> 
                                <?=$this->callback()?>
                                <fieldset class="form">
                                    <div class="activity-box-wrap">
                                        <div class="activity-box-content">
                                            <?=$form->helper('content', 'formTextarea', array('class' => '', 'rows' => 5, 'value' => 'From Event :' . $this->serverUrl() . '/events/' . $this->item['urlName']))?>        
                                        </div>
                                        <div class="activity-box-buttons">
                                            <a id="activity-box-image-button" class="activity-box-func activity-box-text" href="javascript:;" data-activity-text="Share Photo."><i class="icon-mini icon-picture"></i> Photo</a>
                                            <a id="activity-box-video-button" class="activity-box-func" href="javascript:;" data-placement="bottom" rel="popover"><i class="icon-mini icon-facetime-video"></i> Video</a>
                                            <label id="activity-box-sync-twitter" class="activity-box-func" title="Sync to Twitter"><i class="icon-mini icon-twitter"></i><input type="checkbox" /></label>
                                            There are <span class="highlight highlight-large activity-box-count">140</span> letters left <button type="submit" class="btn btn-light-brown btn-large">Submit</button>
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                        </div>

                        <div class="activity-list vlist">
                            <?foreach($items as $item):?>
                            <div class="item">
                                <a href="<?=$this->uri('/user/' . $item['User']['userName'])?>" title="" class="item-absolute item-userface"><img src="<?=$this->gravatar($item['User']['email'])?>" alt="" class="img-rounded" width="60" height="60" /></a>
                                <div class="item-inline item-text span6">
                                    <div class="item-content">
                                        <div class="item-title"><a href="<?=$this->uri('/user/' . $item['User']['userName'])?>" class="item-user"><?=$item['User']['userName']?></a> Said:</div>
                                        <p><?=$item['ContentHtml']?></p>
                                        <?if($item['File']):?>
                                        <div class="item-image">
                                            <p><a href="<?=$item['File'][0]['Thumb']?>" class="item-preview image" data-preview-type="image" data-url="<?=$this->thumb($item['File'][0]['Thumb'], array('w_400'))?>" data-width="400"><img src="<?=$this->thumb($item['File'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                                        </div>
                                        <?endif?>

                                        <?if($item['Video']):$video = $item['Video'];?>
                                        <div class="item-video">
                                            <?if($video['thumbnail']):?>
                                            <a href="<?=$video['url']?>" class="item-preview video" data-preview-type="video" data-url="<?=$video['swf']?>" data-width="<?=$video['width']?>" data-height="<?=$video['height']?>"><img src="<?=$video['thumbnail']?>" alt="video preview" class="img-polaroid" width="200" /><i class="icon-play btn-play"></i></a>
                                            <?else:?>
                                            <a href="<?=$video['url']?>" class="item-preview video" data-preview-type="video" data-url="<?=$video['swf']?>" data-width="<?=$video['width']?>" data-height="<?=$video['height']?>"><div class="video-no-preview"></div><i class="icon-play btn-play"></i></a>
                                            <?endif?>
                                        </div>
                                        <?endif?>

                                        <?if(isset($item['ForwardActivity']) && $item['ForwardActivity']): $subItem = $item['ForwardActivity'];?>
                                        <div class="well">
                                            <p><?=$subItem['ContentHtml']?></p>
                                            <?if($subItem['File']):?>
                                            <div class="item-image">
                                                <p><a href="<?=$subItem['File'][0]['Thumb']?>"><img src="<?=$this->thumb($subItem['File'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                                            </div>
                                            <?endif?>
                                            <div class="item-action">
                                                <p class="pull-right"><a href="<?=$this->uri('/feed/' . $subItem['messageHash'])?>" class="" data-activity-comment="<?=$subItem['id']?>"><i class="icon-comment"></i> Comments (<span class="highlight"><?=$subItem['commentedCount']?></span>)</a></p>
                                                <p class="pull-left">
                                                <a href="<?=$this->uri('/feed/' . $subItem['messageHash'])?>"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($subItem['createTime'])?>" datetime="<?=$this->datetime()->isoTime($subItem['createTime'])?>"><?=$this->datetime($subItem['createTime'])?></time></a>
                                                </p>
                                            </div>
                                        </div>
                                        <?endif?>

                                        <div class="item-action">
                                            <p class="pull-right">
                                            <a href="javascript:;" class="item-func remove <?=$viewAsGuest ? 'hide' : ''?>"><i class="icon-remove"></i> Delete</a>
                                            <a href="javascript:;" class="item-func comment" data-activity-comment="<?=$item['id']?>"><i class="icon-comment"></i> Comments (<span class="highlight"><?=$item['commentedCount']?></span>)</a>
                                            </p>
                                            <p class="pull-right hide"><a href="#activity-form" class="item-func reference" data-activity-reference="<?=$item['id']?>" data-activity-text="@<?=$item['User']['userName']?> "><i class="icon-share-alt"></i> RT (<span class="highlight"><?=$item['transferredCount']?></span>)</a></p>
                                            <p class="pull-left">
                                            <a href="<?=$this->uri('/feed/' . $item['messageHash'])?>" class="item-id"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['createTime'])?>" datetime="<?=$this->datetime()->isoTime($item['createTime'])?>"><?=$this->datetime($item['createTime'])?></time></a>
                                            </p>
                                        </div>
                                    </div>

                                    <div class="item-remove-ajax">
                                    </div>
                                    <div class="item-sub-ajax">
                                    </div>
                                </div>
                            </div>
                            <?endforeach?>

                            <?if($this->paginator):?>
                            <?=$this->paginator->setPath('/events/' . $this->item['urlName'] . '/')->setBaseQuery($this->query);?>
                            <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                            <?endif;?>
                        </div><!--activity-list end-->


                </div><!--event main end-->
            </div><!--page main left end-->
        </div>
    </div><!-- page-bg end-->
</div><!--container end-->


<div id="video-popover" class="popover bottom">
    <div class="arrow"></div>
    <h3 class="popover-title">Add Video
        <span class="close">×</span>
    </h3>
    <div class="popover-content">
        <div class="form">
            <div class="input-append">
                <input name="url" class="input-medium" type="text" placeholder="Video Url..." />
                <button id="add-video" class="btn" type="button">Add</button>
            </div>
        </div>
        <div class="ajax-video-preview">
            <p>Support video sites: Youtube, Youku</p>
        </div>
    </div>
</div>
<?=$this->widget('File', 'file/index')?>
<script src="<?=$this->link('/src/epic/js/feed.js')?>"></script>
