<?
$title = 'Events';
$title = $this->_($title);
$this->headTitle($title, 'SET');
$items = $this->items;

$form = new Event\Form\EventUserForm();
$form
->setView($this)
->useSubFormGroup()
->setMethod('post')
->setAction($this->uri('/event/join/'))
->prepare();

$unjoinForm = clone $form;
$unjoinForm->setMethod('delete');


$eventSearchForm = $this->form ? $this->form : new Epic\Form\EventSearchForm();
$eventSearchForm->setView($this)
     ->setMethod('get')
     ->setAction($this->uri('/events/'))
     ->prepare();

$calendar = $this->calendar;
$week = $this->week;
$prevPath = $this->prevPath;
$nextPath = $this->nextPath;
$dayPath = $this->dayPath;
?>

<div class="container">
    <header class="event-header">
    <div class="row">
        <div class="span4">
            <h2>Event</h2>
        </div><!--page main right end-->
        <div class="span8">
            <?=$this->widget('Epic', 'widgets/eventnav', $this->vars())?>
        </div><!--page main left end-->
    </div>
    </header>
</div>
<div class="container">
    <div class="page-bg">
        <div class="row">
            <div class="span4">
                <?=$this->widget('Epic', 'widgets/eventside', $this->vars())?>
            </div><!--page main right end-->
            <div class="span8">
                <div class="event-main">
                    <script id="event-thumbnails" type="text/x-tmpl" data-url="<?=$this->uri('/data/event/', array('recommend' => 1,'rows' => 28))?>">
                    <div class="event-thumbnails">
                        <ul>
                            {% if(o.items.length > 0) { %}
                            {% for (var i=0, item; item=o.items[i]; i++) { %}
                                <li><a href="<?=$this->uri('/events/')?>{%=item.urlName%}">
                                {% if(item.File) { %}
                                    <img src="" alt="{%=item.urlName%}" />
                                {% }else{ %}
                                    <img src="https://lh4.googleusercontent.com/-24AS3_MK3m0/UKLldhEDMoI/AAAAAAAARCM/u_zXkKeb9vo/s144-p/DSC_0065.jpg" alt="">
                                {% } %}
                                </a></li>
                            {% } %}
                            {% } %}
                        </ul>
                    </div> 
                    </script>

                    <div class="event-grid">
                        <header class="event-grid-header">
                        <small class="pull-right">Hot Cities: <a href="<?=$this->uri('/events/list/', array('city' => 'New York','order' => 'timedesc'));?>">New York</a> <a href="<?=$this->uri('/events/list/', array('city' => 'Tokyo','order' => 'timedesc'));?>">Tokyo</a> <a href="<?=$this->uri('/events/list/', array('city' => 'Los Angeles','order' => 'timedesc'));?>">Los Angeles</a></small>
                        <div class="page-header border-header">
                            <h3>New Events </h3><a href="<?=$this->uri('/my/city/')?>" class="switch">[Switch City]</a>
                        </div>
                        <ul class="nav nav-pills">
                            <li class="active"><a href="<?=$this->uri('/events/list/', array('order' => 'timedesc'));?>">All Cities</a> |</li>
                            <li><a href="#">My City</a> |</li>
                            <li><a href="<?=$this->uri('/events/list/', array('city' => 'Red Wine','order' => 'timedesc'));?>">Red Wine</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('city' => 'French cuisine','order' => 'timedesc'));?>">French cuisine</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('city' => 'Cocktail party','order' => 'timedesc'));?>">Cocktail party</a></li>
                        </ul>
                        </header>
                        <div class="grid-3columns">
                            <?for($i=0;$i<6;$i++):?>
                            <div class="event media">
                                <a class="pull-left" href="#">
                                    <img  src="https://lh5.googleusercontent.com/-x3r23ub6kmI/UJY4NRadtrI/AAAAAAAACi4/Q17gfO-yHIo/s144-p/Sculptures%252520By%252520The%252520Sea-24.jpg" width="90" height="90" class="media-object img-rounded"/>
                                </a>
                                <div class="media-body">
                                    <h4 class="media-heading"><a href="#">Find best French cuisine in Tokyo</a></h4>
                                    <div class="media">
                                        <!--<a href="<?=$this->uri('/events/create/')?>" class="btn"><i class="icon-plus"></i> Join Now</a>-->
                                        <p class="lowlight">1234 members joined.</p>
                                    </div>
                                </div>
                            </div>
                            <?endfor?>
                        </div>
                    </div>

                    <div class="event-grid">
                        <header class="event-grid-header">
                        <div class="page-header border-header">
                            <h3>Feature Events</h3>
                        </div>
                        <ul class="nav nav-pills">
                            <li class="active"><a href="<?=$this->uri('/events/list/', array('order' => 'memberdesc'));?>">All Cities</a> |</li>
                            <li><a href="#">My City</a> |</li>
                            <li><a href="<?=$this->uri('/events/list/', array('city' => 'Red Wine','order' => 'memberdesc'));?>">Red Wine</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('city' => 'French cuisine','order' => 'memberdesc'));?>">French cuisine</a> | </li>
                            <li><a href="<?=$this->uri('/events/list/', array('city' => 'Cocktail party','order' => 'memberdesc'));?>">Cocktail party</a></li>
                        </ul>
                        </header>
                        <div class="grid-2columns">
                            <?for($i=0;$i<6;$i++):?>
                            <div class="event media">
                                <a class="pull-left" href="#">
                                    <img  src="https://lh5.googleusercontent.com/-x3r23ub6kmI/UJY4NRadtrI/AAAAAAAACi4/Q17gfO-yHIo/s144-p/Sculptures%252520By%252520The%252520Sea-24.jpg" width="90" height="90" class="media-object img-rounded"/>
                                </a>
                                <div class="media-body">
                                    <h4 class="media-heading"><a href="#">Find best French cuisine in Tokyo</a></h4>
                                    <div class="media">
                                        <a href="<?=$this->uri('/events/create/')?>" class="btn"><i class="icon-plus"></i> Join Now</a>
                                        <p class="lowlight">1234 members joined.</p>
                                    </div>
                                </div>
                            </div>
                            <?endfor?>
                        </div>
                    </div>

                    <table class="event-calendar table table-bordered table-condensed table-striped">
                        <thead>
                            <tr>
                                <td class="prev">
                                    <a href="<?=$this->uri($prevPath, array('start' => $calendar['prev']['startDay']))?>"><i class="icon-large icon-chevron-left highlight"></i></a>
                                </td>
                                <td class="switch" colspan="5"><a href="<?=$this->uri($prevPath, array('start' => $calendar['today']['startDay']))?>"><?=$calendar['monthName']?> <?=$calendar['yearName']?></a></td>
                                <td class="next">
                                    <a href="<?=$this->uri($prevPath, array('start' => $calendar['next']['startDay']))?>"><i class="icon-large icon-chevron-right highlight"></i></a>
                                </td>
                            </tr>
                            <tr>
                                <?foreach($calendar['weekNames'] as $weekname):?>
                                <th class="dow"><?=$weekname?></th>
                                <?endforeach;?>
                            </tr>
                        </thead>
                        <tbody>
                            <?foreach($calendar['days'] as $week):?>
                            <tr>
                                <?foreach($week as $day):?>
                                <th  title="<?=$day['datedb']?>" class="day <?=$day['isAdd'] ? "new" : ''?>">
                                    <?if($day['datedb'] == $calendar['today']['datedb']):?>
                                    <span class="today"><?=$day['day']?></span>
                                    <?else:?>
                                    <?=$day['day']?>
                                    <?endif?>
                                   
                                </th>
                                <?endforeach;?>
                            </tr>
                            <tr>
                                <?foreach($week as $day):?>
                                <td title="<?=$day['datedb']?>" class="day <?=$day['isAdd'] ? "new" : ''?>">
                                    <?if (isset($day['Events'])):?>
                                        <?foreach ($day['Events'] as $event):?>
                                            <a href="<?=$this->uri('/events/' . $event['urlName'])?>"><?=$event['title']?></a>
                                        <?endforeach;?>
                                    <?endif;?>
                                </td>
                                <?endforeach;?>
                            </tr>
                            <?endforeach;?>
                        </tbody>
                    </table>

                </div><!--event main end-->
            </div><!--page main left end-->
        </div>
    </div><!-- page-bg end-->
</div><!--container end-->
