<?
$title = 'Events List';
$title = $this->_($title);
$this->headTitle($title, 'SET');
$items = $this->items;

$eventSearchForm = $this->form ? $this->form : new Epic\Form\EventSearchForm();
$eventSearchForm->setView($this)
     ->setMethod('get')
     ->setAction($this->uri('/events/list/'))
     ->prepare();


$calendar = $this->calendar;
$week = $this->week;
$prevPath = $this->prevPath;
$nextPath = $this->nextPath;
$dayPath = $this->dayPath;
?>

<div class="container">
    <header class="event-header">
    <div class="row">
        <div class="span4">
            <h2>Event</h2>
        </div><!--page main right end-->
        <div class="span8">
            <?=$this->widget('Epic', 'widgets/eventnav', $this->vars())?>
        </div><!--page main left end-->
    </div>
    </header>
</div>
<div class="container">
    <div class="page-bg">
        <div class="row">
            <div class="span4">
                <?=$this->widget('Epic', 'widgets/eventside', $this->vars())?>
            </div><!--page main right end-->
            <div class="span8">
                <div class="event-main">
                    <div id="event-calendar-wrap">
                        <table class="event-calendar table table-bordered table-condensed table-striped hide">
                            <thead>
                                <tr>
                                    <td class="prev">
                                        <a href="<?=$this->uri($prevPath, array('start' => $calendar['prev']['startDay']))?>"><i class="icon-large icon-chevron-left highlight"></i></a>
                                    </td>
                                    <td class="switch" colspan="5"><a href="<?=$this->uri($prevPath, array('start' => $calendar['today']['startDay']))?>"><?=$calendar['monthName']?> <?=$calendar['yearName']?></a></td>
                                    <td class="next">
                                        <a href="<?=$this->uri($prevPath, array('start' => $calendar['next']['startDay']))?>"><i class="icon-large icon-chevron-right highlight"></i></a>
                                    </td>
                                </tr>
                                <tr>
                                    <?foreach($calendar['weekNames'] as $weekname):?>
                                    <th class="dow"><?=$weekname?></th>
                                    <?endforeach;?>
                                </tr>
                            </thead>
                            <tbody>
                                <?foreach($calendar['days'] as $week):?>
                                <tr>
                                    <?foreach($week as $day):?>
                                    <th  title="<?=$day['datedb']?>" class="day <?=$day['isAdd'] ? "old" : ''?> <?=$day['datedb'] < $calendar['today']['datedb'] ? 'passed' : ''?>">
                                        <?if($day['datedb'] == $calendar['today']['datedb']):?>
                                        <span class="today"><?=$day['day']?></span>
                                        <?else:?>
                                        <?=$day['day']?>
                                        <?endif?>

                                    </th>
                                    <?endforeach;?>
                                </tr>
                                <tr>
                                    <?foreach($week as $day):?>
                                    <td title="<?=$day['datedb']?>" class="day <?=$day['isAdd'] ? "old" : ''?> <?=$day['datedb'] < $calendar['today']['datedb'] ? 'passed' : ''?>  <?=$day['datedb'] == $calendar['today']['datedb'] ? 'today' : ''?>">
                                        <?if (isset($day['Events'])):?>
                                        <?foreach ($day['Events'] as $event):?>
                                        <a href="<?=$this->uri('/event/' . $event['urlName'])?>" class="label label-event" title="<?=$event['title']?>"><?=$event['title']?></a>
                                        <?endforeach;?>
                                        <?endif;?>
                                    </td>
                                    <?endforeach;?>
                                </tr>
                                <?endforeach;?>
                            </tbody>
                        </table>
                    </div>

                    <div class="search-filter">
                        <form <?=$this->formAttr($eventSearchForm)?> class="form form-inline">
                            <?=$eventSearchForm->helper('keyword', array('class' => 'span2', 'placeholder' => 'Keyword...'))?>
                            <?=$eventSearchForm->helper('city', 'formSelect', array('class' => 'input-medium select2', 'placeholder' => 'City'))?>
                            <?=$eventSearchForm->helper('afterStartDay', array('class' =>'input-small datepicker', 'data-date-format' => 'yyyy-mm-dd', 'placeholder' => 'Start day'))?>
                            <?=$eventSearchForm->helper('beforeStartDay', array('class' => 'input-small datepicker', 'data-date-format' => 'yyyy-mm-dd', 'placeholder' => 'End day'))?>
                            <button class="btn" type="submit"><?=$this->_('Filter Events')?></button>
                        </form>
                    </div>
                    <?=$this->widget('Epic', 'epic/event/list-template', $this->vars())?>

                </div><!--event main end-->
            </div><!--page main left end-->
        </div>
    </div><!-- page-bg end-->
</div><!--container end-->


<script>
eva.ready(function(){
        $(".nav-week a").on('click', function(){
                var calendar = $(".event-calendar");
                calendar.is(":visible") ? calendar.fadeOut() : calendar.fadeIn();
                return false;
        });

        $("#event-calendar-wrap").on('click', '.prev a, .next a', function(){
                $("#event-calendar-wrap").load($(this).attr('href') + ' .event-calendar', function(){
                    $(".event-calendar").fadeIn();
                });
                return false;
        });
});
</script>
