<?
$items = $this->items;
$form = new Event\Form\EventUserForm();
$form
->setView($this)
->useSubFormGroup()
->setMethod('post')
->setAction($this->uri('/event/join/'))
->prepare();

$unjoinForm = clone $form;
$unjoinForm->setMethod('delete');
?>
<div class="event-list vlist">
    <?foreach($items as $item):?>
    <div class="item media">
        <div class="pull-right event-action">
            <?if(isset($item['Join']) && $item['Join']['user_id'] == $item['user_id']):?>
            <?elseif(isset($item['Join']) && $item['Join'] && $item['Join']['user_id'] != $item['user_id']):?>
            <form <?=$this->formAttr($unjoinForm)?>>
                <?=$unjoinForm->restful();?>
                <?=$unjoinForm->helper('event_id', 'formHidden', array('class' => '', 'value' => $item['id']))?>
                <?=$unjoinForm->helper('user_id', array('class' => ''))?>
                <?=$this->callback()?>
                <button class="btn btn-small item-action-main">Quit</button>
            </form>
            <?elseif($item['memberEnable'] && ($item['memberLimit'] > $item['Count']['memberCount'] || $item['memberLimit'] == 0)):?>
            <form <?=$this->formAttr($form)?>>
                <?=$form->restful();?>
                <?=$form->helper('event_id', 'formHidden', array('class' => '', 'value' => $item['id']))?>
                <?=$form->helper('user_id', array('class' => ''))?>
                <?=$this->callback()?>
                <button class="btn btn-small item-action-main">Join</button>
            </form>
            <?endif?>
        </div>
        <a class="pull-left" href="<?=$this->uri('/event/' . $item['urlName'])?>">
            <?if($item['File']):?>
            <img class="media-object img-rounded" src="<?=$this->thumb($item['File'][0]['Thumb'], array('c_fill', 'w_90', 'h_90'))?>" width="90" />
            <?else:?>
            <img class="media-object img-rounded" src="<?=$this->assets('/module/epic/img/event-default.jpg')?>" width="90" />
            <?endif?>
        </a>
        <div class="media-body">
            <h4 class="media-heading"><a href="<?=$this->uri('/event/' . $item['urlName'])?>" class="item-user"><?=$item['title']?></a></h4>
            <div class="media">
                <p class="lowlight"><?=$this->_('Event Time')?>: <?=$item['startDay']?> <?=$item['startTime'] ? $item['startTime'] : null?> - <?=$item['endDay']?> <?=$item['endTime'] ? $item['endTime'] : null?></p>
                <p class="lowlight"><?=$this->_('Location')?>: <?=$item['city']?> <?=$item['location']?></p>
                <p class="lowlight"><span class="highlight"><?=$item['Count']['memberCount']?></span> <?=$this->_('Members Joined')?> </p>
            </div>
        </div>
    </div>
    <?endforeach?>

    <?if($this->paginator):?>
    <?=$this->paginator->setPath('/events/list/')->setBaseQuery($this->query);?>
    <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
    <?endif;?>
</div><!--activity-list end-->


