<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?=$this->language?>" lang="<?=$this->language?>">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
    <?=$this->headTitle()?>
	<!--[if lt IE 9]>
	<meta http-equiv="PRAGMA" content="NO-CACHE" />
    <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
	<![endif]-->
    <?=$this->headMeta()?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="<?=$this->link('/src/gwa/css/gwa.css')?>" media="all" rel="stylesheet" type="text/css" />
    <?//=$this->evajs()?>
</head>

<body class="">

<nav id="navbar_top" class="navbar_top">
    <div class="container">
        <ul class="pull-right">
            <li><a href="<?=$this->uri('/pages/about')?>" class="highlight" rel="nofollow">关于我们</a></li>
            <li><a href="<?=$this->uri('/order/')?>" class="highlight" rel="nofollow">网上订单</a></li>
        </ul>
        <p class="pull-left">欢迎光临甘肃婚庆行业协会</p>
    </div>
</nav>

<header id="header" class="header"><div class="container">
    <p id="hotline" class="pull-right"><?=$this->widget('Gwa', 'components/phone')?></p>
    <h1>
        <a href="<?=$this->uri('/')?>" title="甘肃婚庆行业协会">
            甘肃婚庆行业协会
        </a>
    </h1>
</div></header><!-- #header end -->

<nav id="navbar_main" class="navbar navbar_main"><div class="navbar-inner"><div class="container">
<ul class="nav">
    <li><a href="<?=$this->uri('/')?>" class="first">首页</a></li><li>
    <a href="<?=$this->uri('/category/news')?>">最新动态</a></li><li>
    <a href="<?=$this->uri('/category/jiudian')?>">婚庆酒店</a></li><li>
    <a href="<?=$this->uri('/category/sheying')?>">婚庆摄影</a></li><li>
    <a href="<?=$this->uri('/category/gongsi')?>">婚庆公司</a></li><li>
    <a href="<?=$this->uri('/category/hunsha')?>">婚纱礼服</a></li><li>
    <a href="<?=$this->uri('/category/hunche')?>">婚车租赁</a></li><li>
    <a href="<?=$this->uri('/category/zhuangxiu')?>">新婚装修</a></li><li>
    <a href="<?=$this->uri('/bbs')?>">婚庆论坛</a></li><li>
</ul>
</div></div></nav>


<div id="page" class="page">
<?=$this->layout()->content;?>
</div><!-- #page end-->

<footer id="footer" class="footer"><div class="container">
			<nav id="navbar_footer" class="">
			<ul class="nav">
				<li><a href="<?=$this->uri('/')?>" class="first">首页</a></li><li>
				<a href="<?=$this->uri('/pages/about-yangs')?>">杨氏介绍</a></li><li>
				<a href="<?=$this->uri('/themes')?>">主题摄影</a></li><li>
				<a href="<?=$this->uri('/category/events')?>">最新活动</a></li><li>
				<a href="<?=$this->uri('/pages/franchise')?>">加盟连锁</a></li><li>
				<a href="<?=$this->uri('/contact/order/')?>">在线订单</a></li><li>
				<a href="<?=$this->uri('/pages/joinus')?>">人才招聘</a></li><li>
				<a href="<?=$this->uri('/pages/contact')?>" class="last">联系我们</a></li>
			</ul>
			</nav>
    <p>
    Copyright 2009 - 2012 A8国际婚纱电影会馆  All Rights Reserved
    </p>
    <p>电话：0931-8477000 13919002602
    </p>
    <p>邮箱：1095813029@qq.com | QQ：1095813029/1355246279</p>
    <p>地址：甘肃省兰州市张掖路231号民基大厦A座5楼
    </p>
    <p><a href="http://www.miibeian.gov.cn" target="_blank">陇ICP备7546564588号</a>　|　技术支持：<a href="http://www.easthv.cc/" target="_blank">兰州东方惠梵软件科技有限公司</a>
    </p>
</div></footer><!-- #footer end-->


<script src="<?=$this->link('/lib/js/jquery/jquery.min.js')?>"></script>
    <script src="<?=$this->link('/lib/js/bootstrap/bootstrap.min.js')?>"></script>
    <script src="<?=$this->link('/eva/js/core.js')?>"></script>
    <script src="<?=$this->link('/lib/js/jquery/jquery.easing.1.3.js')?>"></script>
    <script src="<?=$this->link('/eva/js/eva.jquery.evaSlider.js')?>"></script>
    <script src="<?=$this->link('/src/gwa/js/init.js')?>"></script>
</body>
</html>
