<?
$this->headTitle('Change Your City', 'SET');	
?>
<div class="container">
    <div id="singletitle" class="page-header typo">
        <h1>Change Your City</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="span12">
            <div id="change-city" class="well typo">
                <div class="page-header">
                    <h2>EUROPE</h2>
                </div>
                <ul class="row">
                    <li class="span3"><a href="#">Amsterdam</a></li>
                    <li class="span3"><a href="#">Florence</a></li>
                    <li class="span3"><a href="#">Prague</a></li>
                    <li class="span3"><a href="#">Athens</a></li>
                    <li class="span3"><a href="#">Istanbul</a></li>
                    <li class="span3"><a href="#">Rome</a></li>
                    <li class="span3"><a href="#">Barcelona</a></li>
                    <li class="span3"><a href="#">Lisbon</a></li>
                    <li class="span3"><a href="#">Seville</a></li>
                    <li class="span3"><a href="#">Berlin</a></li>
                    <li class="span3"><a href="#">London</a></li>
                    <li class="span3"><a href="#">Venice</a></li>
                    <li class="span3"><a href="#">Brussels</a></li>
                    <li class="span3"><a href="#">Madrid</a></li>
                    <li class="span3"><a href="#">Vienna</a></li>
                    <li class="span3"><a href="#">Budapest</a></li>
                    <li class="span3"><a href="#">Milan</a></li>
                    <li class="span3"><a href="#">Zurich</a></li>
                    <li class="span3"><a href="#">Copenhagen</a></li>
                    <li class="span3"><a href="#">Naples</a></li>
                    <li class="span3"><a href="#">Dublin</a></li>
                    <li class="span3"><a href="#">Paris</a></li>
                </ul>
                <div class="page-header">
                    <h2>Africa & Middle EAST</h2>
                </div>
                <ul class="row">
                    <li class="span3"><a href="#">Cairo</a></li>
                    <li class="span3"><a href="#">Marrakech</a></li>
                    <li class="span3"><a href="#">Tel Aviv</a></li>
                </ul>
                <div class="page-header">
                    <h2>Amercia</h2>
                </div>
                <ul class="row">
                    <li class="span3"><a href="#">Las Vegas</a></li>
                    <li class="span3"><a href="#">Los Angeles</a></li>
                    <li class="span3"><a href="#">Miami</a></li>
                    <li class="span3"><a href="#">New York</a></li>
                    <li class="span3"><a href="#">San Francisco</a></li>
                    <li class="span3"><a href="#">Washington D.C.</a></li>
                    <li class="span3"><a href="#">Buenos Aires</a></li>
                    <li class="span3"><a href="#">Rio De Janeiro</a></li>
                    <li class="span3"><a href="#">San Paulo</a></li>
                </ul>
                <div class="page-header">
                    <h2>Asia</h2>
                </div>
                <ul class="row">
                    <li class="span3"><a href="#">Shanghai</a></li>
                    <li class="span3"><a href="#">Beijing</a></li>
                    <li class="span3"><a href="#">Guangzhou</a></li>
                    <li class="span3"><a href="#">Nanjing</a></li>
                    <li class="span3"><a href="#">Hong Kong</a></li>
                    <li class="span3"><a href="#">Singapore</a></li>
                </ul>
            </div>
        </div>
    </div>
</div>
