<ul class="nav nav-tabs nav-stacked">
    <li data-highlight-url="^/account/profile/?$"><a href="<?=$this->uri('/account/profile/')?>"><i class="icon-user"></i> Profile</a></li>
    <li data-highlight-url="^/account/setting/?$"><a href="<?=$this->uri('/account/setting/')?>"><i class="icon-cogs"></i> Setting</a></li>
    <li data-highlight-url="^/account/membership/?$"><a href="<?=$this->uri('/account/membership/')?>"><i class="icon-trophy"></i> Membership</a></li>
    <li data-highlight-url="^/account/(import|addfriend|invite)"><a href="<?=$this->uri('/account/import/')?>"><i class="icon-search"></i> Find Friends</a></li>
</ul>
