<div class="group-side">
    <div class="calendar calendar-mini">
        <div class="calendar-wrap">

        </div>
        <div class="calendar-caption">
            <i class="icon-stop green"></i> Coming Events
            <i class="icon-stop brown"></i> Finished Events
            <i class="icon-stop orange"></i> Today
        </div>
    </div><!--calendar end-->

    <div class="page-header  border-header">
        <h4 class="txt-bold">Group Members (<?=count($this->members)?>)</h4>
    </div>

    <div class="group-member-list">
        <div class="page-header">
            <h5 class="txt-bold">Group Admin</h5>
        </div>
       <?if($this->members):?>
        <ul>
        <?foreach($this->members as $member):?>
        <?if($member['role'] != 'admin'){continue;}?>
            <li>
                <a href="<?=$this->uri('/user/' . $member['User']['userName'])?>">
                    <img alt="userface" class="img-rounded" src="<?=$this->gravatarLink($member['User']['email'], 30)?>" width="30" height="30"/>
                    <?=$member['User']['userName']?>
                </a>
            </li>
        <?endforeach;?>
        </ul>
        <?endif;?> 
    </div>
    <div class="group-member-list">
        <div class="page-header">
            <small class="pull-right"><a href="<?=$this->uri('/user/', array('group' => $this->item['id']))?>">View All</a></small>
            <h5 class="txt-bold">Group Members</h5>
        </div>
        <?if($this->members):?>
        <ul>
        <?foreach($this->members as $member):?>
        <?if($member['role'] == 'admin'){continue;}?>
            <li>
                <a href="<?=$this->uri('/user/' . $member['User']['userName'])?>">
                    <img alt="userface" class="img-rounded" src="<?=$this->gravatarLink($member['User']['email'], 30)?>" width="30" height="30"/>
                    <?=$member['User']['userName']?>
                </a>
            </li>
        <?endforeach;?>
        </ul>
        <?endif;?> 
    </div>

    <script id="side-event-list" type="text/x-tmpl" data-url="<?=$this->uri('/group/' . $this->item['groupKey'] . '/event/', array(/*'rows' => 10*/))?>">
        <div class="page-header border-header">
            <h4>Group Events  ({% if(o.paginator) { %}{%=o.paginator.rowCount%}{% } else { %} 0 {% } %})</h4>
        </div>
        <div class="side-event-list">
            {% if(o.items.length > 0) { %}
                {% for (var i=0, item; item=o.items[i]; i++) { %}
                    <div class="item">
                        <a href="<?=$this->uri('/event/')?>{%=item.urlName%}" title="" class="">
                            {% if(item.File) { %}
                                    <img src="{%=eva.thumb(item.File.Thumb, 'c_fill,h_50,w_50')%}" alt="{%=item.title%}" width="50" height="50" class="item-absolute imgdelay figure userface" />
                            {% }else{ %}
                                    <img src="{%=eva.s('/assets/module/epic/img/event-default.jpg')%}" alt="" width="50" height="50" class="item-absolute imgdelay figure userface" />
                            {% } %}
                        </a>
                        <div class="item-inline item-text">
                            <div class="text-content">
                                <div class="item-title">
                                    <a href="<?=$this->uri('/event/')?>{%=item.urlName%}">{%=item.title%}</a>
                                </div>
                            </div>
                        </div>
                    </div>
                    {% } %}
                {% } %}
        </div>
    </script>

    <div class="page-header">
        <small class="pull-right"><a href="<?=$this->uri('/my/friend/')?>">View All</a></small>
        <h4 class="txt-bold">Group Albums (20)</h4>
    </div>
    <div class="side-album-list">
        <ul class="thumbnails">
            <?for($i = 0; $i < 8; $i++):?>
            <li>
            <a class="thumbnail" href="#">
                <img src="<?=$this->link('/src/epic/css/img/food.jpg')?>" alt="" class="img-rounded" width="70" height="70" />
            </a>
            </li>
            <?endfor;?>
        </ul>
    </div>

    <script id="group-ranks" type="text/x-tmpl" data-url="<?=$this->uri('/data/group/',array('rows' => 5, 'order' => 'memberdesc'))?>">
    <div class="page-header border-header">
        <h4>Group Ranks</h4>
    </div>
    <div class="group-ranks">
        <ul>
        {% if(o.items.length > 0) { %}
            {% for (var i=0, item; item=o.items[i]; i++) { %}
            <li>
            <em class="ranknum rank{%=i+1%}">{%=i+1%}</em>
            <div class="media">
                <a class="pull-left" href="<?=$this->uri('/group/')?>{%=item.groupKey%}">
                            {% if(item.File) { %}
                                    <img src="{%=eva.thumb(item.File.Thumb, 'c_fill,h_50,w_50')%}" alt="{%=item.title%}" width="50" height="50" class="media-object img-rounded" />
                            {% }else{ %}
                                    <img src="{%=eva.s('/assets/module/epic/img/event-default.jpg')%}" alt="" width="50" height="50" class="media-object img-rounded" />
                            {% } %}
                </a>
                <div class="media-body">
                    <h4 class="media-heading"><a class="pull-left" href="<?=$this->uri('/group/')?>{%=item.groupKey%}">{%=item.groupName%}</a></h4>
                    <div class="media">
                        <div class="row">
                            <span class="span1"><span class="highlight txt-bold">123</span> Topics</span>
                            <span class="highlight txt-bold">{%=item.Count.memberCount%}</span> Members
                        </div>
                    </div>
                </div>
            </div>
            </li>
            {% } %}
        {% } %}
        </ul>
    </div>
    </script>

     <?=$this->widget('Epic', 'components/ad_group')?>
</div><!--right side end-->
