<?
$joinForm = new Group\Form\GroupUserForm();
$joinForm
->setView($this)
->setMethod('post')
->setAction($this->uri('/group/join/'))
->prepare();

$unjoinForm = clone $joinForm;
$unjoinForm->setMethod('delete');
?>                    
<div class="groupcard media">
    <a class="pull-left" href="<?=$this->uri('/group/' . $this->item['groupKey']);?>">
        <?if($this->item['File']):?>
        <img alt="group" class="media-object" src="<?=$this->thumb($this->item['File'][0]['Thumb'], array('c_fill', 'h_130', 'w_130'))?>" width="130" />
        <?else:?>
        <img alt="group" class="media-object" src="<?=$this->assets('/module/epic/img/event-default-l.jpg')?>" width="130" />
        <?endif?>
    </a>
    <div class="media-body">
        <h4 class="media-heading"><a href="<?=$this->uri('/group/' . $this->item['groupKey']);?>"><?=$this->item['groupName']?></a></h4>
        <div class="media typo">
            <div class="content"><?=$this->item['Text']['content']?></div>
            <div class="row ">
                <span class="span2 summary"><span class="highlight"><?=$this->item['Count']['memberCount']?></span>Members</span>
                <span class="span2 summary"><span class="highlight"><?=$this->item['PostCount']['postCount']?></span>Discussion</span>
                <span class="span1">
                    <?if(isset($this->item['Join']) && $this->item['Join']['user_id'] == $this->item['user_id']):?>
                    <?elseif(isset($this->item['Join']) && $this->item['Join'] && $this->item['Join']['user_id'] != $this->item['user_id']):?>
                    <form <?=$this->formAttr($unjoinForm)?>>
                        <?=$unjoinForm->restful();?>
                        <?=$unjoinForm->helper('group_id', 'formHidden', array('class' => '', 'value' => $this->item['id']))?>
                        <?=$unjoinForm->helper('user_id', array('class' => ''))?>
                        <?=$this->callback()?>
                        <button class="btn btn-small item-action-main btn btn-gray icon-minus-sign"> <?=$this->_('Quit')?></button>
                    </form>
                    <?elseif($this->item['memberEnable'] && ($this->item['memberLimit'] > $this->item['Count']['memberCount'] || $this->item['memberLimit'] == 0)):?>
                    <form <?=$this->formAttr($joinForm)?>>
                        <?=$joinForm->restful();?>
                        <?=$joinForm->helper('group_id', 'formHidden', array('class' => '', 'value' => $this->item['id']))?>
                        <?=$joinForm->helper('user_id', array('class' => ''))?>
                        <?=$this->callback()?>
                        <button class="btn btn-small item-action-main btn btn-gray icon-plus"> <?=$this->_('Join')?></button>
                    </form>
                    <?endif?>  
                </span>
                <?if(count($this->members) > 1 && $this->user['id'] == $this->item['user_id']):?>
                <a href="<?=$this->uri('/group/' . $this->item['groupKey'] . '/sendmail/')?>" class="btn btn-small btn-gray"><i class="icon-plus"></i> Mail To Group Members</a>
                <?endif;?>
            </div>
        </div>
    </div>
</div>

<div class="group-nav">
    <?$path = $this->getHelperPluginManager()->getServiceLocator()->get('request')->getUri()->getPath();?>
    <?if(strpos($path, 'event')):?>
    <a href="<?=$this->uri('/group/' . $item['groupKey'] . '/event/create')?>" class="btn btn-gray pull-right"><i class="icon-plus"></i> <?=$this->_('Schedule an Event')?></a>
    <?elseif(strpos($path, 'album')):?>
    <?else:?>
    <a href="<?=$this->uri('/group/' . $item['groupKey'] . '/blog/create')?>" class="btn btn-gray pull-right"><i class="icon-plus"></i> <?=$this->_('Create New Discussion')?></a>
    <?endif?>
    <ul class="nav nav-tabs group-tab">
        <li data-highlight-url="(^/group/[a-z0-9A-Z]+/?$)|^/group/[a-z0-9A-Z]+/blog/"><a href="<?=$this->uri('/group/' . $item['groupKey'])?>">Forum</a></li>
        <li data-highlight-url="^/group/[a-z0-9A-Z]+/event/" ><a href="<?=$this->uri('/group/' . $item['groupKey'] . '/event/')?>">Events</a></li>
        <li data-highlight-url="^/group/[a-z0-9A-Z]+/album/"><a href="<?=$this->uri('/group/' . $item['groupKey'] . '/album/')?>">Albums</a></li>
        <?if(count($this->members) > 1 && $this->user['id'] == $this->item['user_id']):?>
        <li data-highlight-url="^/group/[a-z0-9A-Z]+/sendmail/"><a href="<?=$this->uri('/group/' . $item['groupKey'] . '/sendmail/')?>">Send Mail</a></li>
        <?endif;?>
    </ul>
</div>
