                   <div class="groupcard media">
                        <a class="pull-left" href="#">
                            <img alt="group" src="https://lh6.googleusercontent.com/-lD5DMaTz1ng/UIyuunNHTbI/AAAAAAAARoo/b1H0tDTIy30/s144-p/P8100165.jpg" width="130" height="130" class="media-object"/>
                        </a>
                        <div class="media-body">
                            <h4 class="media-heading"><a href=""><?=$item['groupName']?></a></h4>
                            <div class="media typo">
                                <div class="content"><?=$item['Text']['content']?></div>
                                <div class="row ">
                                    <span class="span2 summary"><span class="highlight">12345</span>Members</span>
                                    <span class="span2 summary"><span class="highlight">12345</span>Topics</span>
                                    <span class="span1"><a href="<?=$this->uri('/groups/join/')?>" class="btn btn-gray"><i class="icon-plus"></i> Join</a></span>
                                </div>

                            </div>
                        </div>
                    </div>
