<div class="profile-side">
    <div class="calendar calendar-mini">
        <div class="calendar-wrap">

        </div>
        <div class="calendar-caption">
            <i class="icon-stop green"></i> Coming Events
            <i class="icon-stop brown"></i> Finished Events
            <i class="icon-stop orange"></i> Today
        </div>
    </div><!--calendar end-->

    <div class="side-subscription">
        <p>Subscribe here to receive our free e-newsletters and notifications:</p>
        <button class="btn btn-orange btn-block"><i class="icon-mini icon-envelope-alt"></i> Subscription Newsletters</button>
    </div>

<script id="side-friend-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/friend/', array('user_id' => $this->user['id']))?>">
<div class="page-header border-header">
    <small class="pull-right"><a href="<?=$this->uri('/my/friend/')?>">View All</a></small>
    <h4>Friends ({% if(o.paginator) { %}{%=o.paginator.rowCount%}{% } else { %} 0 {% } %})</h4>
</div>
<div class="side-user-list">
    {% if(o.items.length > 0) { %}
    <ul class="thumbnails">
    {% for (var i=0, item; item=o.items[i]; i++) { %}
        <li>
        <a class="thumbnail" href="<?=$this->uri('/user/')?>{%=item.User.userName%}">
            <img src="http://www.gravatar.com/avatar/{%=item.User.EmailHash%}?size=50" alt="{%=item.User.userName%}" class="img-rounded" width="30" height="30" />
        </a>
        </li>
    {% } %}
    </ul>
    {% } %}
</div>
</script>

<?if(0):?>
    <div class="page-header border-header">
        <small class="pull-right"><a href="<?=$this->uri('/my/friend/')?>">View All</a></small>
        <h4>My Friends (123)</h4>
    </div>
    <div class="side-user-list">
        <ul class="thumbnails">
            <?for($i = 0; $i < 16; $i++):?>
            <li>
            <a class="thumbnail" href="#">
                <img src="<?=$this->link('/src/epic/css/img/face-04.jpg')?>" alt="" class="img-rounded" width="30" height="30" />
            </a>
            </li>
            <?endfor;?>
        </ul>
    </div>
<?endif?>

<script id="side-blog-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/blog/', array('user_id' => $this->user['id']))?>">
<div class="page-header border-header">
    <small class="pull-right"><a href="<?=$this->uri('/user/' . $this->user['userName'] . '/blog/')?>">View All</a></small>
    <h4>Blogs  ({% if(o.paginator) { %}{%=o.paginator.rowCount%}{% } else { %} 0 {% } %})</h4>
</div>
<div class="side-blog-list">
{% if(o.items.length > 0) { %}
{% for (var i=0, item; item=o.items[i]; i++) { %}
<div class="item">
    <a href="<?=$this->uri('/user/')?>{%=item.User.userName%}" title="" class="item-absolute imgdelay figure userface">
        {% if(item.User.Avatar) { %}
        <img src="{%=eva.thumb(item.User.Avatar.Thumb, 'c_fill,h_50,w_50')%}" alt="" class="img-rounded" width="50" height="50" />
        {% } else { %}
        <img src="<?=$this->assets('/module/epic/img/default_avatar.png')?>" alt="" class="img-rounded" width="50" height="50" />
        {% } %}
    </a>
    <div class="item-inline item-text">
        <div class="text-content">
            <div class="item-title">
                <a href="<?=$this->uri('/user/')?>{%=item.User.userName%}/blog/{%=item.urlName%}">{%=item.title%}</a>
            </div>
            <p>{%=item.Text.Preview%}</p>
        </div>
    </div>
</div>
{% } %}
{% } %}
</div>
</script>

    <?if(0):?>
    <div class="page-header border-header">
        <small class="pull-right"><a href="#">View All</a></small>
        <h4>My Blog (123)</h4>
    </div>
    <div class="side-blog-list">
        <?for($i = 0; $i < 10; $i++):?>
        <div class="item">
            <a href="" title="" class="item-absolute imgdelay figure userface"><img src="<?=$this->link('/src/epic/css/img/face-01.jpg')?>" alt="" class="img-rounded" width="50" height="50" /></a>
            <div class="item-inline item-text">
                <div class="text-content">
                    <div class="item-title">
                        <a href="#">Blog title test
                            Blog title test</a>
                    </div>
                    <p>Post content test</p>
                </div>
            </div>
        </div>
        <?endfor?>
    </div><!--activity-list end-->
    <?endif?>
<script id="side-event-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/event/', array('user_id' => $this->user['id']))?>">
<div class="page-header border-header">
    <small class="pull-right"><a href="<?=$this->uri('/user/' . $this->user['userName'] . '/events/')?>">View All</a></small>
    <h4>Events  ({% if(o.paginator) { %}{%=o.paginator.rowCount%}{% } else { %} 0 {% } %})</h4>
</div>
<div class="side-event-list">
{% if(o.items.length > 0) { %}
{% for (var i=0, item; item=o.items[i]; i++) { %}
<div class="item">
    <a href="<?=$this->uri('/user/')?>{%=item.User.userName%}" title="" class="item-absolute imgdelay figure userface"><img src="http://www.gravatar.com/avatar/{%=item.User.EmailHash%}?size=50" alt="" class="img-rounded" width="50" height="50" /></a>
    <div class="item-inline item-text">
        <div class="text-content">
            <div class="item-title">
                <a href="<?=$this->uri('/event/')?>{%=item.urlName%}">{%=item.title%}</a>
            </div>
        </div>
    </div>
</div>
{% } %}
{% } %}
</div>
</script>
    <?if(0):?>
    <div class="page-header border-header">
        <small class="pull-right"><a href="#">View All</a></small>
        <h4>My Events (123)</h4>
    </div>
    <div class="side-blog-list">
        <?for($i = 0; $i < 10; $i++):?>
        <div class="item ">
            <a href="" title="" class="item-absolute imgdelay figure userface"><img src="<?=$this->link('/src/epic/css/img/face-01.jpg')?>" alt="" class="img-rounded" width="50" height="50" /></a>
            <div class="item-inline item-text">
                <div class="text-content">
                    <div class="item-title">
                        <a href="#">Event title test</a>
                    </div>
                    <p>Event Members: 50</p>
                    <p>Event Time: <?=$this->datetime(time())?></p>
                </div>
            </div>
        </div>
        <?endfor?>
    </div><!--activity-list end-->
    <?endif?>

    <div class="page-header border-header">
        <small class="pull-right"><a href="#">View All</a></small>
        <h4>Albums</h4>
    </div>
    <div class="side-album-list">
        <ul class="thumbnails">
            <?for($i = 0; $i < 8; $i++):?>
            <li>
            <a class="thumbnail" href="#">
                <img src="<?=$this->link('/assets/module/epic/css/img/food.jpg')?>" alt="" class="img-rounded" width="70" height="70" />
            </a>
            </li>
            <?endfor;?>
        </ul>
    </div>
<script id="side-group-list" type="text/x-tmpl" data-url="<?=$this->uri('/data/group/', array('user_id' => $this->user['id'], 'rows' => 12))?>">
<div class="page-header border-header">
    <small class="pull-right"><a href="<?=$this->uri('/user/' . $this->user['userName'] . '/groups/')?>">View All</a></small>
    <h4>Groups  ({% if(o.paginator) { %}{%=o.paginator.rowCount%}{% } else { %} 0 {% } %})</h4>
</div>
<div class="side-group-list">
    <ul class="thumbnails">
    {% if(o.items.length > 0) { %}
    {% for (var i=0, item; item=o.items[i]; i++) { %}
        <li>
            <a class="thumbnail" href="<?=$this->uri('/group/')?>{%=item.groupKey%}">
                {% if(item.File) { %}
                    <img src="{%=eva.thumb(item.File.Thumb, 'c_fill,h_50,w_50')%}" alt="" width="50" height="50" class="item-absolute imgdelay figure userface" />
                {% }else{ %}
                    <img src="{%=eva.s('/assets/module/epic/img/event-default.jpg')%}" alt="" width="50" height="50" class="item-absolute imgdelay figure userface" />
                {% } %}
            </a>
        </li>
    {% } %}
    {% } %}
        </ul>
    </div>
</div>
</script>
    <?if(0):?>
    <div class="page-header border-header">
        <small class="pull-right"><a href="#">View All</a></small>
        <h4>My Groups</h4>
    </div>
    <div class="side-group-list">
        <ul class="thumbnails">
            <?for($i = 0; $i < 5; $i++):?>
            <li>
            <a class="thumbnail" href="#">
                <img src="<?=$this->link('/src/epic/css/img/group.jpg')?>" alt="" class="img-rounded" width="50" height="50" />
            </a>
            </li>
            <?endfor;?>
        </ul>
    </div>
    <?endif;?>
    <?if($this->viewAsGuest):?>
    <?=$this->widget('Epic', 'components/ad_user')?>
    <?else:?>
    <?=$this->widget('Epic', 'components/ad_home')?>
    <?endif?>
</div><!--profile-side end-->
