<?
$user = $this->user;
$viewAsGuest = $this->viewAsGuest;
$form = new Activity\Form\FollowForm();
$form
->setView($this)
->useSubFormGroup()
->setMethod('post')
->setAction($this->uri('/activity/follow'))
->prepare();

?>
<div class="thumbnail profile-face">
    <img alt="userface" src="<?=$this->gravatar($user['email'], 175)?>" width="175" height="175">
    <div class="caption">
        <a class="highlight highlight-large" href="<?=$this->uri('/my/friend/')?>"><?=$user['FriendsCount']['friendsCount']?></a> Friends
    </div>
</div>
<div class="profile-intro">
    <div class="profile-title">
        <h2><?=$user['userName']?></h2>
        <small class="profile-level">Professional  <a href="<?=$this->uri('/account/membership/')?>" title="VIP User"><i class="icon-trophy"></i></a></small>
    </div>

    <table class="table-condensed">
        <tbody>
            <tr>
                <td>Title: 
                    <?if($user['gender'] =='male'):?>
                        Mr.
                    <?elseif($user['gender'] == 'femail'):?>
                        Miss.
                    <?endif?>
                    
                    <?if($user['firstName'] && $user['lastName']):?>
                    <?=$user['lastName']?> <?=$user['firstName']?>
                    <?endif?>
                </td>
                <td colspan="2">Website : 
                    <?if($user['Profile']['site']):?>
                    <a href="<?=$user['Profile']['site']?>"><?=$user['Profile']['site']?></a>
                    <?endif?>
                </td>
            </tr>
            <tr>
                <td>Location : 
                    <?if($user['Profile']['city']):?>
                    <?=$user['Profile']['city']?>
                    <?endif?>
                    <?if($user['Profile']['city']):?>
                    <?=$user['Profile']['province']?>
                    <?endif?>
                    <?if($user['Profile']['country']):?>
                    <?=$this->locale('territory', $user['Profile']['country'])?>
                    <?endif?>
                </td>
                <td>Birthday : 
                    <?if($user['Profile']['birthday'] && $user['Profile']['birthday'] != '0000-00-00'):?>
                    <?=$user['Profile']['birthday']?>
                    <?else:?>
                    Secret
                    <?endif?>
                </td>
                <td>Events : <a href="">0</a> Times</td>
            </tr>
            <tr>
                <td colspan="3">Bio : 
                    <?if($user['Profile']['bio']):?>
                    <?=$user['Profile']['bio']?>
                    <?endif?>
                </td>
            </tr>
            <tr>
                <?if($viewAsGuest):?>
                <td colspan="2">
                    <form <?=$this->formAttr($form)?> class="follow-form">
                        <?=$form->restful();?>
                        <?=$form->helper('user_id', array('class' => '', 'value' => $this->user['id']))?>
                        <?=$form->helper('follower_id', array('class' => ''))?>
                        <?=$this->callback()?>
                        <button class="btn btn-brown btn-mini" href="<?=$this->uri('/activity/follow/')?>"><i class="icon-mini icon-plus"></i> Follow</button>
                    </form>
                    <a class="btn btn-gray btn-mini" href="<?=$this->uri('/messages/send/' . $this->user['userName'])?>"><i class="icon-mini icon-envelope-alt"></i> Send Message</a>
                </td>
                <td class="social">
                <?else:?>
                <td>
                    <a class="btn btn-gray btn-mini" href="<?=$this->uri('/user/' . $this->user['userName'])?>"><i class="icon-mini icon-eye-open"></i> View As Guest</a>
                </td>
                <td colspan="2" class="social">
                <?endif?>
                    Social Networking : 
                    <a href="#"><i class="icon-facebook-sign"></i></a>
                    <a href="#"><i class="icon-pinterest"></i></a>
                    <!--
                    <a href="#"><i class="icon-twitter"></i></a>
                    <a href="#"><i class="icon-google-plus"></i></a>
                    -->
                </td>
            </tr>
        </tbody>
    </table>
</div><!--profile-intro end-->
