<ul class="nav nav-tabs nav-stacked">
    <li data-highlight-url="^/messages.*"><a href="<?=$this->uri('/messages/')?>"><i class="icon-envelope-alt"></i> My Messages</a></li>
    <li data-highlight-url="^/my/event/?$"><a href="<?=$this->uri('/my/event/')?>"><i class="icon-calendar"></i> My Events</a></li>
    <li data-highlight-url="^/my/friend/?$"><a href="<?=$this->uri('/my/friend/')?>"><i class="icon-user"></i> My Friends</a></li>
    <li data-highlight-url="^/my/blog/?$"><a href="<?=$this->uri('/my/blog/')?>"><i class="icon-paste"></i> My Blog</a></li>
    <li data-highlight-url="^/my/album/?$"><a href="<?=$this->uri('/my/album/')?>"><i class="icon-picture"></i> My Albums</a></li>
    <li data-highlight-url="^/my/group/?$"><a href="<?=$this->uri('/my/group/')?>"><i class="icon-group"></i> My Groups</a></li>
</ul>
