<div class="side-blog-list">
    <div class="page-header border-header">
        <small class="pull-right"><a href="#">View All</a></small>
        <h4>My Blog (123)</h4>
    </div>
    <?for($i = 0; $i < 10; $i++):?>
    <div class="item ">
        <a href="" title="" class="item-absolute imgdelay figure userface"><img src="<?=$this->link('/src/epic/css/img/face-01.jpg')?>" alt="" class="img-rounded" width="50" height="50" /></a>
        <div class="item-inline item-text">
            <div class="text-content">
                <div class="item-title">
                    <a href="#">Blog title test
                        Blog title test</a>
                </div>
                <p>Post content test</p>
            </div>
        </div>
    </div>
    <?endfor?>
</div>
