<ul class="nav nav-tabs nav-stacked">
    <li data-highlight-url="^/message.*"><a href="<?=$this->uri('/message/')?>"><i class="icon-envelope-alt"></i> My Messages</a></li>
    <li data-highlight-url="^/user/my/event/?$"><a href="<?=$this->uri('/user/my/event/')?>"><i class="icon-calendar"></i> My Events</a></li>
    <li data-highlight-url="^/user/my/friend/?$"><a href="<?=$this->uri('/user/my/friend/')?>"><i class="icon-user"></i> My Friends</a></li>
    <li data-highlight-url="^/user/my/blog/?$"><a href="<?=$this->uri('/user/my/blog/')?>"><i class="icon-paste"></i> My Blog</a></li>
    <li data-highlight-url="^/user/my/album/?$"><a href="<?=$this->uri('/user/my/album/')?>"><i class="icon-picture"></i> My Albums</a></li>
    <li data-highlight-url="^/user/my/group/?$"><a href="<?=$this->uri('/user/my/group/')?>"><i class="icon-group"></i> My Groups</a></li>
</ul>
