<?
$this->headTitle('Epicurissimo compass | communauté privé pour les pros et les connaisseur du gastronomie et vin', 'SET');
$form = new Epic\Form\ProfessionalForm();
$form->useSubFormGroup()->setView($this);
$form->setMethod('post');
$form->setAction($this->uri('/reg/'));
?>
<div class="container">
    <div id="singletitle" class="page-header typo img">
        <!--<h1>Sign Up <span class="highlight">Connoisseur</span></h1>-->
        <h1><img src="<?=$this->link('/src/epic/css/img/title-' . $this->id . '.png')?>" alt="logo"></h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="span5">
            <form id="signupform" <?=$this->formAttr($form)?> class="form">
                <?=$form->restful();?>
                <?=$form->helper('id');?>
                <fieldset class="form-horizontal">
                 <div class="control-group <?=$form->isError('screenName') ? 'error' : '';?>">
    <?=$form->helper('screenName', 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper('screenName', array('class' => ''))?>        
        <div class="help-block"><?=$form->helper('screenName', 'formElementErrors')?></div>
    </div>
</div>
<div class="control-group <?=$form->isError('gender') ? 'error' : '';?>">
    <?=$form->helper('gender', 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper('gender', 'formSelect', array('class' => ''))?>        
        <div class="help-block"><?=$form->helper('gender', 'formElementErrors')?></div>
    </div>
</div>
<div class="control-group <?=$form->isError('email') ? 'error' : '';?>">
    <?=$form->helper('email', 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper('email', array('class' => ''))?>        
        <div class="help-block"><?=$form->helper('email', 'formElementErrors')?></div>
    </div>
</div>
<?=$form->helper(array('ProfessionalProfile', 'user_id'), array('class' => ''))?>
<div class="control-group <?=$form->isError(array('ProfessionalProfile', 'firstName')) ? 'error' : '';?>">
    <?=$form->helper(array('ProfessionalProfile', 'firstName'), 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper(array('ProfessionalProfile', 'firstName'), array('class' => ''))?>        
        <div class="help-block"><?=$form->helper(array('ProfessionalProfile', 'firstName'), 'formElementErrors')?></div>
    </div>
</div>
<div class="control-group <?=$form->isError(array('ProfessionalProfile', 'lastName')) ? 'error' : '';?>">
    <?=$form->helper(array('ProfessionalProfile', 'lastName'), 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper(array('ProfessionalProfile', 'lastName'), array('class' => ''))?>        
        <div class="help-block"><?=$form->helper(array('ProfessionalProfile', 'lastName'), 'formElementErrors')?></div>
    </div>
</div>
<div class="control-group <?=$form->isError(array('ProfessionalProfile', 'birthday')) ? 'error' : '';?>">
    <?=$form->helper(array('ProfessionalProfile', 'birthday'), 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper(array('ProfessionalProfile', 'birthday'), array('class' => ''))?>        
        <div class="help-block"><?=$form->helper(array('ProfessionalProfile', 'birthday'), 'formElementErrors')?></div>
    </div>
</div>
<div class="control-group <?=$form->isError(array('ProfessionalProfile', 'country')) ? 'error' : '';?>">
    <?=$form->helper(array('ProfessionalProfile', 'country'), 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper(array('ProfessionalProfile', 'country'), 'formSelect', array('class' => ''))?>        
        <div class="help-block"><?=$form->helper(array('ProfessionalProfile', 'country'), 'formElementErrors')?></div>
    </div>
</div>
<div class="control-group <?=$form->isError(array('ProfessionalProfile', 'hobbies')) ? 'error' : '';?>">
    <?=$form->helper(array('ProfessionalProfile', 'hobbies'), 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper(array('ProfessionalProfile', 'hobbies'), array('class' => ''))?>        
        <div class="help-block"><?=$form->helper(array('ProfessionalProfile', 'hobbies'), 'formElementErrors')?></div>
    </div>
</div>
<div class="control-group <?=$form->isError(array('ProfessionalProfile', 'bio')) ? 'error' : '';?>">
    <?=$form->helper(array('ProfessionalProfile', 'bio'), 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper(array('ProfessionalProfile', 'bio'), 'formTextarea', array('class' => ''))?>        
        <div class="help-block"><?=$form->helper(array('ProfessionalProfile', 'bio'), 'formElementErrors')?></div>
    </div>
</div>
<div class="control-group <?=$form->isError(array('ProfessionalProfile', 'school')) ? 'error' : '';?>">
    <?=$form->helper(array('ProfessionalProfile', 'school'), 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper(array('ProfessionalProfile', 'school'), array('class' => ''))?>        
        <div class="help-block"><?=$form->helper(array('ProfessionalProfile', 'school'), 'formElementErrors')?></div>
    </div>
</div>
<div class="control-group <?=$form->isError(array('ProfessionalProfile', 'degree')) ? 'error' : '';?>">
    <?=$form->helper(array('ProfessionalProfile', 'degree'), 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper(array('ProfessionalProfile', 'degree'), array('class' => ''))?>        
        <div class="help-block"><?=$form->helper(array('ProfessionalProfile', 'degree'), 'formElementErrors')?></div>
    </div>
</div>
<div class="control-group <?=$form->isError(array('ProfessionalProfile', 'industryIndustrie')) ? 'error' : '';?>">
    <?=$form->helper(array('ProfessionalProfile', 'industryIndustrie'), 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper(array('ProfessionalProfile', 'industryIndustrie'), 'formSelect', array('class' => ''))?>        
        <div class="help-block"><?=$form->helper(array('ProfessionalProfile', 'industryIndustrie'), 'formElementErrors')?></div>
    </div>
</div>
<div class="control-group <?=$form->isError(array('ProfessionalProfile', 'phoneBusiness')) ? 'error' : '';?>">
    <?=$form->helper(array('ProfessionalProfile', 'phoneBusiness'), 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper(array('ProfessionalProfile', 'phoneBusiness'), array('class' => ''))?>        
        <div class="help-block"><?=$form->helper(array('ProfessionalProfile', 'phoneBusiness'), 'formElementErrors')?></div>
    </div>
</div>
<div class="control-group <?=$form->isError(array('ProfessionalProfile', 'address')) ? 'error' : '';?>">
    <?=$form->helper(array('ProfessionalProfile', 'address'), 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper(array('ProfessionalProfile', 'address'), array('class' => ''))?>        
        <div class="help-block"><?=$form->helper(array('ProfessionalProfile', 'address'), 'formElementErrors')?></div>
    </div>
</div>
<div class="control-group <?=$form->isError(array('ProfessionalProfile', 'howCouldWehelpYou')) ? 'error' : '';?>">
    <?=$form->helper(array('ProfessionalProfile', 'howCouldWehelpYou'), 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper(array('ProfessionalProfile', 'howCouldWehelpYou'), 'formMultiCheckbox', array('class' => ''))?>        
        <div class="help-block"><?=$form->helper(array('ProfessionalProfile', 'howCouldWehelpYou'), 'formElementErrors')?></div>
    </div>
</div>
<div class="control-group <?=$form->isError(array('ProfessionalProfile', 'yourExpertise')) ? 'error' : '';?>">
    <?=$form->helper(array('ProfessionalProfile', 'yourExpertise'), 'label', array('class' => 'control-label'))?>
    <div class="controls">
        <?=$form->helper(array('ProfessionalProfile', 'yourExpertise'), 'formMultiCheckbox', array('class' => ''))?>        
        <div class="help-block"><?=$form->helper(array('ProfessionalProfile', 'yourExpertise'), 'formElementErrors')?></div>
    </div>
</div>
                    <div class="control-group">
                        <div class="controls">
                            <label class="checkbox">
                                <input type="checkbox"> By clicking Sign Up, you agree to our <a href="<?=$this->uri('/pages/terms')?>" target="_blank">Terms &amp; Conditions</a>.
                            </label>
                            <button type="submit" class="btn btn-large">Sign Up</button>
                        </div>
                    </div>

                </fieldset>
            </form>
        </div>

        <div class="span7">
            <div class="well typo">
                <?$locale = \Eva\Api::_()->getServiceManager()->get('translator')->getLocale();?>
                <?if($locale == 'en'):?>

                <div class="page-header">
                    <h1>You work as</h1>
                </div>
                <ul>
                    <li>Chefs, Resaurateur, Sommelier, Mixologist</li>
                    <li>Gourmet Food, Wine and spirit producers</li>
                    <li>Gastronomic Critics, Journalists</li>
                    <li>Other Relevant Professions</li>
                </ul>



                <div class="page-header">
                    <h1>How you can benefit from joining us?</h1>
                </div>

                <ul>
                    <li>Showcase Your Work</li>
                    <li>Career Opportunities</li>
                    <li>Network : Access to 10,000+decision makers</li>
                    <li>Events : Exhibitions, shows, receptions…</li>
                    <li>Inspiration : Exchange idea with other professionals</li>
                    <li>Vision : trends and insight of your industry</li>
                </ul>
                <?elseif($locale == 'fr'):?>

                <div class="page-header">
                    <h1>Vous travaillez comme</h1>
                </div>
                <ul>
                    <li>Chefs, Restaurateur, Sommelier, Mixologists</li>
                    <li>Producteurs des aliments gourmet, des vins et des spiritueux</li>
                    <li>Les critiques gastronomiques, journalistes</li>
                    <li>D'autres professions concernées</li>
                </ul>


                <div class="page-header">
                    <h1>Comment vous pouvez profiter de vous joindre à nous?</h1>
                </div>

                <ul>
                    <li>Présentez votre travail</li>
                    <li>Carrière </li>
                    <li>Réseau professionnel: Accès à 10.000 décideurs +</li>
                    <li>Événements</li>
                    <li>S’inspirer: Échange idée avec d'autres professionnels</li>
                    <li>Conseille:</li>
                </ul>


                <?elseif($locale == 'zh'):?>

                <div class="page-header">
                    <h1>如果您的职业是：</h1>
                </div>
                <ul>
                    <li>厨师，调酒师，侍酒师</li>
                    <li>美食家，红酒或洋酒制造商</li>
                    <li>美食评论家，行业记者</li>
                    <li>或其他与本行业相关的职业</li>
                </ul>

                <div class="page-header">
                    <h1>加入我们，您将受益于：</h1>
                </div>


                <ul>
                    <li>更多曝光：展示您的工作</li>
                    <li>更多机会：帮助您找到更多职业机会</li>
                    <li>更多人脉：近距离接触超过10,000+名行业决策者</li>
                    <li>更多活动：组织和参与展会、活动或高端酒会</li>
                    <li>更多创新：将您的想法与其他职业人士分享</li>
                    <li>更多视野：洞悉及讨论行业发展趋势</li>
                </ul>
                <?elseif($locale == 'zh_TW'):?>

                <div class="page-header">
                    <h1>如果您的職業是：</h1>
                </div>
                <ul>
                    <li>廚師，調酒師，侍酒師</li>
                    <li>美食家，紅酒或洋酒制造商</li>
                    <li>美食評論家，行業記者</li>
                    <li>或其他與本行業相關的職業</li>
                </ul>
                <div class="page-header">
                    <h1>加入我們，您將受益於：</h1>
                </div>


                <ul>
                    <li>更多曝光：展示您的工作</li>
                    <li>更多機會：幫助您找到更多職業機會</li>
                    <li>更多人脈：近距離接觸超過10,000+名行業決策者</li>
                    <li>更多活動：組織和參與展會、活動或高端酒會</li>
                    <li>更多創新：將您的想法與其他職業人士分享</li>
                    <li>更多視野：洞悉及討論行業發展趨勢</li>
                </ul>

                <?endif?>
            </div>
        </div>

    </div>
</div>


