<?
$title = 'Groups';
$this->headTitle($title, 'SET');
$user = $this->user;
$item = $this->event;
?>

<div class="container">
    <header class="group-header">
        <?=$this->widget('Epic', 'widgets/groupnav', $this->vars())?> 
    </header>
</div>

<div class="container">
    <div class="page-bg">
        <div class="row">

            <div class="span8">
                <div class="group-main">

                    <?=$this->widget('Epic', 'widgets/groupcard', $this->vars())?>  
  
                                <div class="album-list">
                                    <?for($i=0;$i<4;$i++):?>
                                    <div class="row-fluid stack-row">
                                        <?for($j=0;$j<4;$j++):?>
                                        <div class="span3">
                                            <div class="stack">	
                                                <a href="">
                                                    <img src="<?=$this->assets('/module/epic/img/album-default.png')?>" width="180" alt="" />
                                                </a>
                                            </div>
                                        </div>
                                        <?endfor;?>
                                    </div>
                                    <?endfor;?>
                                </div><!--album-list end-->

                </div><!--group main end-->
            </div><!--page main left end-->
            <div class="span4">
                <?=$this->widget('Epic', 'widgets/groupside', $this->vars())?>  
            </div>

        </div><!--page main right end-->
    </div><!-- page-bg end-->
</div><!--container end-->
