<?
$title = 'Groups';
$this->headTitle($title, 'SET');
$user = $this->user;
$item = $this->item;
$event = $this->event;

if($this->form){
	$form = $this->form;
} else {
    if($event['id']) {
        $form = new Epic\Form\EventEditForm();
        $form->setAction($this->uri('/event/edit/'));

    } else {
        $form = new Epic\Form\EventCreateForm();
        $form->setAction($this->uri('/data/group/event/'));
    }
}
$form->useSubFormGroup()
     ->setMethod($event['id'] ? 'put' : 'post')
     ->setView($this)
     ->bind($event)
     ->prepare();
?>

<div class="container">
    <header class="group-header">
        <?=$this->widget('Epic', 'widgets/groupnav', $this->vars())?> 
    </header>
</div>

<div class="container">
    <div class="page-bg">
        <div class="row">

            <div class="span8">
                <div class="group-main">

                    <?=$this->widget('Epic', 'widgets/groupcard', $this->vars())?>  

                   <form <?=$this->formAttr($form)?> class="form event-create-form">
                                    <?=$form->restful();?>
                                    <?=$form->helper('id');?>
                                    <fieldset class="">
                                        <div class="control-group <?=$form->isError('title') ? 'error' : '';?>">
                                            <?=$form->helper('title', 'label', array('class' => 'control-label'))?>
                                            <div class="controls docs-input-sizes">
                                                <?=$form->helper('title', array('class' => 'span6'))?>
                                                <div class="help-block"><?=$form->helper('title', 'formElementErrors')?></div>
                                            </div>
                                        </div>

                                        <div class="control-group <?=$form->isError('city') ? 'error' : '';?>">
                                            <?=$form->helper('city', 'label', array('class' => 'control-label'))?>
                                            <div class="controls">
                                                <?=$form->helper('city', 'formSelect', array('class' => 'select2 input-large', 'value' => $this->params['city']))?>        
                                                <div class="help-block"><?=$form->helper('city', 'formElementErrors')?></div>
                                            </div>
                                        </div>
                                        
                                        <div class="control-group <?=$form->isError('memberEnable') ? 'error' : '';?>">
                                            <?=$form->helper('memberEnable', 'label', array('class' => 'control-label'))?>
                                            <div class="controls">
                                                <?=$form->helper('memberEnable', 'formSelect', array('class' => ''))?>        
                                                <div class="help-block"><?=$form->helper('memberEnable', 'formElementErrors')?></div>
                                            </div>
                                        </div>                   
                                       
                                         <div class="control-group <?=$form->isError('memberLimit') ? 'error' : '';?>">
                                            <?=$form->helper('memberLimit', 'label', array('class' => 'control-label'))?>
                                            <div class="controls">
                                                <?=$form->helper('memberLimit', array('class' => ''))?>        
                                                <div class="help-block"><?=$form->helper('memberLimit', 'formElementErrors')?></div>
                                            </div>
                                        </div>

                                        <div class="control-group <?=$form->isError('location') ? 'error' : '';?>">
                                            <?=$form->helper('location', 'label', array('class' => 'control-label'))?>
                                            <div class="controls">
                                                <?=$form->helper('location', array('class' => 'span6'))?>        
                                                <div class="help-block"><?=$form->helper('location', 'formElementErrors')?></div>
                                            </div>
                                        </div>  

                                        <div class="control-group">
                                            <label>Event Theme Photo</label>
                                            <?if($item['File']):?>
                                                <img id="post-image" src="<?=$this->thumb($item['File'][0]['Thumb'], array('h_250'))?>" alt="" />
                                            <?else:?>
                                                <img id="post-image" src="http://placehold.it/260x180" alt="" />
                                            <?endif?>
                                            <div class="row">
                                                <div class="span4">
                                                    <?=$this->widget('File', 'file/upload')?>
                                                </div>
                                            </div>
                                        </div>  

                                        <div class="datepair row">
                                        <div class="control-group <?=$form->isError('startDay') ? 'error' : '';?>  controls-row span3">
                                            <?=$form->helper('startDay', 'label', array('class' => 'control-label'))?>
                                            <div class="controls">
                                                <?=$form->helper('startDay', array('class' => 'input-small date start', 'data-date-format' => 'yyyy-mm-dd'))?>        
                                                <?=$form->helper('startTime', array('class' => 'timepicker input-small time start', 'data-date-format' => 'yyyy-mm-dd'))?>        
                                                <div class="help-block"><?=$form->helper('startDay', 'formElementErrors')?></div>
                                                <div class="help-block"><?=$form->helper('startTime', 'formElementErrors')?></div>
                                            </div>
                                        </div>

                                        <div class="control-group <?=$form->isError('endDay') ? 'error' : '';?> controls-row span3">
                                            <?=$form->helper('endDay', 'label', array('class' => 'control-label'))?>
                                            <div class="controls">
                                                <?=$form->helper('endDay', array('class' => 'input-small date end', 'data-date-format' => 'yyyy-mm-dd'))?>        
                                                <?=$form->helper('endTime', array('class' => 'timepicker input-small time end', 'data-date-format' => 'yyyy-mm-dd'))?>        
                                                <div class="help-block"><?=$form->helper('endDay', 'formElementErrors')?></div>
                                                <div class="help-block"><?=$form->helper('endTime', 'formElementErrors')?></div>
                                            </div>
                                        </div>
                                        </div>

                                        <div class="control-group">
                                            <label>Event Categories</label>
                                            <div class="controls">
                                                <?foreach($form->get('CategoryEvent') as $subForm):?>
                                                <?$cate = $subForm->getCategory();if(!$cate){continue;}?>
                                                <label class="checkbox inline">
                                                    <?=$subForm->helper('category_id', 'formCheckbox', array(
                                                        'class' => '',
                                                        'checkedValue' => $cate['id'],
                                                        'checked' => $subForm->get('event_id')->getValue() ? true : false
                                                    ))?>
                                                    <?=$cate['categoryName']?>
                                                </label>
                                        <?endforeach?>
                                            </div>
                                        </div>

                                        <div class="control-group <?=$form->isError(array('Text', 'content')) ? 'error' : '';?>">
                                            <?=$form->helper(array('Text', 'content'), 'formLabel')?>
                                            <div id="editor-left" class="controls">
                                                <?=$form->helper(array('Text', 'content'), 'formTextarea', array('class' => 'span6 editor-html simple', 'rows' => '15',))?>
                                            </div>
                                            <div id="editor-right" class="markdown-preview"></div>
                                            <div class="help-block"><?=$form->helper(array('Text', 'content'), 'formElementErrors')?></div>

                                        </div>

                                        <div class="control-group <?=$form->isError('longitude') ? 'error' : '';?> hide">
                                            <?=$form->helper('longitude', 'label', array('class' => 'control-label'))?>
                                            <div class="controls">
                                                <?=$form->helper('longitude', array('class' => 'span3'))?>        
                                                <div class="help-block"><?=$form->helper('longitude', 'formElementErrors')?></div>
                                            </div>
                                        </div>  

                                        <div class="control-group <?=$form->isError('latitude') ? 'error' : '';?> hide">
                                            <?=$form->helper('latitude', 'label', array('class' => 'control-label'))?>
                                            <div class="controls">
                                                <?=$form->helper('latitude', array('class' => 'span3'))?>        
                                                <div class="help-block"><?=$form->helper('latitude', 'formElementErrors')?></div>
                                            </div>
                                        </div> 

                                        <div class="control-group <?=$form->isError('urlName') ? 'error' : '';?> hide">
                                            <?=$form->helper('urlName', 'label', array('class' => 'control-label'))?>
                                            <div class="controls">
                                                <?=$form->helper('urlName', array('class' => ''))?>        
                                                <div class="help-block"><?=$form->helper('urlName', 'formElementErrors')?></div>
                                            </div>
                                        </div>   

                                        <?if($this->hasModule('File')):?>
                                        <?=$form->helper(array('EventFile', 'file_id'), 'formHidden')?>
                                        <?endif?>

                                    </fieldset>
                                    <div class="form-actions">
                                        <button type="submit" class="btn btn-info btn-large"><?=$this->_('Publish');?></button>
                                    </div>
                                </form>


                </div><!--group main end-->
            </div><!--page main left end-->
            <div class="span4">
               <?=$this->widget('Epic', 'widgets/groupside', $this->vars())?>  
            </div>

        </div><!--page main right end-->
    </div><!-- page-bg end-->
</div><!--container end-->
