<?
$title = 'Groups';
$this->headTitle($title, 'SET');
$user = $this->user;
$items = $this->items;
?>

<div class="container">
    <header class="group-header">
        <?=$this->widget('Epic', 'widgets/groupnav', $this->vars())?> 
    </header>
</div>

<div class="container">
    <div class="page-bg">
        <div class="row">

            <div class="span8">
                <div class="group-main">

                    <?=$this->widget('Epic', 'widgets/groupcard', $this->vars())?>  

                    <div class="group-nav">
                        <a href="<?=$this->uri('/group/' . $item['groupKey'] . '/blog/create')?>" class="btn btn-gray pull-right"><i class="icon-plus"></i> Create New Topic</a>
                        <ul class="nav nav-tabs group-tab">
                            <li class="active"><a href="#group-forum">Forum</a></li>
                            <li><a href="#group-events">Events</a></li>
                            <li><a href="#group-albums">Albums</a></li>
                        </ul>
                    </div>

                    <div class="tab-content">
                        <div class="tab-pane active group-forum" id="group-forum">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th class="span5">Topics</th>
                                        <th>Author</th>
                                        <th class="span1 centeralign">Comments</th>
                                        <th class="span2 rightalign">Last Comment</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <?for($i=0;$i<30;$i++):?>
                                    <tr>
                                        <td class="title"><a href="">I grew up in Paris, France and moved to Oxford, UK when I was 5 years old. </a></td>
                                        <td class="author"><a href="">AlloVince</a></td>
                                        <td class="centeralign comment-count"><a href="">123</a></td>
                                        <td class="comment-time  rightalign"><?=$this->Datetime()->isoTime()?></td>
                                    </tr>
                                    <?endfor?>
                                </tbody>
                            </table>

                        </div>
                        <div class="tab-pane" id="group-events">...</div>
                        <div class="tab-pane" id="group-albums">...</div>
                    </div>


                </div><!--group main end-->
            </div><!--page main left end-->
            <div class="span4">
               <?=$this->widget('Epic', 'widgets/groupside', $this->vars())?>  
            </div>

        </div><!--page main right end-->
    </div><!-- page-bg end-->
</div><!--container end-->
