<?
$title = 'Groups';
$this->headTitle($title, 'SET');
$user = $this->user;
$items = $this->items;
$viewAsGuest = $this->viewAsGuest;
?>

<div class="page-inner">
    <div class="container">
        <div class="profile-cover">
            <?=$this->widget('Epic', 'widgets/profilenav', $this->vars())?>
        </div>
    </div><!-- above container end -->
    <div class="container">
        <div class="profile-main">
            <div class="row">
                <div class="span8">
                    <?=$this->widget('Epic', 'widgets/profilemeta', $this->vars())?>

                    <div class="profile-activities">
                        <div class="page-header border-header">
                            <h3><?=$this->_($item['groupName']);?></h3>
                        </div>

                        <article class="typo">
                        <?=$item['Text']['content']?>
                        </article>
                        
                    </div><!--profile-activities end-->
                </div><!--left span8 end-->
                <div class="span4">
                    <?=$this->widget('Epic', 'widgets/profileside', $this->vars())?>
                </div><!--right span4 end-->
            </div><!--row end-->
        </div><!--profil-main end-->
    </div><!--container end-->
</div><!--page inner end-->
