<?
$title = 'Groups';
$title = $this->_($title);
$this->headTitle($title, 'SET');
$items = $this->items;

$form = new Group\Form\GroupUserForm();
$form
->setView($this)
->useSubFormGroup()
->setMethod('post')
->setAction($this->uri('/group/join/'))
->prepare();

$unjoinForm = clone $form;
$unjoinForm->setMethod('delete');


$groupSearchForm = $this->form ? $this->form : new Epic\Form\GroupSearchForm();
$groupSearchForm->setView($this)
     ->setMethod('get')
     ->setAction($this->uri('/groups/'))
     ->prepare();

?>

<div class="container">
    <header class="group-header">
        <?=$this->widget('Epic', 'widgets/groupnav', $this->vars())?>  
    </header>
</div>

<div class="container">
    <div class="page-bg">
        <div class="row">

            <div class="span8">
                <div class="group-main">
                    <?=$this->widget('Epic', 'components/banner_group')?>  

                    <div class="page-header border-header">
                        <h3>New Groups</h3>
                    </div>
                    
                    <script id="group-new" type="text/x-tmpl" data-url="<?=$this->uri('/data/group/', array('order' => 'timedesc','rows' => 6, 'category' => $this->query['category']))?>">
                        <div class="group-new group-thumbnails">
                            <ul class="thumbnails">
                                {% if(o.items.length > 0) { %}
                                {% for (var i=0, item; item=o.items[i]; i++) { %}
                                <li><a href="<?=$this->uri('/group/')?>{%=item.groupKey%}">
                                    {% if(item.File) { %}
                                    <img width="90" height="90" class="img-rounded" alt="" src="{%=eva.thumb(item.File.Thumb, 'c_fill,h_90,w_90')%}">
                                    {% } else { %}
                                    <img  src="{%=eva.s('/assets/module/epic/img/group-default.jpg')%}" width="90" height="90" class="img-rounded"/>
                                    {% } %}
                                    <p>{%=item.groupName%}</p>
                                </a></li>
                                {% } %}
                                {% } %}
                            </ul>
                        </div>
                    </script>

                    <div class="page-header border-header">
                        <h3>Hot Groups</h3>
                    </div>

                    <script id="group-hot" type="text/x-tmpl" data-url="<?=$this->uri('/data/group/', array('order' => 'timedesc','rows' => 12, 'category' => $this->query['category']))?>">
                        <div class="group-hot group-thumbnails">
                            <ul class="thumbnails">
                                {% if(o.items.length > 0) { %}
                                {% for (var i=0, item; item=o.items[i]; i++) { %}
                                <li><a href="<?=$this->uri('/group/')?>{%=item.groupKey%}">
                                    {% if(item.File) { %}
                                    <img width="90" height="90" class="img-rounded" alt="" src="{%=eva.thumb(item.File.Thumb, 'c_fill,h_90,w_90')%}">
                                    {% } else { %}
                                    <img  src="{%=eva.s('/assets/module/epic/img/group-default.jpg')%}" width="90" height="90" class="img-rounded"/>
                                    {% } %}
                                    <p>{%=item.groupName%}</p>
                                </a></li>
                                {% } %}
                                {% } %}
                            </ul>
                        </div>
                    </script>

                    <div class="page-header border-header">
                        <h3>Topics of Groups</h3>
                    </div>

                    <div class="group-topics">
                        <?for($i=0;$i<8;$i++):?>
                        <div class="topic-wrap <?=$i%2 == 0 ? 'odd' : 'even'?>">
                            <div class="topic">
                                <div class="topic-heading">
                                    <small class="pull-right"><a href="">More</a></small>
                                    <h4><a href="">Gastronomy</a></h4>
                                </div>
                                <div class="topic-body-wrap">
                                    <div class="topic-body">
                                        <ul>
                                            <li><a href="">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</a></li>
                                            <li><a href="">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</a></li>
                                            <li><a href="">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</a></li>
                                            <li><a href="">Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</a></li>
                                        </ul>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <?endfor?>
                    </div>
                </div><!--group main end-->
            </div><!--page main left end-->
            <div class="span4">
                <?=$this->widget('Epic', 'widgets/groupsside', $this->vars())?>
            </div>

        </div><!--page main right end-->
    </div><!-- page-bg end-->
</div><!--container end-->


