<?
$title = 'Groups';
$title = $this->_($title);
$this->headTitle($title, 'SET');
$items = $this->items;

$form = new Group\Form\GroupUserForm();
$form
->setView($this)
->useSubFormGroup()
->setMethod('post')
->setAction($this->uri('/group/join/'))
->prepare();

$unjoinForm = clone $form;
$unjoinForm->setMethod('delete');


$groupSearchForm = $this->form ? $this->form : new Epic\Form\GroupSearchForm();
$groupSearchForm->setView($this)
     ->setMethod('get')
     ->setAction($this->uri('/groups/'))
     ->prepare();

?>

<div class="container">
    <header class="group-header">
    <div class="navbar navbar-inverse">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="nav-collapse">
                    <ul class="nav nav-main">
                        <li data-highlight-url="^/groups/\?category=hot" class="active"><a href="<?=$this->uri('/groups/?category=hot')?>"><?=$this->_('Hot')?></a></li>
                        <li data-highlight-url="^/groups/\?category=gastronomy"><a href="<?=$this->uri('/groups/?category=gastronomy')?>"><?=$this->_('Gastronomy')?></a></li>
                        <li data-highlight-url="^/groups/\?category=wine"><a href="<?=$this->uri('/groups/?category=wine')?>"><?=$this->_('Wine')?></a></li>
                        <li data-highlight-url="^/groups/\?category=spirit"><a href="<?=$this->uri('/groups/?category=spirit')?>"><?=$this->_('Spirit')?></a></li>
                        <li data-highlight-url="^/groups/\?category=cocktail"><a href="<?=$this->uri('/groups/?category=cocktail')?>"><?=$this->_('Cocktail')?></a></li>
                        <li data-highlight-url="^/groups/\?category=hotel-resort"><a href="<?=$this->uri('/groups/?category=hotel-resort')?>"><?=$this->_('Hotel & Resort')?></a></li>
                        <li data-highlight-url="^/groups/\?category=art-design"><a href="<?=$this->uri('/groups/?category=art-design')?>"><?=$this->_('Art & Design')?></a></li>
                        <li data-highlight-url="^/groups/\?category=event"><a href="<?=$this->uri('/groups/?category=event')?>"><?=$this->_('Event')?></a></li>
                    </ul>
                </div><!-- /.nav-collapse -->
            </div>
        </div><!-- /navbar-inner -->
    </div><!-- /navbar -->
    </header>
</div>

<div class="container">
    <div class="page-bg">
        <div class="row">

            <div class="span8">
                <div class="group-main">

                    <div id="myCarousel" class="carousel slide">
                        <div class="carousel-inner">
                            <div class="item active">
                                <img src="https://lh6.googleusercontent.com/-NXbW5HO17mA/UJEZG-4xLEI/AAAAAAAC-Lw/9Qxbhz2_3H0/s1152/Fabrizio_Musacchio_018_120804_1106_muenchen_200_HDR_pan_v01.jpg" alt="">
                                <div class="carousel-caption">
                                    <h4>First Thumbnail label</h4>
                                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                </div>
                            </div>
                            <div class="item">
                                <img src="https://lh5.googleusercontent.com/-FJpAsu3eJwM/UIsrsb_o16I/AAAAAAAAWe0/zfDy_7gREak/s1152/_KMC7744.jpg" alt="">
                                <div class="carousel-caption">
                                    <h4>Second Thumbnail label</h4>
                                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                </div>
                            </div>
                            <div class="item">
                                <img src="https://lh5.googleusercontent.com/-_A4lWEFZIRM/UEeptqGLA3I/AAAAAAAABro/x2rmlVafb-A/s1000/_MG_2471.jpg" alt="">
                                <div class="carousel-caption">
                                    <h4>Third Thumbnail label</h4>
                                    <p>Cras justo odio, dapibus ac facilisis in, egestas eget quam. Donec id elit non mi porta gravida at eget metus. Nullam id dolor id nibh ultricies vehicula ut id elit.</p>
                                </div>
                            </div>
                        </div>
                        <a class="left carousel-control" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                        <a class="right carousel-control" href="#myCarousel" data-slide="next">&rsaquo;</a>
                    </div>

                    <div class="page-main-header">
                        <h3>
                            <?=$this->_('Groups')?>
                            <?if($this->query['keyword']):?>
                            | Now Searching "<span class="highlight"><?=$this->query['keyword']?></span>"
                            <?endif?>
                        </h3>
                    </div>
                    <div class="search-filter">
                        <form <?=$this->formAttr($groupSearchForm)?> class="form form-inline">
                            <?=$groupSearchForm->helper('keyword', array('class' => 'span2', 'placeholder' => 'Keyword...'))?>
                            <button class="btn" type="submit"><?=$this->_('Filter Groups')?></button>
                        </form>
                    </div>
                    <div class="user-list vlist">
                        <?foreach($items as $item):?>
                        <div class="item">
                            <div class="item-inline item-text">
                                <div class="item-title">
                                    <h2><a href="<?=$this->uri('/groups/' . $item['groupKey'])?>" class="item-user"><?=$item['groupName']?></a></h2>
                                </div>
                                <div class="item-meta">
                                    <table class="table-condensed">
                                        <tbody>
                                            <tr>
                                                <td><?=$this->_('Create Time')?>: 
                                                    <?=$item['createTime']?>
                                                </td>
                                                <td><?=$this->_('Members')?> : <a href="">0</a></td>
                                            </tr>
                                        </tbody>
                                    </table>
                                </div>
                                <div class="item-content">
                                    <p><?=$this->_('Summary')?> : <?=$item['summary']?></p>
                                </div>
                            </div>
                            <div class="item-absolute item-action">

                                <?if(isset($item['Join']) && $item['Join']['user_id'] == $item['user_id']):?>
                                <?elseif(isset($item['Join']) && $item['Join'] && $item['Join']['user_id'] != $item['user_id']):?>
                                <form <?=$this->formAttr($unjoinForm)?>>
                                    <?=$unjoinForm->restful();?>
                                    <?=$unjoinForm->helper('group_id', 'formHidden', array('class' => '', 'value' => $item['id']))?>
                                    <?=$unjoinForm->helper('user_id', array('class' => ''))?>
                                    <?=$this->callback()?>
                                    <button class="btn btn-small item-action-main">Unjoin</button>
                                </form>
                                <?else:?>
                                <form <?=$this->formAttr($form)?>>
                                    <?=$form->restful();?>
                                    <?=$form->helper('group_id', 'formHidden', array('class' => '', 'value' => $item['id']))?>
                                    <?=$form->helper('user_id', array('class' => ''))?>
                                    <?=$this->callback()?>
                                    <button class="btn btn-small item-action-main">Join</button>
                                </form>
                                <?endif?>


                            </div>
                        </div>
                        <?endforeach?>
                    </div><!--activity-list end-->

                    <?if($this->paginator):?>
                    <?=$this->paginator->setPath('/groups/')->setBaseQuery($this->query);?>
                    <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                    <?endif;?>
                </div><!--group main end-->
            </div><!--page main left end-->
            <div class="span4">
               <?=$this->widget('Epic', 'widgets/groupside', $this->vars())?> 
            </div>

        </div><!--page main right end-->
    </div><!-- page-bg end-->
</div><!--container end-->


