<?
$this->headTitle('爱尔医疗', 'SET');
?>

<!-- START homepage slideshow -->
<div id="slideshow-wrapper">
    <ul id="slideshow">
        <li class="active"><!-- slide 1 -->
        <a href="#"><img src="<?=$this->link('/src/aier/images/yl2.jpg')?>" width="641" height="281" alt="" class="slide-1-img" /></a>
        <div class="slide-1-desc">
            <h1>爱尔医疗</h1>
            <p>
            爱尔医疗有限公司是集开发、生产制造、经营销售三类植入材料及人工器官、二类矫形外科(骨科)手术器械专业生产企业。产品注册为“艾迪尔”商标。 
            </p>
            <p>
            公司始终坚持以 “科技为本”为指导思想，以市场为导向，以需求为已任，追求科技创新的可持续发展战略。以优质的产品，真诚完善的服务，实现公司对顾客的承诺，满足顾客的需求。
            </p>
            <div class="slideshow-rm"><a href="#">learn more</a></div>
        </div>
        </li>

        <li><!-- slide 2 -->
        <a href="#"><img src="<?=$this->link('/src/aier/images/yl1.jpg')?>" width="960" height="281" alt="" /></a>
        </li>

        <li><!-- slide 3 -->
        <div class="slide-txt">
            <h3><a href="#">Learn how to protect your investments - a step by step guide</a></h3>

        </div>
        <a href="#"><img src="<?=$this->link('/src/aier/images/yl3.jpg')?>" width="960" height="281" alt="" /></a>
        </li>
    </ul>
</div>
<!-- END homepage slideshow -->
<div id="left">
    <div class="clearfix">
        <h2>Welcome to our company</h2>
        <p class="header-desc">We bring value, innovation and growth to your business</p>
    </div>
    <p>
    Ut dico exerci cum. Ipsum movet dolore sit ea, pri ea dicant mediocrem aliquando. Stet maiestatis ut pri, et vim melius legimus alienum. Nam nibh ipsum ad, pri dictas ornatus consequat te. Vel quem vidit posidonium in, brute dicunt maiorum vis te, mei veniam sanctus imperdiet ad.
    </p>  
    <p>
    Ad officiis percipitur theophrastus quo, ubique impedit ancillae per eu, pri natum tritani copiosae in. Civibus molestie deseruisse mea an, sumo omittam adolescens has te. Atqui luptatum pro ei, his eu regione sensibus necessitatibus. Ne feugait consetetur temporibus nec, inani audiam interpretaris cu vis, qui aeque zzril dissentiunt ea. Ut lorem choro aliquid vix, dolor partem bonorum duo in. Enim cetero luptatum usu ne, soluta invidunt signiferumque id ius, eos eius idque audiam eu.        
    </p>      

    <div class="h-box-1"><!-- services overview box-->
        <img src="<?=$this->link('/src/aier/images/service1.png')?>" width="54" height="54" alt="" class="h-box-img" />
        <div class="h-box-title">
            <h3>Services overview</h3>
            <p class="header-desc">Our services at a glance</p>
        </div>
        <div class="h-box-wrap">
            <p>Phasellus ipsum nulla, dignissim condimentum mattis sit amet, feugiat a nulla.</p>
            <ul class="h-services-list">
                <li><a href="#">Corporate Publishing</a></li>
                <li><a href="#">Interactive &amp; Onscreen Production</a></li>
                <li><a href="#">Advertising</a></li>
                <li><a href="#">Event Management</a></li>
                <li><a href="#">Integrated Communications</a></li>                                
                <li><a href="#">Public Relations</a></li>
            </ul>
        </div>
    </div>

    <div class="h-box-2"><!-- featured case study overview -->
        <img src="<?=$this->link('/src/aier/images/service5.png')?>" width="53" height="54" alt="" class="h-box-img" />
        <div class="h-box-title">
            <h3>Services overview</h3>
            <p class="header-desc">Investments and advertising campaigns</p>
        </div>
        <div class="h-box-wrap">
            <p>
            Phasellus ipsum nulla, dignissim condimentum mattis sit amet, feugiat a nulla. Nulla molestie pellentesque lorem, eu lacinia sem pellentesque ut. Aenean tempor ligula ut massa feugiat quis lacinia sem sollicitudin.
            </p>
            <p>
            Fusce mattis blandit libero a imperdiet. Sed lorem quam, imperdiet eu congue eget, pretium eget justo. 
            </p>
            <div class="body-rm"><a href="#">read more</a></div>
        </div>
    </div>

</div>
<div id="right">
    <div class="newsletter"><!-- newsletter section -->
        <h3>官方微博</h3>
        <iframe width="100%" height="550" class="share_self"  frameborder="0" scrolling="no" src="http://widget.weibo.com/weiboshow/index.php?language=&width=0&height=550&fansRow=2&ptype=1&speed=0&skin=1&isTitle=0&noborder=1&isWeibo=1&isFans=0&uid=2011927842&verifier=8ceb4535&dpc=1"></iframe>
    </div>
</div>  
