<div class="blog-categ">
    <?$posts = $this->action('Aier\Api\Controller\FrontendController', 'postlistAction',array('category' => 'news', 'rows' => 5));?>
    <?$category = $this->action('Aier\Api\Controller\FrontendController', 'categoryAction',array('category' => 'news', 'rows' => 5));?>
    <h3><a href="<?=$this->uri('/category/' . $category['urlName'])?>"><?=$category['categoryName']?></a></h3>
    <ul class="services-box-list">
        <?foreach($posts as $post):?>
        <li><a href="<?=$this->uri('/pages/' . $post['urlName'])?>"><?=$post['title']?></a></li>
        <?endforeach;?>
    </ul>             
</div>

<div class="blog-categ">
    <?$posts = $this->action('Aier\Api\Controller\FrontendController', 'postlistAction',array('category' => 'projects', 'rows' => 5));?>
    <?$category = $this->action('Aier\Api\Controller\FrontendController', 'categoryAction',array('category' => 'projects', 'rows' => 5));?>
    <h3><a href="<?=$this->uri('/category/' . $category['urlName'])?>"><?=$category['categoryName']?></a></h3>
    <ul class="services-box-list">
        <?foreach($posts as $post):?>
        <li><a href="<?=$this->uri('/pages/' . $post['urlName'])?>"><?=$post['title']?></a></li>
        <?endforeach;?>
    </ul>             
</div>

<div class="aboutus-box">
    <?=$this->widget('Aier', 'components/qq')?>
</div>
<div class="newsletter">
    <?=$this->widget('Aier', 'components/weibo')?>
</div>
