<?
$this->headTitle($this->post['title'], 'SET');

$gonggao = $this->action('Aier\Api\Controller\FrontendController', 'postlistAction',array('category' => 'gonggao', 'rows' => 7));
$zhuanti = $this->action('Aier\Api\Controller\FrontendController', 'postlistAction',array('category' => 'zhuanti', 'rows' => 7));
?>
<div id="left">

    <div class="interior-content">
        <h2><a href="<?=$this->uri('/pages/' . $this->post['urlName'])?>"><?=$this->post['title']?></a></h2>
        <div class="blog-misc">
            <span><a href="#"><?=$this->post['createTime']?></a></span>
        </div>
        <?=$this->post['Text']['contentHtml']?>
    </div>

</div>

<div id="right">
    <div class="blog-categ">
        <h3>Categories</h3>
        <ul>
            <li><a href="#">Web Design</a></li>
            <li><a href="#">Photography</a></li>                
            <li><a href="#">Wordpress Themes</a></li>                
            <li><a href="#">News</a></li>                
            <li><a href="#">Inspiration</a></li>                
            <li><a href="#">Marketing and Advertising</a></li>                
            <li><a href="#">Management</a></li>                                                                
        </ul>
    </div>

    <div class="blog-categ">
        <h3>Archives</h3>
        <ul>
            <li><a href="#">August 2009</a></li>
            <li><a href="#">July 2009</a></li>                
            <li><a href="#">June 2009</a></li>                
            <li><a href="#">May 2009</a></li>                
            <li><a href="#">April 2009</a></li>                                            
        </ul>
    </div>

    <div class="flickr">
        <h3>Flickr</h3>
        <ul>
            <li><a href="#"><img src="img/flickr1.jpg" width="90" height="90" alt="" /></a></li>
            <li><a href="#"><img src="img/flickr2.jpg" width="90" height="90" alt="" /></a></li>
            <li><a href="#"><img src="img/flickr3.jpg" width="90" height="90" alt="" /></a></li>    
            <li><a href="#"><img src="img/flickr4.jpg" width="90" height="90" alt="" /></a></li>
            <li><a href="#"><img src="img/flickr5.jpg" width="90" height="90" alt="" /></a></li>
            <li><a href="#"><img src="img/flickr6.jpg" width="90" height="90" alt="" /></a></li>                                                
        </ul>
    </div>
    <div class="newsletter"><!-- newsletter section -->
        <h3>Sign up for Newsletter</h3>
        <form action="#" method="post">
            <fieldset class="newsletter-fieldset">
                <input type="text" class="newsletter-input" value="Your email address" name="newsletter" />
                <input type="submit" value="" class="input-arrow" />
            </fieldset>
        </form>
        <p>We will keep you up to date with news, events and other great features.</p>
    </div>

    <div class="brochure"><!-- brochure section -->
        <a href="#"><img src="img/pdf_icon.png" width="43" height="53" alt="" /></a>
        <div class="brochure-title">
            <h3>Media Consult brochure</h3>
            <p class="header-desc">Download our PDF brochure</p>
        </div>            
    </div>

</div>  
