<?
$this->headTitle($this->post['title'], 'SET');

$gonggao = $this->action('Aier\Api\Controller\FrontendController', 'postlistAction',array('category' => 'gonggao', 'rows' => 7));
$zhuanti = $this->action('Aier\Api\Controller\FrontendController', 'postlistAction',array('category' => 'zhuanti', 'rows' => 7));
?>
<div id="left">

    <div class="interior-content">
        <h2><a href="<?=$this->uri('/pages/' . $this->post['urlName'])?>"><?=$this->post['title']?></a></h2>
        <div class="blog-misc">
            <span><a href="#"><?=$this->post['createTime']?></a></span>
        </div>
        <?=$this->post['Text']['contentHtml']?>
    </div>

</div>

<div id="right">
    <?=$this->widget('Aier', 'widgets/side', $this->vars())?>
</div>
