<?
$title = 'Members';
$title = $this->_($title);
$this->headTitle($title, 'SET');
$items = $this->items;

$form = new Activity\Form\FollowForm();
$form
->setView($this)
->useSubFormGroup()
->setMethod('post')
->setAction($this->uri('/activity/follow/'))
->prepare();
?>

<div class="container">
    <div class="normal-page">
        <div class="page-main"><div class="row"><div class="span12">
            <div class="row">
                <div class="span8">
                    <div class="page-main-header">
                        <h3><?=$this->_('Members')?></h3>
                    </div>

                    <div class="user-list vlist">
                        <?foreach($items as $item):?>
                        <div class="item">
                            <div class="item-absolute item-userface">
                                <a href="<?=$this->uri('/user/' . $item['userName'])?>" title="" class="userface"><img src="<?=$this->gravatar($item['email'])?>" alt="" class="img-rounded" width="60" height="60" /></a>
                                <a href="<?=$this->uri('/message/' . $item['id'])?>" title="" class="item-quick-action btn btn-small btn-tiny-white">Message</a>
                            </div>
                            <div class="item-inline item-text">
                                <div class="item-title">
                                    <h2><a href="<?=$this->uri('/user/' . $item['userName'])?>" class="item-user"><?=$item['userName']?></a></h2>
                                    <?=$item['Profile']['city']?> <?=$item['Profile']['province']?> <?=$item['Profile']['country']?> 
                                </div>
                                <div class="item-meta">
                                    <?=$item['gender']?>
                                </div>
                                <div class="item-content">
                                    <p><?=$item['Profile']['bio']?></p>
                                </div>
                            </div>
                            <div class="item-absolute item-action">
                                <form <?=$this->formAttr($form)?>>
                                    <?=$form->restful();?>
                                    <?=$form->helper('user_id', 'formHidden', array('class' => '', 'value' => $item['id']))?>
                                    <?=$form->helper('follower_id', array('class' => ''))?>
                                    <?=$this->callback()?>
                                    <button class="btn btn-small item-action-main">Follow</button>
                                </form>

                            </div>
                        </div>
                        <?endforeach?>
                    </div><!--activity-list end-->
                </div><!--page main left end-->
                <div class="span3">
                    <div class="page-extra">
                        <?=$this->widget('Epic', 'widgets/userextra')?>
                    </div>
                </div><!--page main right end-->
            </div>
</div></div></div><!--page-main end-->
    </div><!-- normal end-->
</div><!--container end-->

