<li class="active"><!-- slide 1 -->
<a href="#"><img src="/static/src/aier/images/yl2.jpg?v=1.0.0" width="641" height="281" alt="" class="slide-1-img" /></a>
<div class="slide-1-desc">
    <h1>爱尔医疗</h1>
    <p>
    爱尔医疗有限公司是集开发、生产制造、经营销售三类植入材料及人工器官、二类矫形外科(骨科)手术器械专业生产企业。产品注册为“艾迪尔”商标。 
    </p>
    <p>
    公司始终坚持以 “科技为本”为指导思想，以市场为导向，以需求为已任，追求科技创新的可持续发展战略。以优质的产品，真诚完善的服务，实现公司对顾客的承诺，满足顾客的需求。
    </p>
    <div class="slideshow-rm"><a href="#">learn more</a></div>
</div>
</li>

<li><!-- slide 2 -->
<a href="#"><img src="/static/src/aier/images/yl1.jpg?v=1.0.0" width="960" height="281" alt="" /></a>
</li>

<li><!-- slide 3 -->
<div class="slide-txt">
    <h3><a href="#">Learn how to protect your investments - a step by step guide</a></h3>

</div>
<a href="#"><img src="/static/src/aier/images/yl3.jpg?v=1.0.0" width="960" height="281" alt="" /></a>
</li>

