<?
$title = $this->_('七彩梦圆澜沧江畔——告庄西双景景真寨之亿成阳光国际公寓');
$this->headTitle($title, 'SET');
$config = $this->getHelperPluginManager()->getServiceLocator()->get('config');
$thumbUrl = $config['upload']['storage']['default']['thumburl'];
?>

<div id="featured">
    <img src="<?=$this->assets('/module/yicheng/images/slider/banner3.jpg')?>" width="100%" alt=""/>
    <!--<img src="<?=$this->assets('/module/yicheng/images/slider/banner1.jpg')?>" width="100%" alt=""/>-->
    <img src="<?=$this->assets('/module/yicheng/images/slider/banner2.jpg')?>" width="100%" alt=""/>
    <img src="<?=$this->assets('/module/yicheng/images/slider/banner4.jpg')?>" width="100%" alt=""/>
</div>

<div class="row">
    <div class="tagline">
        <div class="main-nav">
            <p>七彩梦圆澜沧江畔——告庄西双景景真寨之亿成阳光国际公寓</p>
        </div>
    </div>
</div>

<!--HOME PAGE : STARTS--> 
<div class="row layout">
    <a href="<?=$this->uri('/index/overview/')?>"><img src="<?=$this->assets('/module/yicheng/images/bg/11.jpg')?>" width="100%" /></a>
    <!--
    <section id="second" class="twelve columns outer-wrap">
    </section>
    -->
</div>
<!--HOME PAGE : ENDS--> 

<!--HOME PAGE : STARTS--> 
<div class="row layout">
    <a href="<?=$this->uri('/index/overview/')?>"><img src="<?=$this->assets('/module/yicheng/images/bg/12.jpg')?>" width="100%" /></a>
    <!--
    <section id="third" class="twelve columns outer-wrap">
    <div class="box" style="top:20%;right:10%;">
        <a href="<?=$this->uri('/index/overview/')?>">
            <h2 class="white-txt">亿成阳光公寓</h2>
            <h4 class="white-txt text-left"><span class="color-high">全球休闲旅游投资</span>目的地，限购令下最火掘金项目</h4>
        </a>
    </div>
    </section>
    -->
</div>
<!--HOME PAGE : ENDS--> 

<!--HOME PAGE : STARTS--> 
<div class="row layout">
    <!--
    <section id="fourth" class="twelve columns outer-wrap">
    <div class="box" style="top:30%;left:7%;">
        <a href="<?=$this->uri('/index/jiazhi/')?>">
            <h4 class="white-txt text-left">天时地利人和<br>扼守商脉成就财富</h4>
            <h4 class="white-txt text-left"><span class="color-high">时代巅峰之作</span><br>傣泰文化倾献！</h4>
        </a>
    </div>
    </section>
    -->
</div>
<!--HOME PAGE : ENDS--> 

<!--HOME PAGE : STARTS--> 
<div class="row layout">
    <section id="fifth" class="twelve columns outer-wrap">
    <div class="main-nav">
        <div class="placeholder"></div>
        <div class="row">
            <article class="four columns skill-info">
            <h3 class="dark-txt">世界级旅游门户</h3>
            <p><a href="<?=$this->uri('/index/jiazhi/')?>"><img src="<?=$this->assets('/module/yicheng/images/compare/05.jpg')?>" alt=""></a></p>
            <p>西双版纳，北回归线上唯一一片绿洲，依托特色民族风情及气候优势，是中国知名旅游城市。随着全球旅游经济的发展，以西双版纳、清迈、琅勃拉邦为节点的旅游目的地和集散中心的“大金三角旅游区”正在逐渐形成。西双版纳凭借其独特的区位优势、水陆空立体交通网、丰富的旅游资源，逐渐成为进入金三角、中南半岛、新马泰的一线国际旅游门户。<a href="<?=$this->uri('/index/jiazhi/')?>">更多</a></p>
            </article>
            <article class="four columns skill-info">
            <h3 class="dark-txt">九塔十二寨</h3>
            <p><a href="<?=$this->uri('/index/jiazhi/')?>"><img src="<?=$this->assets('/module/yicheng/images/compare/07.jpg')?>" alt=""></a></p>
            <p>告庄西双景为傣语，汉意为“九塔十二寨”，通过“一江两门九塔十二寨”的总体规划，打造“六大国际中心、五大景观带、三大综合体、东南亚特色综合业态，实现文化、休闲、度假、体验、娱乐、旅游、商贸、居住等综合功能。<a href="<?=$this->uri('/index/jiazhi/')?>">更多</a></p>
            </article>
            <article class="four columns skill-info">
            <h3 class="dark-txt">二期升级力作绽放</h3>
            <p><a href="<?=$this->uri('/index/jiazhi/')?>"><img src="<?=$this->assets('/module/yicheng/images/compare/06.jpg')?>" alt=""></a></p>
            <p>高品质精装小户型江景公寓，东南亚风格、现代欧式风格顶级装修，奢华家具家电全套配备，24小时物业守护，真正实现提包即可入住，投资自住两相宜。从40平米到80平米多达25种户型供您选择，是专为追求生活品位的精英阶层量身打造的度假公寓；背山面水，一户一景，尽享舒适与奢华。度假休闲，观江赏月，独享世外桃园悠然空间。<a href="<?=$this->uri('/index/jiazhi/')?>">更多</a></p>
            </article>
        </div>

    </div>
    </section>
</div>
<!--HOME PAGE : ENDS--> 


<!--HOME PAGE : STARTS--> 
<div class="row layout">
    <a href="<?=$this->uri('/index/overview/')?>"><img src="<?=$this->assets('/module/yicheng/images/bg/13.jpg')?>" width="100%" /></a>
</div>
<!--HOME PAGE : ENDS--> 
