<?
$title = $this->_('七彩梦圆澜沧江畔——告庄西双景景真寨之亿成阳光国际公寓');
$this->headTitle($title, 'SET');
$config = $this->getHelperPluginManager()->getServiceLocator()->get('config');
$thumbUrl = $config['upload']['storage']['default']['thumburl'];
?>


<!--SERVICES : STARTS-->  
<div class="row layout">
    <section id="fourth" class="twelve columns outer-wrap">
    <div class="story">
        <div class="twelve columns add-top">

            <div class="row">
                <div class="placeholder"></div>

                <article class="twelve columns services-testimonial">
                <h4 class="dark-txt">户型鉴赏</h4>
                <div class="placeholder"></div>

                <div class="row">
                    <?for($i = 1; $i <=24; $i++):?>
                    <article class="two columns">
                    <a data-fancybox-group="gallery2" class="fancybox-effects-d" href="<?=$this->link('/upload/album/huxing/' . sprintf('%02s', $i) . '.jpg')?>" title="可以使用鼠标滚轮切换图片"><div class="overlay-block"><h4 class="work-item-name">亿成阳光公寓房产户型</h4></div><img src="<?=$thumbUrl?>album/huxing/<?=sprintf('%02s', $i)?>,c_fill,h_280,w_280.jpg"  title="persona by designova" alt="persona" /></a>
                    </article>
                    <?endfor;?>
                </div>
                </article>
            </div>
        </div>
    </div> 
    <!--.story-->  
    </section>
</div>
<!--SERVICES : STARTS-->
