<?
$title = $this->_('亿成国际');
$this->headTitle($title, 'SET');
?>
<script src="<?=$this->assets('/module/yicheng/js/paomadeng.js')?>" type="text/javascript"></script>
<!-- Slider -->
<div id="slider">

    <!-- Flexslider Start-->
    <div class="flexslider" style="background: #fafafa;">
        <ul class="slides">
            <?for($i=1;$i<=7;$i++):?>
            <!-- Slide -->
            <li class="custom-slide" style="background: url(<?=$this->assets("/module/yicheng/index/images/bg$i.jpg")?>)">
            <div class="container">
                <div class="sixteen columns">
                </div>
            </div>
            </li>
            <?endfor?>
        </ul>
    </div>
    <!-- Flexslider End-->

</div>
<!-- End Slider -->

<!-- 960 Container Start -->
<div class="container">

    <!--Recent Work -->
    <div class="sixteen columns">
        <h4 id="index-title" class="headline">集团业务</h4>
    </div>

    <!-- 1/3 Column -->
    <div class="one-third column">
        <div class="item-img"><a href="/pages/jinrong"><img src="<?=$this->assets("/module/yicheng/index/images/1.jpg")?>" alt=""/></a></div>
        <div class="portfolio-item-meta">
            <h5><a href="/pages/jinrong">金融产业</a></h5>
            <p>集团及各分公司核心人员均系拥有多年国际市场投资经验，与国际知名金融机构有着良好的合作关系的高知人士。我们创建了一套完善的投资理念和科学的风险管理方法；通过国际投资集团专家团队的技术分析指导,日夜紧贴市场走势,提供国际性最新,最快,最专业的信息。</p>
        </div>
    </div>

    <!-- 1/3 Column -->
    <div class="one-third column">
        <div class="item-img"><a href="/home/"><img src="<?=$this->assets("/module/yicheng/index/images/4.jpg")?>" alt=""/></a></div>
        <div class="portfolio-item-meta">
            <h5><a href="/home/">房地产业</a></h5>
            <p>亿成国际以专业投资眼光考察评估地产项目，准确定位，寻找良机，以雄厚实力投入多个省市房地产业发展，已取得良好业绩。多年经营使亿成国际在房地产领域愈加成熟，房地产投资跨越多种类型，从商业地产，旅游地产，到住宅别墅，已帮助很多客户成功置业投资，并使亿成国际商业触角不断延伸。</p>
        </div>
    </div>

    <!-- 1/3 Column -->
    <div class="one-third column">
        <div class="item-img"><a href="/pages/nengyuan"><img src="<?=$this->assets("/module/yicheng/index/images/2.jpg")?>" alt=""/></a></div>
        <div class="portfolio-item-meta">
            <h5><a href="/pages/nengyuan">能源产业</a></h5>
            <p>21世纪中国能源产业面临发展和风险共存的局面，开拓海外市场势在必行。亿成国际以雄厚实力成功挺进能源领域，已在能源储备丰富的俄罗斯站稳脚跟，并将在满洲里建设能源企业园区。随着企业发展，未来亿成国际必将为中国能源产业做出巨大贡献。</p>
        </div>
    </div>

    <div class="clearfix"></div>

    <div class="sixteen columns">
        <h4 id="index-title" class="headline">特色产业</h4>
    </div>

    <!--Latest From Blog -->
    <div id="index-below" class="sixteen columns">
        <!--<h4 class="headline">Latest From Blog</h4>-->


        <!-- 1/4 Column -->
        <div class="four columns alpha">
            <div class="item-img"><a href="/pages/guojimaoyi"><img src="<?=$this->assets("/module/yicheng/index/images/3.jpg")?>" alt=""/></a></div>
            <div class="portfolio-item-meta">
                <h5><a href="/pages/guojimaoyi">国际贸易</a></h5>
                <p>亿成国际团队具有精辟的市场分析能力和良好的市场控制能力，一线人员均具有多年相关工作经验。依托多年的市场积累，公司逐渐形成了国际贸易运作模式和健全的管理模式，并且配有常年的法律顾问。</p>
            </div>
        </div>

        <!-- 1/4 Column -->
        <div class="four columns">
            <div class="item-img"><a href="/pages/lvyou"><img src="<?=$this->assets("/module/yicheng/index/images/5.jpg")?>" alt=""/></a></div>
            <div class="portfolio-item-meta">
                <h5><a href="/pages/lvyou">旅游产业</a></h5>
                <p>经过几年来在旅游产业的深入研究，亿成国际未来将扩大思维半径，在吃住行游购娱六大方面交叉营销，实现旅游产业突破性发展。</p>
            </div>
        </div>

        <!-- 1/4 Column -->
        <div class="four columns omega">
            <div class="item-img"><a href="/pages/shengwu"><img src="<?=$this->assets("/module/yicheng/index/images/6.jpg")?>" alt=""/></a></div>
            <div class="portfolio-item-meta">
                <h5><a href="/pages/shengwu">生物科技</a></h5>
                <p>亿成国际在张北地区兴建高品质北冬虫夏草生产基地，未来将开发系列产品，使更多人享受到品质高于冬虫夏草，价格却可被寻常百姓接受的“北冬虫夏草”。</p>
            </div>
        </div>

        <!-- 1/4 Column -->
        <div class="four columns omega">
            <div class="item-img"><a href="/pages/wenhua"><img src="<?=$this->assets("/module/yicheng/index/images/7.jpg")?>" alt=""/></a></div>
            <div class="portfolio-item-meta">
                <h5><a href="/pages/wenhua">文化产业</a></h5>
                <p>亿成国际将发展文化产业视为社会责任的体现。在推出文化产品的同时，倡导绿色环保理念与中国原创的发展方向，为文化产业良好发展添砖加瓦。</p>
            </div>
        </div>

    </div>

<!-- News and Videos -->
	<div class="sixteen">
		<div class="ten columns">
			<h4 class="headline">集团新闻</h4>
			<div id="a" style="overflow:hidden;height:210px;width:560px;">  
				<div id="a1">  
                <ul>
                <!--
				<h6><li><i class="icon-volume-up" style="margin-right:20px;"></i><a href="http://yichengguoji.net/pages/hebeiyicheng">河北亿成投资有限公司简介</a></li></h6>
				<p></p>
                -->
				<h6><li><i class="icon-volume-up" style="margin-right:20px;"></i><a href="http://yichengguoji.net/pages/zhangjiakou">亿成张家口壹善北虫草生产基地简介</a></li></h6>
				<p></p>
				<h6><li><i class="icon-volume-up" style="margin-right:20px;"></i><a href="http://yichengguoji.net/pages/yangguang">亿成阳光房地产开发有限公司简介</a></li></h6>
				<p></p>
				<h6><li><i class="icon-volume-up" style="margin-right:20px;"></i><a href="http://yichengguoji.net/pages/tianjinheeryi">天津合而壹股份投资基金管理有限公司简介</a></li></h6>
				<p></p>
				<h6><li><i class="icon-volume-up" style="margin-right:20px;"></i><a href="http://yichengguoji.net/pages/feicui">亿成万兴进出口贸易公司简介</a></li></h6>
				<p></p>
				<h6><li><i class="icon-volume-up" style="margin-right:20px;"></i><a href="http://yichengguoji.net/pages/mubiao">集团远景目标</a></li></h6>
				<p></p>
				</ul>
				</div>  
				<div id="a2"></div> 
			</div>
			<script type="text/javascript"> 
			boxmove("a","a1","a2",1); 
			</script> 
		</div>
		<div class="six columns">
			<h4 class="headline">亿成国际</h4>
			<iframe height=220 width=340 src="http://player.youku.com/embed/XNTI5OTMzMjky" frameborder=0 allowfullscreen></iframe>
		</div>
	</div>
	
	<div class="clearfix"></div>
	<!-- News and Videos End -->

</div>
<!-- 960 Container End -->
<script>
jQuery(document).ready(function() {

    var leftside = $('<a href="/home"><img src="<?=$this->assets('/module/yicheng/images/sideleft.png')?>"></a>').css({
        position : 'fixed',
        top : '10px'
    }).appendTo('body').hide();
    var rightside = $('<a href="http://wpa.qq.com/msgrd?v=3&amp;uin=1715752592&amp;site=qq&amp;menu=yes" target="_blank"><img src="<?=$this->assets('/module/yicheng/images/qq.png')?>"></a>').css({
        position : 'fixed',
        bottom : '30%'
    }).appendTo('body').hide();
    var sideWidth = 200;
    var showSide = function(){
        if($(window).scrollTop() < 640 || $(document).width() < 1000){
            leftside.hide();
            rightside.hide();
        } else {
            var left = ($(document).width() - 960) / 2 - sideWidth - 30 ;
            leftside.css('left', left).show();
            rightside.css('right', left).show();
        }
    }

    $(window).on('scroll', function(){
        showSide();
    });
});
</script>
