<?
$title = $this->_('七彩梦圆澜沧江畔——告庄西双景景真寨之亿成阳光国际公寓');
$this->headTitle($title, 'SET');
$config = $this->getHelperPluginManager()->getServiceLocator()->get('config');
$thumbUrl = $config['upload']['storage']['default']['thumburl'];
?>


<!--FEATURES : STARTS--> 
<div class="row layout">
    <section id="third" class="twelve columns outer-wrap">
    <div class="story">
        <div class="bg"></div>
        <div class="nine columns add-top">

            <h2 class="main-heading-alt color-high">保驾护航 <span class="main-heading color-dark">八大价值</span></h2>

            <div class="placeholder"></div>

            <div class="row">
                <article class="six columns skill-info">
                <h3 class="dark-txt"><i class="foundicon-star color-high"></i> 规划价值</h3>
                <p>西双版纳1200目首席商旅大盘，盛世规划六大国际中心、五大景观带、三大综合体、东南亚特色综合业态，创造巅峰价值版图。</p>
                </article>

                <article class="six columns skill-info">
                <h3 class="dark-txt"><i class="foundicon-settings color-high"></i> 门户价值</h3>
                <p>尊处“西南桥头堡战略“前沿，紧邻澜沧江，扼守城市要道，是百万游客到达西双版纳的第一站，门户优势无可比拟。</p>
                </article>
            </div>

            <div class="row">
                <article class="six columns skill-info">
                <h3 class="dark-txt"><i class="foundicon-tools color-high"></i> 地域价值</h3>
                <p>中国最大的热带雨林、古老而传播甚广的少数民族文化传承、中国五大长寿带之一。</p>
                </article>

                <article class="six columns skill-info">
                <h3 class="dark-txt"><i class="foundicon-tools color-high"></i> 枢纽价值</h3>
                <p>汇聚西双版纳规模最大配套最全的国际游客集散中心、国际旅游签证中心、国际班车客运中心，造就势不可挡的枢纽高地。</p>
                </article>

            </div>

            <div class="row">

                <article class="six columns skill-info">
                <h3 class="dark-txt"><i class="foundicon-flag color-high"></i> 文化价值</h3>
                <p>东盟自由贸易区与湄公河次区域经济合作区的旅游文化项目、傣泰文化重点展示区、云南省九大旅游重点项目之一。</p>
                </article>

                <article class="six columns skill-info">
                <h3 class="dark-txt"><i class="foundicon-heart color-high"></i> 推动力价值</h3>
                <p>大金三角旅游环线游客出发台与回归台，优越的区位优势，便利的水陆空立体交通，描绘不可估量的升值前景。</p>
                </article>

            </div>

            <div class="row">
                <article class="six columns skill-info">
                <h3 class="dark-txt"><i class="foundicon-idea color-high"></i> 消费力价值</h3>
                <p>每年近800万国际、国内游客接待量跨越式增长，带来国际购物、旅游观光、休闲度假、狂欢娱乐、风情体验、文化品位等一站式消费潜力。</p>
                </article>

                <article class="six columns skill-info">
                <h3 class="dark-txt"><i class="foundicon-heart color-high"></i>品牌共赢价值</h3>
                <p>国际百名实力商家强势入驻，比肩国际品牌，更坚实的投资保障，无限商机盛大呈现。</p>
                </article>

            </div>

            <div class="row">
                <article class="twelve columns services-testimonial">
                <h4 class="dark-txt">项目投资对比分析</h4>
                <div class="row">
                    <article class="six columns">
                    <div class="three columns">
                        <img alt="persona" title="persona by designova" src="<?=$this->assets('/module/yicheng/images/compare/01.jpg')?>">
                    </div>
                    <div class="nine columns">
                        <h5>海南鹏欣白金湾</h5>
                        <blockquote>依托海南旅游资源、黎族等少数民族文化，在国家政策的扶植下2009年确立了“国际旅游岛“的战略地位。项目类型主要由精装公寓、度假酒店等构成。鹏欣白金湾依托海南旅游资源蓬勃发展，房产价值提升惊人。精装公寓在2012年1月1.5万元/㎡开盘以来，在房地产市场萎靡的环境下，一路飙升到目前的2.3万元，短短10个月价格上涨50%以上。</blockquote>
                    </div>
                    </article>

                    <article class="six columns">
                    <div class="three columns">
                        <img alt="persona" title="persona by designova" src="<?=$this->assets('/module/yicheng/images/compare/02.jpg')?>">
                    </div>
                    <div class="nine columns">
                        <h5>成都泰达上青城</h5>
                        <blockquote>都江堰风景区青城山下以及众多的名胜古迹，中国道教的发源地之一。项目由精装公寓、办公楼和商业物业组成。泰达上青城依托都江堰风景区、青城山风景区以及众多的名胜古迹映衬下，酒店式精装公寓2011年开盘价5千元/㎡（折扣后），截止到目前市场报价已经攀升到了1万元，1年多上涨100%。</blockquote>
                    </div>
                    </article>
                </div>
                <div class="row">
                    <article class="twelve columns">
                    <div class="three columns">
                        <img alt="persona" title="persona by designova" src="<?=$this->assets('/module/yicheng/images/compare/03.jpg')?>">
                    </div>
                    <div class="three columns">
                        <img alt="persona" title="persona by designova" src="<?=$this->assets('/module/yicheng/images/compare/04.jpg')?>">
                    </div>
                    <div class="six columns">
                        <h5>亿成阳光酒店式公寓</h5>
                        <blockquote>依托西双版纳独特的区位优势以及大金三角国际旅游黄金环绕。悠久的“九塔十二寨“历史文化底蕴，汇集东南亚、傣泰文化精髓。“西南桥头堡”的战略地位。依托西双版纳每年800万中外游客，恢弘的区域规划，完善丰富、多元的业态组合以及项目独特的市场地位和发展前景，资本投资增值潜力与日俱增。</blockquote>
                    </div>
                    </article>

                </div>
                </article>


            </div>


            <!-- End Right Column -->
            <div class="clearfix">
            </div>


        </div>
    </div> 
    <!--.story-->  
    </section>
</div>
<!--FEATURES : ENDS--> 


