<?
$title = $this->_('七彩梦圆澜沧江畔——告庄西双景景真寨之亿成阳光国际公寓');
$this->headTitle($title, 'SET');
$config = $this->getHelperPluginManager()->getServiceLocator()->get('config');
$thumbUrl = $config['upload']['storage']['default']['thumburl'];
?>

<!--ABOUT : STARTS--> 
<div class="row layout">
    <section id="second" class="twelve columns outer-wrap">
    <div class="story">
        <!--<div class="bg hide-for-small"></div>-->
        <div class="four columns offset-by-eight add-top">
            <h2 class="main-heading-alt white-txt">一本充满魅力的财富读本 <span class="main-heading dark-txt">西双版纳</span></h2>
            <p class="medium-para">亿成阳光国际公寓位于告庄西双景东部景真寨，北临孔雀大道，南邻澜沧江，项目聘请国内外顶尖的战略策划，建筑设计、景观规划、融汇他们的前沿理念和创新思想，严格依循西双版纳特有的傣族文化和大金三角的异域情调，打造独具东南亚异域格调的景观特色和傣泰建筑群，将一切设计融入园林景观之中，最大尺度的让人们去体会专属西双版纳的原生态风貌和雨林景观，以及属于大金三角的休闲文化体验。</p>
            <p class="medium-para">告庄西双景为傣语，汉意为“九塔十二寨”，通过“一江两门九塔十二寨”的总体规划，打造“六大国际中心、五大景观带、三大综合体、东南亚特色综合业态，实现文化、休闲、度假、体验、娱乐、旅游、商贸、居住等综合功能。园区占地1200亩，汲取东南亚建筑风情，融合浓郁的傣泰文化，原汁原味地打造热带雨林中的田园城市，缔造前所未有的大金三角傣泰文明中心，引擎西双版纳旅游地产，呈现文化体验之都、休闲度假之都、旅游商贸之都、国际商务之都、傣泰生活之都、时尚繁华之都。</p>
            <ul class="features add-top ">
                <li class="features-first white-txt"><i class="foundicon-settings"></i><span>总建筑面积</span>13万平方米</li>
                <li class="white-txt"><i class="foundicon-heart"></i><span>公寓</span>1000余套</li>
                <li class="white-txt"><i class="foundicon-star"></i><span>物业守护</span>24小时</li>
                <li class="white-txt"><i class="foundicon-checkmark"></i><span>户型</span>25种</li>
            </ul>
            <div class="twelve columns sidebarright alignright">
            </div>
        </div>
    </div> 
    <!--.story-->  
    </section>
</div>
<!--ABOUT : ENDS-->  
