<?
$this->headTitle('联系我们', 'SET');
$method = 'post';

if($this->form){
	$form = $this->form;
} else {
    $form = Eva\Api::_()->getForm('Aier\Form\ContactForm');
}
$form->init(array(
    'action' => $this->uri('/order/'),
    'method' => $method,
    'values' => ''
));

$post = $this->action('Aier\Api\Controller\FrontendController', 'postAction', 'contact');
?>

<div id="left">
    <div class="interior-header">
        <h2><?=$post['title']?></h2>
    </div>
    <div class="interior-content">
        <div class="clearfix">
            <?=$post['Text']['contentHtml']?>
        </div>

        <form <?=$this->formAttr($form)?>><!-- Contact form -->
            <fieldset class="contact-fieldset">
                <h3>留言板</h3>
                <ul>
                    <li>
                    <label for="contactname">你的名字:</label>
                    <input type="text" name="name" id="contactname" value="" class="contact-input required" />
                    </li>
                    <li>
                    <label for="email">电话:</label>
                    <input type="text" id="email" name="phone" class="contact-input required email" />
                    </li>
                    <li>
                    <label for="im">QQ:</label>
                    <input type="text" id="im" name="im" class="contact-input" />
                    </li>
                    <li>
                    <label for="message">留言内容:</label>
                    <textarea rows="6" cols="40" id="message" name="message" class="contact-textarea required"></textarea>
                    </li>
                    <li>
                    <input type="submit" value="提交" name="submit" class="contact-submit" />
                    </li>                      
                </ul>
            </fieldset>
        </form>

    </div>

</div>
<div id="right">
    <?=$this->widget('Aier', 'widgets/side', $this->vars())?>
</div>  

