<?
$this->headTitle('在线订单', 'SET');
$method = 'post';

$gonggao = $this->action('Gwa\Api\Controller\FrontendController', 'postlistAction',array('category' => 'gonggao', 'rows' => 7));
$zhuanti = $this->action('Gwa\Api\Controller\FrontendController', 'postlistAction',array('category' => 'zhuanti', 'rows' => 7));

if($this->form){
	$form = $this->form;
} else {
    $form = Eva\Api::_()->getForm('Gwa\Form\ContactForm');
}
$form->init(array(
    'action' => $this->uri('/order/'),
    'method' => $method,
    'values' => ''
));
?>
<div class="container">
<ul class="breadcrumb">
	<li>您的位置：</li>
	<li class="">
		<a href="<?=$this->uri('/')?>">首页</a>
		<span class="divider">››</span>
	</li>
	<li class="">
    <a href="<?=$this->uri('/order/')?>">在线订单</a>
	</li>
</ul>
</div>


<div class="page">
<!-- #body start-->
<article id="body" class="body grid-s7m0">

	<!-- #main start-->
	<section id="main-wrap" class="main-wrap"><article id="main" class="main">
    <div id="blog">


        <div class="page_header large">
            <h2>在线订单</h2>
        </div>
        <hr class="white" />
        <?if($this->flashMessenger->getMessages()):?>
        <div id="post-create-succeed" class="alert alert-success">
            <a href="#" data-dismiss="alert" class="close">x</a>
            <h4 class="alert-heading">订单已提交</h4>
        </div>
        <?endif?>

        <form <?=$this->formAttr($form)?> class="form form-horizontal">
            <?=$form->restful();?>
            <div class="control-group <?=$form->isError('name') ? 'error' : '';?>">
                <?=$form->helper('name', 'label', array('class' => 'control-label'))?>
                <div class="controls">
                    <?=$form->helper('name', array('class' => 'input-xlarge'))?>        
                    <div class="help-block"><?=$form->helper('name', 'formElementErrors')?></div>
                </div>
            </div>
            <div class="control-group <?=$form->isError('phone') ? 'error' : '';?>">
                <?=$form->helper('phone', 'label', array('class' => 'control-label'))?>
                <div class="controls">
                    <?=$form->helper('phone', array('class' => 'input-xlarge'))?>        
                    <div class="help-block"><?=$form->helper('phone', 'formElementErrors')?></div>
                </div>
            </div>
            <div class="control-group <?=$form->isError('im') ? 'error' : '';?>">
                <?=$form->helper('im', 'label', array('class' => 'control-label'))?>
                <div class="controls">
                    <?=$form->helper('im', array('class' => 'input-xlarge'))?>        
                    <div class="help-block"><?=$form->helper('im', 'formElementErrors')?></div>
                </div>
            </div>
            <div class="control-group <?=$form->isError('message') ? 'error' : '';?>">
                <?=$form->helper('message', 'label', array('class' => 'control-label'))?>
                <div class="controls">
                    <?=$form->helper('message', 'formTextarea', array('class' => 'span6', 'rows' => '15'))?>        
                    <div class="help-block"><?=$form->helper('message', 'formElementErrors')?></div>
                </div>
            </div>
            <div class="form-actions">
                <button class="btn btn-primary" type="submit">提交</button>
            </div>

        </form>

    </div>


    </article></section>
    <!-- #main end-->

   <section id="sidebar" class="sidebar">

    <div class="article-menu">
        <ul>
            <li>
            <h3><a href="<?=$this->uri('/category/news')?>">
                    最新动态
                    <span class="divider">›</span>
            </a></h3>
            </li>
            <li>
            <h3><a href="<?=$this->uri('/category/jiudian')?>">
                    婚庆酒店
                    <span class="divider">›</span>
            </a></h3>
            </li>
            <li>
            <h3><a href="<?=$this->uri('/category/sheying')?>">
                    婚庆摄影
                    <span class="divider">›</span>
            </a></h3>
            </li>
            <li>
            <h3><a href="<?=$this->uri('/order/')?>">
                    在线订单
                    <span class="divider">›</span>
            </a></h3>
            </li>
        </ul>
    </div>

    <hr class="white">

    <div class="">
        <?=$this->widget('Gwa', 'components/ad')?>
        <div class="box-container-t15">
            <div class="tab-box square split3">
                <ul class="nav nav-tabs" id="side-news-tab">
                    <li class="active"><a href="#home">公告</a></li>
                    <li><a href="#profile">专题</a></li>
                    <li><a href="#messages">论坛</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="home"><div class="box-container-v15">
                        <?if($gonggao):?>        
                            <ul class="vlist textlist">
                                <?foreach($gonggao as $post):?>
                                    <li><a href="<?=$this->uri('/pages/' . $post['urlName'])?>" target="_blank" title=""><?=$post['title']?></a></li>
                                <?endforeach;?>    
                            </ul>
                        <?endif;?>
                    </div></div>
                    <div class="tab-pane" id="profile"><div class="box-container-v15">
                        <?if($zhuanti):?>        
                            <ul class="vlist textlist">
                                <?foreach($zhuanti as $post):?>
                                    <li><a href="<?=$this->uri('/pages/' . $post['urlName'])?>" target="_blank" title=""><?=$post['title']?></a></li>
                                <?endforeach;?>    
                            </ul>
                        <?endif;?>
                    </div></div>
                    <div class="tab-pane" id="messages">...</div>
                </div>
            </div>
        </div>
    </div><!--span3 end-->


    </section>

    <!-- #body end-->
    </article>
</div>

