<?
$title = $this->_('七彩梦圆澜沧江畔——告庄西双景景真寨之亿成阳光国际公寓');
$this->headTitle($title, 'SET');
?>


<!--FEATURES : STARTS--> 
<div class="row layout">
    <section id="third" class="twelve columns outer-wrap">
    <div class="story">
        <div class="bg"></div>
        <div class="nine columns add-top">

            <div class="placeholder"></div>
            <h2 class="main-heading-alt color-high">新闻动态</h2>

            <div class="placeholder"></div>

            <div class="row">
                <?if($this->items):?>
                <?foreach($this->items as $key=>$item):?>
                <div id="item_<?=$item['id'] ?>" class="skill-info">
                    <h3 class="dark-txt"><a href="<?=$this->Uri('/pages/' . $item['urlName'])?>" class="title"><?=$item['title'] ?></a></h3>
                    <p><?=$this->datetime($item['createTime'])?></p>
                    <p><?=$item['preview'];?></p>
                </div>
                <?endforeach;?>
                <?else:?>
                <p><?=$this->_('No blog item found')?></p>
                <?endif;?>

            </div>

            <?if($this->paginator):?>
            <?=$this->paginator->setPath('/pages/')->setBaseQuery($this->query);?>
            <?=$this->widget('Yicheng', 'widgets/paginator', $this->vars())?>
            <?endif;?>

        </div>

        <!-- End Right Column -->
        <div class="clearfix">
        </div>


    </div>
</div> 
<!--.story-->  
</section>
</div>
<!--FEATURES : ENDS--> 


