<?
$item = $this->item;
$title = 'Find Friends';
$title = $this->_($title);
$this->headTitle($title, 'SET');

$contacts = $this->contacts;

?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="page-main-header">
                            <h3><?=$this->_('Find Friends')?></h3>
                        </div>

                        <div class="well">
                            <a class="btn btn-large btn-block" href="<?=$this->uri('/contacts/import/', array('r' => $this->serverUrl() . '/account/addfriend/?service=google','service' => 'google'))?>">Find friends by Google Contacts</a>
                            <a class="btn btn-large btn-block" href="<?=$this->uri('/contacts/import/', array('r' => $this->serverUrl() . '/account/addfriend/?service=msn','service' => 'msn'))?>">Find friends by Hotmail/Live/MSN Contacts</a>
                        </div>




                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/accountnav', $this->vars())?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->
