<?
$item = $this->item;
$title = 'Find Friends';
$title = $this->_($title);
$this->headTitle($title, 'SET');

$inviteCode = $this->inviteCode;
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="page-main-header">
                            <h3><?=$this->_('Find Friends')?></h3>
                        </div>

                        <div class="well">
                            <a class="btn btn-large btn-block" href="<?=$this->uri('/contacts/import/', array('r' => $this->serverUrl() . '/account/addfriend/?service=google','service' => 'google'))?>">Find friends by Google Contacts</a>
                            <a class="btn btn-large btn-block" href="<?=$this->uri('/contacts/import/', array('r' => $this->serverUrl() . '/account/addfriend/?service=msn','service' => 'msn'))?>">Find friends by Hotmail/Live/MSN Contacts</a>
                        </div>

                        <div class="page-main-header">
                            <h3><?=$this->_('Invite Friends')?></h3>
                        </div>

                        <div class="well form">
                            <div class="control-group">
                                <label class="control-label" for="invite-url">Invite Link</label>
                                <div class="controls">
                                    <input type="text" id="invite-url" class="span8" value="<?=$this->serverUrl() . '/register/?code=' . $inviteCode?>" readonly="readonly" >
                                </div>
                            </div>
                        </div>


                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/accountnav', $this->vars())?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->
