<?
$item = $this->item;
$title = 'Account Setting';
$title = $this->_($title);
$this->headTitle($title, 'SET');

if(!$this->form){
    $form = new Epic\Form\AccountEditForm();
    $form->useSubFormGroup();
}

$form->setMethod($item['id'] ? 'put' : 'post');
$form->setView($this)
    ->setAction($this->uri('/account/setting/'))
     ->bind($item)
     ->prepare();

?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="page-main-header">
                            <h3><?=$this->_('Account Setting')?></h3>
                        </div>
                        <div class="accordion">
                            <div class="accordion-group">
                                <div class="accordion-heading">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseOne">
                                        Change Email
                                    </a>
                                </div>
                                <div id="collapseOne" class="accordion-body collapse in">
                                    <div class="accordion-inner">
                        <form <?=$this->formAttr($form)?> class="form">
                            <?=$form->restful();?>
                            <?=$form->helper('id');?>
                            <input type="hidden" name="callback" value="<?=$this->uri('/account/profile/')?>" />

                            <fieldset class="form-horizontal">


                                <div class="control-group <?=$form->isError(array('Profile', 'bio')) ? 'error' : '';?>">
                                    <?=$form->helper(array('Profile', 'bio'), 'label', array('class' => 'control-label'))?>
                                    <div class="controls">
                                        <?=$form->helper(array('Profile', 'bio'), 'formTextarea', array('class' => ''))?>        
                                        <div class="help-block"><?=$form->helper(array('Profile', 'bio'), 'formElementErrors')?></div>
                                    </div>
                                </div>

                                <div class="form-actions">
                                    <button id="save-publish" class="btn btn-success btn-large"><?=$this->_('Save')?></button>
                                </div>
                            </fieldset>
                        </form>
                                    </div>
                                </div>
                            </div>
                            <div class="accordion-group">
                                <div class="accordion-heading">
                                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion2" href="#collapseTwo">
                                        Change Password
                                    </a>
                                </div>
                                <div id="collapseTwo" class="accordion-body collapse">
                                    <div class="accordion-inner">
                                    </div>
                                </div>
                            </div>
                        </div>


                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/accountnav', $this->vars())?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->
