<?
$config = $this->getHelperPluginManager()->getServiceLocator()->get('config');
$thumbUrl = $config['upload']['storage']['default']['thumburl'];
?><!DOCTYPE html>

<!-- paulirish.com/2008/conditional-stylesheets-vs-css-hacks-answer-neither/ -->
<!--[if lt IE 7]> <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang="en"> <![endif]-->
<!--[if IE 7]>    <html class="no-js lt-ie9 lt-ie8" lang="en"> <![endif]-->
<!--[if IE 8]>    <html class="no-js lt-ie9" lang="en"> <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en"> <!--<![endif]-->

<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <?=$this->headTitle()?>
    <?$this->assets('/module/admin/css/bootstrap.css')?>
    <!--[if lt IE 9]>
    <meta http-equiv="PRAGMA" content="NO-CACHE" />
    <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
    <![endif]-->
    <meta name="viewport" content="width=device-width,initial-scale=1"/>

    <script src="<?=$this->assets('/module/yicheng/javascripts/modernizr.foundation.js')?>"></script>
    <?=$this->googleAnalytics()?>
    <?=$this->evajs()?>
    <?=$this->headMeta()?>
    <?=$this->headStyle()?>
    <?$this->cssAssets(array(
        '/lib/css/fontawesome/css/font-awesome.css',
        '/lib/css/foundation/foundation.css',
        '/module/yicheng/stylesheets/typography.css',
        '/module/yicheng/stylesheets/myworks.css',
        '/module/yicheng/stylesheets/jquery.fancybox-thumbs.css',
        '/module/yicheng/stylesheets/jquery.fancybox.css',
        '/module/yicheng/stylesheets/jquery.fancybox-buttons.css',
        '/module/yicheng/stylesheets/app.css',
    ));?>
    <?$this->jsAssets(array(
        '/lib/js/labjs/labjs.js',
        '/lib/js/jquery/jquery.js',
        '/module/core/js/core.js',
        '/module/core/js/ui.js',
    ));?>
    <?=$this->headLink()?>
    <?=$this->headScript()?>
</head>

<body>

    <div class="row">

        <div class="twelve columns">
            <nav id="navbar" class="top-bar fixed">
            <div class="main-nav">
                <ul>
                    <!-- Title Area -->
                    <li class="name">
                    <h1>
                        <a href="<?=$this->uri('/')?>">
                            亿成阳光公寓
                        </a>
                    </h1>
                    </li>
                    <li class="toggle-topbar"><a href="#"></a></li>
                </ul>

                <section>
                <!-- Left Nav Section -->
                <ul class="left">
                    <li class="divider"></li>
                    <li><a href="<?=$this->uri('/home')?>" title="Next Section">首页</a></li>
                    <li class="divider"></li>
                    <li><a href="<?=$this->uri('/index/overview/')?>" title="Next Section">项目概况</a></li>
                    <li class="divider"></li>
                    <li class="has-dropdown">
                    <a class="active" href="#">整体规划</a>
                    <ul class="dropdown">
                        <li><a href="<?=$this->uri('/pages/ziranhuanjing')?>">自然环境</a></li>
                        <li><a href="<?=$this->uri('/pages/chanpinbuju')?>">产品布局</a></li>
                    </ul>
                    </li>
                    <li class="divider"></li>
                    <li class="has-dropdown">
                    <a class="active" href="#">图册欣赏</a>
                    <ul class="dropdown">
                        <li><a href="<?=$this->uri('/album/yuanlin')?>">园林景观</a></li>
                        <li><a href="<?=$this->uri('/album/shijing')?>">房产实景</a></li>
                        <li><a href="<?=$this->uri('/album/pingmianzhanshi')?>">平面展示</a></li>
                    </ul>
                    </li>

                    <li class="divider"></li>
                    <li><a href="<?=$this->uri('/index/huxing')?>" title="Next Section">户型鉴赏</a></li>
                    <li class="divider"></li>
                    <li><a href="<?=$this->uri('/index/jiazhi')?>" title="Next Section">投资价值</a></li>
                    <li class="divider"></li>
                    <!--<li><a href="<?=$this->uri('/pages/ziranhuanjing')?>" title="Next Section">VIP优惠信息</a></li>-->
                    <li class="divider"></li>
                    <li><a href="<?=$this->uri('/pages/')?>" title="Next Section">新闻动态</a></li>
                    <li class="divider"></li>
                    <li >
                    <a href="<?=$this->uri('/index/fuwu')?>">客户服务</a>
                    </li>

                </ul>

                </section>
            </div>
            </nav>
        </div>
    </div>

    <?=$this->content;?>

    <div class="row layout box-shadow">
        <section id="footer" class="twelve columns outer-wrap">
        <div id="footer-inner">
        <div class="main-nav">
            <div class="row">
                <div class="four columns">
                    <div class="">
                        <ul class="square">
                            <li><a href="<?=$this->uri('/home')?>" title="Next Section">首页</a></li>
                            <li><a href="<?=$this->uri('/index/overview/')?>" title="Next Section">项目概况</a></li>
                            <li class="has-dropdown">
                            <a class="active" href="#">整体规划</a>
                            <ul class="dropdown">
                                <li><a href="<?=$this->uri('/pages/ziranhuanjing')?>">自然环境</a></li>
                                <li><a href="<?=$this->uri('/pages/chanpinbuju')?>">产品布局</a></li>
                            </ul>
                            </li>
                            <li><a href="<?=$this->uri('/pages/ziranhuanjing')?>" title="Next Section">VIP优惠信息</a></li>
                            <li><a href="<?=$this->uri('/pages/')?>" title="Next Section">新闻动态</a></li>
                        </ul>
                    </div>
                </div>
                <div class="four columns">
                    <div class="">
                        <ul class="square">
                            <li class="has-dropdown">
                            <a class="active" href="#">图册欣赏</a>
                            <ul class="dropdown">
                                <li><a href="<?=$this->uri('/album/yuanlinjinguan')?>">园林景观</a></li>
                                <li><a href="<?=$this->uri('/album/fangchanshijing')?>">房产实景</a></li>
                                <li><a href="<?=$this->uri('/album/pingmianzhanshi')?>">平面展示</a></li>
                            </ul>
                            </li>
                            <li><a href="<?=$this->uri('/index/huxing')?>" title="Next Section">户型鉴赏</a></li>
                            <li><a href="<?=$this->uri('/index/jiazhi')?>" title="Next Section">投资价值</a></li>
                            <li >
                            <a href="<?=$this->uri('/home/')?>#seventh">客户服务</a>
                            </li>
                        </ul>
                    </div>
                </div>
                <div class="four columns">
                    <div class="">
                        <p><a target="_blank" href="http://yichengguoji.cn/">亿成国际投资集团</a><br/>Copyright &copy; 2012 亿成国际投资集团
                        <br />销售地址：北京市朝阳区万达广场A座21层 <br />销售热线：0086-010-58205909 / 58205910</p>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!--.story-->  
    </section>
    </div>

    <!--CONTACT : ENDS-->




    <!-- Included JS Files (Compressed) -->
    <script src="<?=$this->assets('/lib/js/foundation/foundation.min.js')?>"></script>

    <!-- Initialize JS Plugins -->
    <script src="<?=$this->assets('/module/yicheng/javascripts/jquery.easing.1.3.js')?>"></script>
    <script src="<?=$this->assets('/module/yicheng/javascripts/jquery.parallax-1.1.3.js')?>"></script>
    <script src="<?=$this->assets('/module/yicheng/javascripts/jquery.localscroll-1.2.7-min.js')?>"></script>
    <script src="<?=$this->assets('/module/yicheng/javascripts/jquery.scrollTo-1.4.2-min.js')?>"></script>
    <!-- Add mousewheel plugin (this is optional) -->
    <script src="<?=$this->assets('/module/yicheng/javascripts/jquery.mousewheel-3.0.6.pack.js')?>"></script>

    <!-- Add fancyBox main JS and CSS files -->
    <script src="<?=$this->assets('/module/yicheng/javascripts/jquery.fancybox.js')?>?v=2.1.0"></script>
    <script src="<?=$this->assets('/module/yicheng/javascripts/jquery.fancybox-buttons.js')?>?v=1.0.3"></script>

    <!-- Add Thumbnail helper (this is optional) -->
    <script src="<?=$this->assets('/module/yicheng/javascripts/jquery.fancybox-thumbs.js')?>?v=1.0.6"></script>

    <!-- Add Media helper (this is optional) -->
    <script src="<?=$this->assets('/module/yicheng/javascripts/jquery.fancybox-media.js')?>?v=1.0.3"></script>
    <script src="<?=$this->assets('/module/yicheng/javascripts/jquery.quicksand.js')?>"></script>
    <script src="<?=$this->assets('/module/yicheng/javascripts/filter.js')?>"></script>  
    <script src="<?=$this->assets('/module/yicheng/javascripts/form-validation.js')?>"></script>  
    <script src="<?=$this->assets('/module/yicheng/javascripts/jquery.tweet.js')?>"></script>
    <script src="<?=$this->assets('/module/yicheng/javascripts/jquery.transit.min.js')?>"></script>
    <script src="<?=$this->assets('/module/yicheng/javascripts/app.js')?>"></script>
    <script src="<?=$this->assets('/module/yicheng/javascripts/jquery.fullscreen.js')?>"></script>
    <script>
        $(".fancybox-effects-d").fancybox({
                padding: 0,
                openEffect : 'elastic',
                openSpeed  : 150,
                closeEffect : 'elastic',
                closeSpeed  : 150,
                closeClick : true,
                helpers : {
                        overlay : null
                }
        });
        $('.fancybox-media')
        .attr('rel', 'media-gallery')
        .fancybox({
                openEffect : 'none',
                closeEffect : 'none',
                prevEffect : 'none',
                nextEffect : 'none',

                arrows : false,
                helpers : {
                        media : {},
                        buttons : {}
                }
        });
    </script>

</body>
</html>
