<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"><![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"><![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"><![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"><!--<![endif]-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <?=$this->headTitle()?>
    <!--[if lt IE 9]>
    <meta http-equiv="PRAGMA" content="NO-CACHE" />
    <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
    <![endif]-->
    <meta name="viewport" content="width=device-width,initial-scale=1"/>

    <?=$this->googleAnalytics()?>
    <?=$this->evajs()?>
    <?=$this->headMeta()?>
    <?=$this->headStyle()?>
    <?$this->cssAssets(array(
        '/module/yicheng/index/css/style.css',
    ));?>
    <?$this->jsAssets(array(
        '/lib/js/labjs/labjs.js',
        '/lib/js/jquery/jquery.js',
        '/module/yicheng/index/js/flexslider.js',
        '/module/yicheng/index/js/jquery.isotope.min.js',
        '/module/yicheng/index/js/custom.js',
        '/module/yicheng/index/js/ender.min.js',
        '/module/yicheng/index/js/selectnav.js',
        '/module/yicheng/index/js/imagebox.min.js',
        '/module/yicheng/index/js/carousel.js',
        '/module/yicheng/index/js/tooltip.js',
        '/module/yicheng/index/js/popover.js',
        '/module/yicheng/index/js/effects.js',
        '/module/yicheng/index/js/cufon-yui.js',
    ));?>
    <?=$this->headLink()?>
    <?=$this->headScript()?>
    <style>
        body {
                font-family:Microsoft YaHei,Trebuchet MS, Verdana, Helvetica, Arial, sans-serif;
        }
        h1,h2,h3,h4,h5,h6,p {
                font-family:Microsoft YaHei,Trebuchet MS, Verdana, Helvetica, Arial, sans-serif;
        }
        #navigation ul li a{
                font-family:Microsoft YaHei,Trebuchet MS, Verdana, Helvetica, Arial, sans-serif;
                font-size:20px;
                font-weight:bold;
        }
        #index-title {
                font-size:20px;
        }
        .flexslider, .custom-slide {
                height:540px;
        }
        #footer a {
            color:#A4A4A4;
        }
        #footer a:hover {
            color:#FFFFFF;
        }
        .portfolio-item-meta h5 {
            font-family:Microsoft YaHei,Trebuchet MS, Verdana, Helvetica, Arial, sans-serif;
            font-size:15px;
        }
        #slider {
                border-top:10px solid #666;
                border-bottom:10px solid #666;
        }
    </style>
</head>

<body>

    <!-- Header -->
    <div id="header">

        <!-- 960 Container Start -->
        <div class="container ie-dropdown-fix">

            <!-- Logo -->
            <div class="five columns">
                <a href="#"><img src="<?=$this->assets("/module/yicheng/index/images/logo.png")?>" alt=""/></a>
            </div>

            <!-- Main Navigation Start -->
            <div class="eleven columns">
                <div id="navigation">
                    <ul id="nav">
                        <li><a href="/">关于亿成</a>
                        </li>
                        <li><a href="#">项目介绍</a>
                        </li>
                        <li><a href="#">投资人关系</a>
                        </li>
                        <li><a href="#">集团新闻</a></li>
                        <li><a href="#">在线客服</a></li>
                    </ul>
                </div>
            </div>
            <!-- Main Navigation End -->

        </div>
        <!-- 960 Container End -->

    </div>
    <!-- End Header -->


    <!-- Slider -->
    <div id="slider">

        <!-- Flexslider Start-->
        <div class="flexslider" style="background: #fafafa;">
            <ul class="slides">
                <?for($i=1;$i<=10;$i++):?>
                <!-- Slide -->
                <li class="custom-slide" style="background: url(<?=$this->assets("/module/yicheng/index/images/bg$i.jpg")?>)">
                <div class="container">
                    <div class="sixteen columns">
                    </div>
                </div>
                </li>
                <?endfor?>
            </ul>
        </div>
        <!-- Flexslider End-->

    </div>
    <!-- End Slider -->

    <!-- 960 Container Start -->
    <div class="container">

        <!--Recent Work -->
        <div class="sixteen columns">
            <h4 id="index-title" class="headline">集团业务</h4>
        </div>

        <!-- 1/3 Column -->
        <div class="one-third column">
            <div class="item-img"><a href="#"><img src="<?=$this->assets("/module/yicheng/index/images/1.jpg")?>" alt=""/></a></div>
            <div class="portfolio-item-meta">
                <h5><a href="#">金融产业</a></h5>
                <p>集团及各分公司核心人员均系拥有多年国际市场投资经验，与国际知名金融机构有着良好的合作关系的高知人士。我们创建了一套完善的投资理念和科学的风险管理方法；通过国际投资集团专家团队的技术分析指导,日夜紧贴市场走势,提供国际性最新,最快,最专业的信息。</p>
            </div>
        </div>

        <!-- 1/3 Column -->
        <div class="one-third column">
            <div class="item-img"><a href="/home/"><img src="<?=$this->assets("/module/yicheng/index/images/4.jpg")?>" alt=""/></a></div>
            <div class="portfolio-item-meta">
                <h5><a href="/home/">房地产业</a></h5>
                <p>亿成国际以专业投资眼光考察评估地产项目，准确定位，寻找良机，以雄厚实力投入多个省市房地产业发展，已取得良好业绩。多年经营使亿成国际在房地产领域愈加成熟，房地产投资跨越多种类型，从商业地产，旅游地产，到住宅别墅，已帮助很多客户成功置业投资，并使亿成国际商业触角不断延伸。</p>
            </div>
        </div>

         <!-- 1/3 Column -->
        <div class="one-third column">
            <div class="item-img"><a href="#"><img src="<?=$this->assets("/module/yicheng/index/images/2.jpg")?>" alt=""/></a></div>
            <div class="portfolio-item-meta">
                <h5><a href="#">能源产业</a></h5>
                <p>21世纪中国能源产业面临发展和风险共存的局面，开拓海外市场势在必行。亿成国际以雄厚实力成功挺进能源领域，已在能源储备丰富的俄罗斯站稳脚跟，并将在满洲里建设能源企业园区。随着企业发展，未来亿成国际必将为中国能源产业做出巨大贡献。</p>
            </div>
        </div>

        <div class="clearfix"></div>

        <!--Latest From Blog -->
        <div class="sixteen columns">
            <!--<h4 class="headline">Latest From Blog</h4>-->


            <!-- 1/4 Column -->
            <div class="four columns alpha">
                <div class="item-img"><a href="#"><img src="<?=$this->assets("/module/yicheng/index/images/3.jpg")?>" alt=""/></a></div>
                <div class="portfolio-item-meta">
                    <h5><a href="#">国际贸易</a></h5>
                    <p>亿成国际团队具有精辟的市场分析能力和良好的市场控制能力，一线人员均具有多年相关工作经验。依托多年的市场积累，公司逐渐形成了国际贸易运作模式和健全的管理模式，并且配有常年的法律顾问。</p>
                </div>
            </div>

            <!-- 1/4 Column -->
            <div class="four columns">
                <div class="item-img"><a href="#"><img src="<?=$this->assets("/module/yicheng/index/images/5.jpg")?>" alt=""/></a></div>
                <div class="portfolio-item-meta">
                    <h5><a href="#">旅游产业</a></h5>
                    <p>经过几年来在旅游产业的深入研究，亿成国际未来将扩大思维半径，在吃住行游购娱六大方面交叉营销，实现旅游产业突破性发展。</p>
                </div>
            </div>

            <!-- 1/4 Column -->
            <div class="four columns omega">
                <div class="item-img"><a href="#"><img src="<?=$this->assets("/module/yicheng/index/images/6.jpg")?>" alt=""/></a></div>
                <div class="portfolio-item-meta">
                    <h5><a href="#">生物科技</a></h5>
                    <p>亿成国际在张北地区兴建高品质北冬虫夏草生产基地，未来将开发系列产品，使更多人享受到品质高于冬虫夏草，价格却可被寻常百姓接受的“北冬虫夏草”。</p>
                </div>
            </div>

            <!-- 1/4 Column -->
            <div class="four columns omega">
                <div class="item-img"><a href="#"><img src="<?=$this->assets("/module/yicheng/index/images/7.jpg")?>" alt=""/></a></div>
                <div class="portfolio-item-meta">
                    <h5><a href="#">文化产业</a></h5>
                    <p>亿成国际将发展文化产业视为社会责任的体现。在推出文化产品的同时，倡导绿色环保理念与中国原创的发展方向，为文化产业良好发展添砖加瓦。</p>
                </div>
            </div>

        </div>


    </div>
    <!-- 960 Container End -->

    <!-- Footer Start -->
    <div id="footer">

        <!-- 960 Container -->
        <div class="container">

            <div class="four columns">
                <h5>关于亿成</h5>
                <div class="links-list">
                    <p><a href="#">集团简介</a></p>
                    <p><a href="#">组织架构</a></p>
                    <p><a href="#">组织架构</a></p>
                    <p><a href="#">组织架构</a></p>
                    <p><a href="#">组织架构</a></p>
                </div>

            </div>



            <!-- Useful Links -->
            <div class="eight columns">
                <h5>集团成员</h5>
                <ul class="links-list">
                    <li><a href="#">亿成国际投资集团</a></li>
                    <li><a href="#">河北亿成投资有限公司</a></li>
                    <li><a href="#">亿成张家口壹善北虫草生产基地</a></li>
                    <li><a href="#">亿成阳光房地产开发有限公司</a></li>
                    <li><a href="#">亿成国际天正文化传媒有限公司</a></li>
                    <li><a href="#">天津合而壹股份投资基金管理有限公司</a></li>
                </ul>
            </div>
            <!-- About -->
            <div class="four columns">
                <h5>关于亿成</h5>
                <p>电话：010-58207072</p>
                <p>传真：010-58207760</p>
                <p>地址：北京市朝阳区建国路93号万达广场A座21层</p>
                <p>邮编：100026</p>
            </div>


        </div>
        <!-- Footer End -->



        <!-- Back To Top Button -->
        <div id="backtotop"><a href="#"></a></div>

        <!-- Imagebox Build -->
        <script src="<?=$this->assets("/module/yicheng/index/js/imagebox.build.js")?>"></script>
        <script>
            Cufon.replace ('#nav a, h4, h5', {fontFamily: 'Microsoft YaHei'});
        </script>

    </body>
</html>
