<!DOCTYPE html>
<!--[if lt IE 7 ]><html class="ie ie6" lang="en"><![endif]-->
<!--[if IE 7 ]><html class="ie ie7" lang="en"><![endif]-->
<!--[if IE 8 ]><html class="ie ie8" lang="en"><![endif]-->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"><!--<![endif]-->
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <?=$this->headTitle()?>
    <!--[if lt IE 9]>
    <meta http-equiv="PRAGMA" content="NO-CACHE" />
    <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
    <![endif]-->
    <meta name="viewport" content="width=device-width,initial-scale=1"/>

    <?=$this->googleAnalytics()?>
    <?=$this->evajs()?>
    <?=$this->headMeta()?>
    <?=$this->headStyle()?>
    <?$this->cssAssets(array(
        '/module/yicheng/index/css/style.css',
    ));?>
    <?$this->jsAssets(array(
        '/lib/js/labjs/labjs.js',
        '/lib/js/jquery/jquery.js',
        '/module/yicheng/index/js/flexslider.js',
        '/module/yicheng/index/js/jquery.isotope.min.js',
        '/module/yicheng/index/js/custom.js',
        '/module/yicheng/index/js/ender.min.js',
        '/module/yicheng/index/js/selectnav.js',
        '/module/yicheng/index/js/imagebox.min.js',
        '/module/yicheng/index/js/carousel.js',
        '/module/yicheng/index/js/tooltip.js',
        '/module/yicheng/index/js/popover.js',
        '/module/yicheng/index/js/effects.js',
    ));?>
    <?=$this->headLink()?>
    <?=$this->headScript()?>
    <style>
        body {
                font-family:Microsoft YaHei,Trebuchet MS, Verdana, Helvetica, Arial, sans-serif;
        }
        h1,h2,h3,h4,h5,h6,p {
                font-family:Microsoft YaHei,Trebuchet MS, Verdana, Helvetica, Arial, sans-serif;
        }
        #navigation ul li a{
                font-family:Microsoft YaHei,Trebuchet MS, Verdana, Helvetica, Arial, sans-serif;
                font-size:18px;
        }
        #index-title {
                font-size:20px;
        }
        .flexslider, .custom-slide {
                height:540px;
        }
        #footer a {
            color:#A4A4A4;
        }
        #footer a:hover {
            color:#FFFFFF;
        }
    </style>
</head>

<body>

    <!-- Header -->
    <div id="header">

        <!-- 960 Container Start -->
        <div class="container ie-dropdown-fix">

            <!-- Logo -->
            <div class="five columns">
                <a href="#"><img src="<?=$this->assets("/module/yicheng/index/images/logo.png")?>" alt=""/></a>
            </div>

            <!-- Main Navigation Start -->
            <div class="eleven columns">
                <div id="navigation">
                    <ul id="nav">
                        <li><a id="current" href="/">关于亿成</a>
                        </li>
                        <li><a href="#">项目介绍</a>
                        </li>
                        <li><a href="#">投资人关系</a>
                        </li>
                        <li><a href="#">集团新闻</a></li>
                        <li><a href="#">在线客服</a></li>
                    </ul>
                </div>
            </div>
            <!-- Main Navigation End -->

        </div>
        <!-- 960 Container End -->

    </div>
    <!-- End Header -->


    <!-- Slider -->
    <div id="slider">

        <!-- Flexslider Start-->
        <div class="flexslider" style="background: #fafafa;">
            <ul class="slides">
                <?for($i=1;$i<=10;$i++):?>
                <!-- Slide -->
                <li class="custom-slide" style="background: url(<?=$this->assets("/module/yicheng/index/images/bg$i.jpg")?>)">
                <div class="container">
                    <div class="sixteen columns">
                    </div>
                </div>
                </li>
                <?endfor?>
            </ul>
        </div>
        <!-- Flexslider End-->

    </div>
    <!-- End Slider -->

    <!-- 960 Container Start -->
    <div class="container">

        <!--Recent Work -->
        <div class="sixteen columns">
            <h4 id="index-title" class="headline">集团业务</h4>
        </div>

        <!-- 1/3 Column -->
        <div class="one-third column">
            <div class="item-img"><a href="images/portfolio_images/portfolio_3_01_large.jpg" rel="imagebox" title="SockMonkee"><img src="images/portfolio_images/portfolio_3_01.jpg" alt=""/><div class="overlay zoom"></div></a></div>
            <div class="portfolio-item-meta">
                <h5><a href="single_project.html">SockMonkee</a></h5>
                <p>Aenean sit amet ligula est, conseact etur lectus. Maecenas hendrerit, lorem.</p>
            </div>
        </div>

        <!-- 1/3 Column -->
        <div class="one-third column">
            <div class="item-img"><a href="single_project.html"><img src="images/portfolio_images/portfolio_3_06.jpg" alt=""/><div class="overlay zoom"></div></a></div>
            <div class="portfolio-item-meta">
                <h5><a href="single_project.html">Franky Fisticuffs</a></h5>
                <p>Aenean sit amet ligula est, conseact etur lectus. Maecenas hendrerit, lorem.</p>
            </div>
        </div>

        <!-- 1/3 Column -->
        <div class="one-third column">
            <div class="item-img"><a href="single_project.html"><img src="images/portfolio_images/portfolio_3_04.jpg" alt=""/><div class="overlay zoom"></div></a></div>
            <div class="portfolio-item-meta">
                <h5><a href="single_project.html">Package Project</a></h5>
                <p>Gravida sit amet ligula eget conseact etur lectu aecenas hendrerit bibenea.</p>
            </div>
        </div>

        <div class="clearfix"></div>

        <!--Latest From Blog -->
        <div class="sixteen columns">
            <!--<h4 class="headline">Latest From Blog</h4>-->


            <!-- 1/4 Column -->
            <div class="four columns alpha">
                <div class="item-img"><a href="blog_post.html"><img src="images/portfolio_images/portfolio_3_07.jpg" alt=""/><div class="overlay zoom"></div></a></div>
                <div class="portfolio-item-meta">
                    <h5><a href="single_project.html">Spaghetti Western</a> <span>June 25, 2012 / 12 Comments</span></h5>
                    <p>Aenean sit amet ligula est, conseact etur lectus. Maecenas hendrerit, lorem.</p>
                </div>
            </div>

            <!-- 1/4 Column -->
            <div class="four columns">
                <div class="item-img"><a href="blog_post.html"><img src="images/portfolio_images/portfolio_3_03.jpg" alt=""/><div class="overlay zoom"></div></a></div>
                <div class="portfolio-item-meta">
                    <h5><a href="single_project.html">Monster Calendar</a> <span>June 22, 2012 / 24 Comments</span></h5>
                    <p>Aenean sit amet ligula est, conseact etur lectus. Maecenas hendrerit, lorem.</p>
                </div>
            </div>

            <!-- 1/4 Column -->
            <div class="four columns omega">
                <div class="item-img"><a href="blog_post.html"><img src="images/portfolio_images/portfolio_3_05.jpg" alt=""/><div class="overlay zoom"></div></a></div>
                <div class="portfolio-item-meta">
                    <h5><a href="single_project.html">Prime Art League</a> <span>June 21, 2012 / 8 Comments</span></h5>
                    <p>Gravida sit amet ligula eget conseact etur lectu aecenas hendrerit bibenea.</p>
                </div>
            </div>

            <!-- 1/4 Column -->
            <div class="four columns omega">
                <div class="item-img"><a href="blog_post.html"><img src="images/portfolio_images/portfolio_3_05.jpg" alt=""/><div class="overlay zoom"></div></a></div>
                <div class="portfolio-item-meta">
                    <h5><a href="single_project.html">Prime Art League</a> <span>June 21, 2012 / 8 Comments</span></h5>
                    <p>Gravida sit amet ligula eget conseact etur lectu aecenas hendrerit bibenea.</p>
                </div>
            </div>

        </div>


    </div>
    <!-- 960 Container End -->

    <!-- Footer Start -->
    <div id="footer">

        <!-- 960 Container -->
        <div class="container">

            <div class="four columns">
                <h5>关于亿成</h5>
                <div class="links-list">
                    <p><a href="#">集团简介</a></p>
                    <p><a href="#">组织架构</a></p>
                    <p><a href="#">组织架构</a></p>
                    <p><a href="#">组织架构</a></p>
                    <p><a href="#">组织架构</a></p>
                </div>

            </div>



            <!-- Useful Links -->
            <div class="eight columns">
                <h5>集团成员</h5>
                <ul class="links-list">
                    <li><a href="#">亿成国际投资集团</a></li>
                    <li><a href="#">河北亿成投资有限公司</a></li>
                    <li><a href="#">亿成张家口壹善北虫草生产基地</a></li>
                    <li><a href="#">亿成阳光房地产开发有限公司</a></li>
                    <li><a href="#">亿成国际天正文化传媒有限公司</a></li>
                    <li><a href="#">天津合而壹股份投资基金管理有限公司</a></li>
                </ul>
            </div>
            <!-- About -->
            <div class="four columns">
                <h5>关于亿成</h5>
                <p>电话：010-58207072</p>
                <p>传真：010-58207760</p>
                <p>地址：北京市朝阳区建国路93号万达广场A座21层</p>
                <p>邮编：100026</p>
            </div>


        </div>
        <!-- Footer End -->



        <!-- Back To Top Button -->
        <div id="backtotop"><a href="#"></a></div>

        <!-- Imagebox Build -->
        <script src="<?=$this->assets("/module/yicheng/index/js/imagebox.build.js")?>"></script>

    </body>
</html>
