<?
$item = $this->item;
$title = 'My Albums';
$title = $this->_($title);
$this->headTitle($title, 'SET');
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span6">
                                <div class="page-main-header">
                                    <a href="<?=$this->uri('/albums/create/')?>" class="btn btn-small btn-orange pull-right">Create New</a>
                                    <h3><?=$this->_($title)?></h3>
                                </div>
                                <div class="album-list">
                                    <?for($i=0;$i<4;$i++):?>
                                    <div class="row-fluid stack-row">
                                        <?for($j=0;$j<3;$j++):?>
                                        <div class="span4">
                                            <div class="stack">	
                                                <a href="">
                                                    <img src="<?=$this->assets('/module/epic/img/album-default.png')?>" width="180" alt="" />
                                                </a>
                                            </div>
                                        </div>
                                        <?endfor;?>
                                    </div>
                                    <?endfor;?>
                                </div><!--album-list end-->
                                <?if($this->paginator):?>
                                <?=$this->paginator->setPath('/my/event/')->setBaseQuery($this->query);?>
                                <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                                <?endif;?>

                            </div><!--page main left end-->
                            <div class="span3">
                                <div class="page-extra">
                                    <?=$this->widget('Epic', 'widgets/userextra', $this->vars())?>
                                </div>
                            </div><!--page main right end-->
                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside')?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->

