<?
$this->headTitle('Switch City', 'SET');	
$item = $this->item;
$title = 'Select Your Current City';
$title = $this->_($title);
$this->headTitle($title, 'SET');
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">
            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span9">
                                <div class="page-main-header">
                                    <a href="<?=$this->uri('/events/')?>" class="btn btn-small btn-orange pull-right">Back to Event</a>
                                    <h3><?=$this->_($title)?></h3>
                                </div>

                                <div class="typo typocn switch-city">
                                    <div class="page-header border-header">
                                        <h2>EUROPE</h2>
                                    </div>
                                    <ul class="row">
                                        <li class="span2"><a href="#">Amsterdam</a></li>
                                        <li class="span2"><a href="#">Florence</a></li>
                                        <li class="span2"><a href="#">Prague</a></li>
                                        <li class="span2"><a href="#">Athens</a></li>
                                        <li class="span2"><a href="#">Istanbul</a></li>
                                        <li class="span2"><a href="#">Rome</a></li>
                                        <li class="span2"><a href="#">Barcelona</a></li>
                                        <li class="span2"><a href="#">Lisbon</a></li>
                                        <li class="span2"><a href="#">Seville</a></li>
                                        <li class="span2"><a href="#">Berlin</a></li>
                                        <li class="span2"><a href="#">London</a></li>
                                        <li class="span2"><a href="#">Venice</a></li>
                                        <li class="span2"><a href="#">Brussels</a></li>
                                        <li class="span2"><a href="#">Madrid</a></li>
                                        <li class="span2"><a href="#">Vienna</a></li>
                                        <li class="span2"><a href="#">Budapest</a></li>
                                        <li class="span2"><a href="#">Milan</a></li>
                                        <li class="span2"><a href="#">Zurich</a></li>
                                        <li class="span2"><a href="#">Copenhagen</a></li>
                                        <li class="span2"><a href="#">Naples</a></li>
                                        <li class="span2"><a href="#">Dublin</a></li>
                                        <li class="span2"><a href="#">Paris</a></li>
                                    </ul>
                                    <div class="page-header border-header">
                                        <h2>Africa & Middle EAST</h2>
                                    </div>
                                    <ul class="row">
                                        <li class="span2"><a href="#">Cairo</a></li>
                                        <li class="span2"><a href="#">Marrakech</a></li>
                                        <li class="span2"><a href="#">Tel Aviv</a></li>
                                    </ul>
                                    <div class="page-header border-header">
                                        <h2>Amercia</h2>
                                    </div>
                                    <ul class="row">
                                        <li class="span2"><a href="#">Las Vegas</a></li>
                                        <li class="span2"><a href="#">Los Angeles</a></li>
                                        <li class="span2"><a href="#">Miami</a></li>
                                        <li class="span2"><a href="#">New York</a></li>
                                        <li class="span2"><a href="#">San Francisco</a></li>
                                        <li class="span2"><a href="#">Washington D.C.</a></li>
                                        <li class="span2"><a href="#">Buenos Aires</a></li>
                                        <li class="span2"><a href="#">Rio De Janeiro</a></li>
                                        <li class="span2"><a href="#">San Paulo</a></li>
                                    </ul>
                                    <div class="page-header border-header">
                                        <h2>Asia</h2>
                                    </div>
                                    <ul class="row">
                                        <li class="span2"><a href="#">Shanghai</a></li>
                                        <li class="span2"><a href="#">Beijing</a></li>
                                        <li class="span2"><a href="#">Guangzhou</a></li>
                                        <li class="span2"><a href="#">Nanjing</a></li>
                                        <li class="span2"><a href="#">Hong Kong</a></li>
                                        <li class="span2"><a href="#">Singapore</a></li>
                                    </ul>

                                </div>
                            </div><!--page main left end-->

                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside')?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->
