<?
$item = $this->item;
$title = 'My Groups';
$title = $this->_($title);
$this->headTitle($title, 'SET');
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span6">
                                <div class="page-main-header">
                                    <a href="<?=$this->uri('/event/create/')?>" class="btn btn-small btn-orange pull-right">Write New</a>
                                    <h3><?=$this->_($title)?></h3>
                                </div>
                                <div class="event-list vlist">
                                    Under Building
                                </div><!--activity-list end-->
                                <?if($this->paginator):?>
                                <?=$this->paginator->setPath('/my/event/')->setBaseQuery($this->query);?>
                                <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                                <?endif;?>

                            </div><!--page main left end-->
                            <div class="span3">
                                <div class="page-extra">
                                    <?=$this->widget('Epic', 'widgets/userextra')?>
                                </div>
                            </div><!--page main right end-->
                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside')?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->

