<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
    <?=$this->headTitle()?>
	<!--[if lt IE 9]>
	<meta http-equiv="PRAGMA" content="NO-CACHE" />
    <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
    <![endif]-->

<!--[if IE 6]>
	<link href="css/ie6.css" type="text/css" rel="stylesheet" />

    <script src="js/dd_belated_png.js"></script>
	<script>DD_belatedPNG.fix('#logo a, .h-box-1 img, .h-box-2 img, .brochure img, .slide-txt');</script>  
<![endif]-->
    <?=$this->headMeta()?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="<?=$this->link('/src/aier/css/index.css')?>" media="all" rel="stylesheet" type="text/css" />
    <script src="<?=$this->link('/lib/js/labjs/labjs.min.js')?>"></script>
    <script src="<?=$this->link('/lib/js/jquery/jquery.min.js')?>"></script>
    <script src="<?=$this->link('/src/aier/js/jqueryslidemenu.js')?>"></script>
    <script src="<?=$this->link('/src/aier/js/slideswitch.js')?>"></script>
    <script src="<?=$this->link('/src/aier/js/slimbox2.js')?>"></script>

</head>
<body>
<div id="body-wrapper">
    <div class="clearfix">
        <div id="logo">
            <a href="homepage.html">Media consult logo</a>
            <p class="logo-desc">your attractive and simple slogan</p>
        </div>
        <form action="#" method="post">
            <fieldset class="search-fieldset">
                <input type="text" class="search-input" value="search" name="search" />
                <input type="submit" value="" class="input-arrow" />
            </fieldset>
        </form>
    </div>	
    
    <div class="main-menu-wrapper">
        <div id="myslidemenu" class="jqueryslidemenu">
            <ul class="primary-menu">
                <li><a href="homepage.html">Home</a></li>
                <li><a href="about_us.html">About Us</a></li>
                <li><a href="services.html">Services</a>
                	<ul>
                        <li><a href="#">Corporate Publishing</a></li>
                        <li><a href="#">Interactive &amp; Onscreen Production</a></li>	
                        <li><a href="#">Advertising</a></li>   
                        <li><a href="#">Event Management</a></li>   
                        <li><a href="#">Integrated Communications</a></li>                                                                    
                        <li><a href="#">Public Relations</a></li>                                                  
                    </ul>
                </li>
                <li><a href="#">Page Types</a>
                    <ul>
                        <li><a href="homepage.html">Index Page</a></li>
                        <li><a href="about_us.html">About Us</a></li>	
                        <li><a href="portfolio.html">Portfolio</a></li>
                        <li><a href="#">Blog - submenu entry</a>
                            <ul>
                                <li><a href="blog_itemlist.html">Blog Item List</a></li>
                                <li><a href="blog_detail.html">Blog Item Detail</a></li>
                            </ul>                
                        </li>
                        <li><a href="#">Other pages - submenu entry</a>
                            <ul>
                                <li><a href="article_detail.html">Article Detail</a></li>                    
                                <li><a href="news_list.html">News Page</a></li>                                                
                                <li><a href="services.html">Our Services</a></li>                                                                        
                                <li><a href="portfolio.html">Portfolio</a></li>                                                          
                                <li><a href="contact.php">Contact</a></li>   
                            </ul>                          
                        </li>                                         
                    </ul>
                </li>
                <li><a href="blog_itemlist.html">Blog</a></li>
                <li><a href="contact.php">Contact</a></li>
            </ul>
        </div>
    </div>
    <!-- START homepage slideshow -->
    <div id="slideshow-wrapper">
        <ul id="slideshow">
            <li class="active"><!-- slide 1 -->
                <a href="#"><img src="img/slide_img1.jpg" width="641" height="281" alt="" class="slide-1-img" /></a>
                <div class="slide-1-desc">
                	<h1>Let them know.<br /> We make a difference.</h1>
                    <p>
                    	Enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. 
                    </p>
                    <p>
						Quisque volutpat condimerum velit. Eos no sale dolore vituperatoribus, eam id exerci sanctus albucius. No est corpora delectus delicata, integre facilis deseruisse an per, natum commodo viderer nec ea.                    
                    </p>
                    <div class="slideshow-rm"><a href="#">learn more</a></div>
                </div>
            </li>
            
            <li><!-- slide 2 -->
                <a href="#"><img src="img/slide_img2.jpg" width="960" height="281" alt="" /></a>
            </li>
            
            <li><!-- slide 3 -->
            	<div class="slide-txt">
                	<h3><a href="#">Learn how to protect your investments - a step by step guide</a></h3>
                
                </div>
                <a href="#"><img src="img/slide_img3.jpg" width="960" height="281" alt="" /></a>            	
            </li>
        </ul>
	</div>
    <!-- END homepage slideshow -->
    <div id="left">
    	<div class="clearfix">
    		<h2>Welcome to our company</h2>
			<p class="header-desc">We bring value, innovation and growth to your business</p>
        </div>
		<p>
        	Ut dico exerci cum. Ipsum movet dolore sit ea, pri ea dicant mediocrem aliquando. Stet maiestatis ut pri, et vim melius legimus alienum. Nam nibh ipsum ad, pri dictas ornatus consequat te. Vel quem vidit posidonium in, brute dicunt maiorum vis te, mei veniam sanctus imperdiet ad.
        </p>  
        <p>
Ad officiis percipitur theophrastus quo, ubique impedit ancillae per eu, pri natum tritani copiosae in. Civibus molestie deseruisse mea an, sumo omittam adolescens has te. Atqui luptatum pro ei, his eu regione sensibus necessitatibus. Ne feugait consetetur temporibus nec, inani audiam interpretaris cu vis, qui aeque zzril dissentiunt ea. Ut lorem choro aliquid vix, dolor partem bonorum duo in. Enim cetero luptatum usu ne, soluta invidunt signiferumque id ius, eos eius idque audiam eu.        
        </p>      
        
		<div class="h-box-1"><!-- services overview box-->
        	<img src="img/services_icon.png" width="54" height="54" alt="" class="h-box-img" />
            <div class="h-box-title">
                <h3>Services overview</h3>
                <p class="header-desc">Our services at a glance</p>
            </div>
            <div class="h-box-wrap">
                <p>Phasellus ipsum nulla, dignissim condimentum mattis sit amet, feugiat a nulla.</p>
                <ul class="h-services-list">
                    <li><a href="#">Corporate Publishing</a></li>
                    <li><a href="#">Interactive &amp; Onscreen Production</a></li>
                    <li><a href="#">Advertising</a></li>
                    <li><a href="#">Event Management</a></li>
                    <li><a href="#">Integrated Communications</a></li>                                
                    <li><a href="#">Public Relations</a></li>
                </ul>
            </div>
        </div>
        
		<div class="h-box-2"><!-- featured case study overview -->
            <img src="img/case_study_icon.png" width="54" height="54" alt="" class="h-box-img" />
            <div class="h-box-title">
                <h3>Services overview</h3>
                <p class="header-desc">Investments and advertising campaigns</p>
            </div>
            <div class="h-box-wrap">
                <p>
                    Phasellus ipsum nulla, dignissim condimentum mattis sit amet, feugiat a nulla. Nulla molestie pellentesque lorem, eu lacinia sem pellentesque ut. Aenean tempor ligula ut massa feugiat quis lacinia sem sollicitudin.
                </p>
                <p>
                    Fusce mattis blandit libero a imperdiet. Sed lorem quam, imperdiet eu congue eget, pretium eget justo. 
                </p>
                <div class="body-rm"><a href="#">read more</a></div>
			</div>
        </div>
                
    </div>
    <div id="right">
    	<div class="latest-news"><!-- latest news section -->
        	<h3>Latest news</h3>
            <ul class="ln-list">
                <li>
                    <h6><a href="#">Our company organises workshop for ...</a></h6>
                    <p>Supendisse sit amet est odio. Suspendisse semper, tur pi eget feugiat venenatis, diam turpis euismod, nisl...</p>
					<div class="ln-date">September 4th, 2009</div>
                </li>
                <li>
                    <h6><a href="#">Our company organises workshop for ...</a></h6>
                    <p>Supendisse sit amet est odio. Suspendisse semper, tur pi eget feugiat venenatis, diam turpis euismod, nisl...</p>
					<div class="ln-date">September 4th, 2009</div>                    
                </li>
                <li>
                    <h6><a href="#">Our company organises workshop for ...</a></h6>
                    <p>Supendisse sit amet est odio. Suspendisse semper, tur pi eget feugiat venenatis, diam turpis euismod, nisl...</p>
					<div class="ln-date">September 4th, 2009</div>                    
                </li>                                         
            </ul>            
        </div>
        
        <div class="newsletter"><!-- newsletter section -->
			<h3>Sign up for Newsletter</h3>
            <form action="#" method="post">
            	<fieldset class="newsletter-fieldset">
                    <input type="text" class="newsletter-input" value="Your email address" name="newsletter" />
                    <input type="submit" value="" class="input-arrow" />
                </fieldset>
            </form>
            <p>We will keep you up to date with news, events and other great features.</p>
        </div>
    	
        <div class="brochure"><!-- brochure section -->
        	<a href="#"><img src="img/pdf_icon.png" width="43" height="53" alt="" /></a>
            <div class="brochure-title">
                <h3>Media Consult brochure</h3>
                <p class="header-desc">Download our PDF brochure</p>
            </div>            
        </div>
    </div>  
    <div id="footer">
    	<ul>
        	<li><a href="homepage.html">Home</a></li>
        	<li><a href="about_us.html">About Us</a></li>
        	<li><a href="services.html">Services</a></li>
        	<li><a href="portfolio.html">Case Studies</a></li>
        	<li><a href="news_list.html">News</a></li>
        	<li><a href="contact.php">Contact</a></li>                                                            
        </ul>
        <div class="copyright">&copy; 2009 <a href="#">Media Consult</a>. All rights reserved.</div>
    </div>  
</div>

<script type="text/javascript">
$(document).ready(function(){					   
	$(".ln-list li").click(function(){//makes entire area "ln-list li" clickable
    	window.location=$(this).find("a").attr("href");return false;
	});
	
	$(".brochure").click(function(){//makes entire area "brochure" clickable
    	window.location=$(this).find("a").attr("href");return false;
	});	

});
</script>
</body>
</html>

