<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
    <?=$this->headTitle()?>
	<!--[if lt IE 9]>
	<meta http-equiv="PRAGMA" content="NO-CACHE" />
    <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
    <![endif]-->

<!--[if IE 6]>
	<link href="css/ie6.css" type="text/css" rel="stylesheet" />

    <script src="js/dd_belated_png.js"></script>
	<script>DD_belatedPNG.fix('#logo a, .h-box-1 img, .h-box-2 img, .brochure img, .slide-txt');</script>  
<![endif]-->
    <?=$this->headMeta()?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="<?=$this->link('/src/aier/css/index.css')?>" media="all" rel="stylesheet" type="text/css" />
    <script src="<?=$this->link('/lib/js/labjs/labjs.min.js')?>"></script>
    <script src="<?=$this->link('/lib/js/jquery/jquery.min.js')?>"></script>
    <script src="<?=$this->link('/src/aier/js/jqueryslidemenu.js')?>"></script>
    <script src="<?=$this->link('/src/aier/js/slideswitch.js')?>"></script>
    <style>
        body {
            font-size:12px;
        }
        body, h1, h2, h3, h4, h5, h6 , .jqueryslidemenu  {
                font-family:Microsoft YaHei,Trebuchet MS, Verdana, Helvetica, Arial, sans-serif;
        }
        .jqueryslidemenu ul li a {
                padding-bottom:8px;
        }
        .main-menu-wrapper{
            margin-top:-40px;
        }
        .search-fieldset {
            text-align:right;
            margin:0;
        }
    </style>

</head>
<body>
<div id="body-wrapper">
    <div class="clearfix">
        <div id="logo">
            <a href="<?=$this->uri('/')?>"><img src="<?=$this->link('/src/aier/images/logo.png')?>" alt=""/></a>
        </div>
        <form action="#" method="post">
            <fieldset class="search-fieldset">
                <?=$this->widget('Aier', 'components/phone')?>
            </fieldset>
        </form>
    </div>	
    
    <div class="main-menu-wrapper">
        <div id="myslidemenu" class="jqueryslidemenu">
            <ul class="primary-menu">
                <li><a href="<?=$this->uri('/')?>">首页</a></li>
                <li><a href="<?=$this->uri('/pages/about')?>">企业简介</a></li>
                <li><a href="<?=$this->uri('/category/culture')?>">企业文化</a></li>
                <li><a href="<?=$this->uri('/category/news')?>">新闻动态</a></li>
                <li><a href="<?=$this->uri('/category/science')?>">学术前沿</a></li>
                <li><a href="<?=$this->uri('/category/bidding')?>">招标信息</a>
                </li>
                <li><a href="<?=$this->uri('/category/projects')?>">推介项目</a></li>
                <li><a href="<?=$this->uri('/order/')?>">联系我们</a></li>
            </ul>
        </div>
    </div>

    <?=$this->content?>
    <div id="footer">
        <ul>
            <li><a href="<?=$this->uri('/')?>">首页</a></li>
            <li><a href="<?=$this->uri('/pages/contact')?>">联系方式</a></li>
            <li><a href="<?=$this->uri('/order/')?>">留言反馈</a></li>                                                         
        </ul>
        <div class="copyright">&copy; 2012 <a href="#">甘肃金爱尔商贸有限公司</a>. All rights reserved.</div>
    </div>  
</div>

<script type="text/javascript">
    $(document).ready(function(){					   
            $(".ln-list li").click(function(){//makes entire area "ln-list li" clickable
                window.location=$(this).find("a").attr("href");return false;
        });

        $(".brochure").click(function(){//makes entire area "brochure" clickable
            window.location=$(this).find("a").attr("href");return false;
    });	

});
</script>
</body>
</html>

