<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
    <?=$this->headTitle()?>
	<!--[if lt IE 9]>
	<meta http-equiv="PRAGMA" content="NO-CACHE" />
    <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
    <![endif]-->

<!--[if IE 6]>
	<link href="css/ie6.css" type="text/css" rel="stylesheet" />

    <script src="js/dd_belated_png.js"></script>
	<script>DD_belatedPNG.fix('#logo a, .h-box-1 img, .h-box-2 img, .brochure img, .slide-txt');</script>  
<![endif]-->
    <?=$this->headMeta()?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="<?=$this->link('/src/aier/css/index.css')?>" media="all" rel="stylesheet" type="text/css" />
    <script src="<?=$this->link('/lib/js/labjs/labjs.min.js')?>"></script>
    <script src="<?=$this->link('/lib/js/jquery/jquery.min.js')?>"></script>
    <script src="<?=$this->link('/src/aier/js/jqueryslidemenu.js')?>"></script>
    <script src="<?=$this->link('/src/aier/js/slideswitch.js')?>"></script>
    <script src="<?=$this->link('/src/aier/js/slimbox2.js')?>"></script>

</head>
<body>
<div id="body-wrapper">
    <div class="clearfix">
        <div id="logo">
            <a href="homepage.html">Media consult logo</a>
            <p class="logo-desc">your attractive and simple slogan</p>
        </div>
        <form action="#" method="post">
            <fieldset class="search-fieldset">
                <input type="text" class="search-input" value="search" name="search" />
                <input type="submit" value="" class="input-arrow" />
            </fieldset>
        </form>
    </div>	
    
    <div class="main-menu-wrapper">
        <div id="myslidemenu" class="jqueryslidemenu">
            <ul class="primary-menu">
                <li><a href="homepage.html">Home</a></li>
                <li><a href="about_us.html">About Us</a></li>
                <li><a href="services.html">Services</a>
                	<ul>
                        <li><a href="#">Corporate Publishing</a></li>
                        <li><a href="#">Interactive &amp; Onscreen Production</a></li>	
                        <li><a href="#">Advertising</a></li>   
                        <li><a href="#">Event Management</a></li>   
                        <li><a href="#">Integrated Communications</a></li>                                                                    
                        <li><a href="#">Public Relations</a></li>                                                  
                    </ul>
                </li>
                <li><a href="#">Page Types</a>
                    <ul>
                        <li><a href="homepage.html">Index Page</a></li>
                        <li><a href="about_us.html">About Us</a></li>	
                        <li><a href="portfolio.html">Portfolio</a></li>
                        <li><a href="#">Blog - submenu entry</a>
                            <ul>
                                <li><a href="blog_itemlist.html">Blog Item List</a></li>
                                <li><a href="blog_detail.html">Blog Item Detail</a></li>
                            </ul>                
                        </li>
                        <li><a href="#">Other pages - submenu entry</a>
                            <ul>
                                <li><a href="article_detail.html">Article Detail</a></li>                    
                                <li><a href="news_list.html">News Page</a></li>                                                
                                <li><a href="services.html">Our Services</a></li>                                                                        
                                <li><a href="portfolio.html">Portfolio</a></li>                                                          
                                <li><a href="contact.php">Contact</a></li>   
                            </ul>                          
                        </li>                                         
                    </ul>
                </li>
                <li><a href="blog_itemlist.html">Blog</a></li>
                <li><a href="contact.php">Contact</a></li>
            </ul>
        </div>
    </div>

    <?=$this->content?>
    <div id="footer">
    	<ul>
        	<li><a href="homepage.html">Home</a></li>
        	<li><a href="about_us.html">About Us</a></li>
        	<li><a href="services.html">Services</a></li>
        	<li><a href="portfolio.html">Case Studies</a></li>
        	<li><a href="news_list.html">News</a></li>
        	<li><a href="contact.php">Contact</a></li>                                                            
        </ul>
        <div class="copyright">&copy; 2009 <a href="#">Media Consult</a>. All rights reserved.</div>
    </div>  
</div>

<script type="text/javascript">
$(document).ready(function(){					   
	$(".ln-list li").click(function(){//makes entire area "ln-list li" clickable
    	window.location=$(this).find("a").attr("href");return false;
	});
	
	$(".brochure").click(function(){//makes entire area "brochure" clickable
    	window.location=$(this).find("a").attr("href");return false;
	});	

});
</script>
</body>
</html>

