<?
$this->headTitle('Epicurissimo compass | communauté privé pour les pros et les connaisseur du gastronomie et vin', 'SET');

?>
<div class="bg bg-0">
    <div class="container">
        <div id="bg-0" class="guide"></div>

        <div class="loginblock block-text-1">
            <div class="typo">
                <a href="#">About Us: Epicurissimo is a private network and online publication, a trusted place for professionals and connoisseurs of gastronomy and fine drinks to meet, connect, stay informed, showcase their work, find experts, share ideas, ask questions, find jobs and make business.</a>
            </div>
        </div>
    </div>
</div>

<div class="bg bg-1">
    <div class="container">
        <div id="bg-1" class="guide"></div>
        <div class="loginblock block-1 hide">
        </div>
        <div class="loginblock block-2 hide">
        </div>
        <div class="loginblock block-text-2">
            <div class="typo">
                <a href="#">Food: Whenever you eliminate the inedible， whatever remains， however unpalatable， must be food.</a>
            </div>
        </div>
    </div>
</div>

<div class="bg bg-2">
    <div class="container">
        <div id="bg-2" class="guide"></div>
        <div class="loginblock block-3 hide">
        </div>
        <div class="loginblock block-4 hide">
        </div>
        <div class="loginblock block-text-3">
            <div class="typo">
                <a href="#">Wine: Learn about the types of wine here. What kind of grapes make all the wine types? What are their differences and is there a best wine?</a>
            </div>
        </div>
    </div>
</div>

<div class="bg bg-3">
    <div class="container">
        <div id="bg-3" class="guide"></div>
    </div>
        <div class="loginblock block-text-4">
            <div class="typo">
                <a href="#">Party: life without a friend is a life without a sun. <br >Be slow in choosing a friend; slower in changing.</a>
            </div>
        </div>
</div>

<div class="bg bg-4">
    <div class="container">
        <div id="bg-4" class="guide"></div>
    </div>
        <div class="loginblock block-text-4">
            <div class="typo">
                <a href="#">Party: life without a friend is a life without a sun. <br >Be slow in choosing a friend; slower in changing.</a>
            </div>
        </div>
</div>

<div class="bg bg-5">
    <div class="container">
        <div id="bg-5" class="guide"></div>
    </div>
        <div class="loginblock block-text-4">
            <div class="typo">
                <a href="#">Party: life without a friend is a life without a sun. <br >Be slow in choosing a friend; slower in changing.</a>
            </div>
        </div>
</div>
