<?
$this->headTitle('Epicurissimo compass | communauté privé pour les pros et les connaisseur du gastronomie et vin', 'SET');
$user = $this->user;
$items = $this->items;
$viewAsGuest = $this->viewAsGuest;
$form = new Activity\Form\MessageCreateForm();
$form->useSubFormGroup()
     ->setMethod('post')
     ->setView($this)
     ->setAction($this->uri('/activity/'))
     ->prepare();
?>

<div class="page-inner">
    <div class="container">
        <div class="profile-cover">
            <ul class="nav profile-nav">
                <li class="" data-highlight-url="^/home/?"><a href="<?=$this->uri('/home/')?>"><?=$this->_('Home')?></a></li>
                <li class="" data-highlight-url="^/user/\w+/?"><a href="<?=$this->uri('/user/' . $user['userName'])?>"><?=$this->_('Profile')?></a></li>
                <li class="" data-highlight-url="^/user/\w+/blog/?"><a href="<?=$this->uri('/user/' . $user['userName'] . '/blog/')?>"><?=$this->_('Blog')?></a></li>
                <li class="" data-highlight-url="^/user/\w+/album/?"><a href="<?=$this->uri('/user/' . $user['userName'] . '/album/')?>"><?=$this->_('Album')?></a></li>
                <li class="" data-highlight-url="^/user/\w+/event/?"><a href="<?=$this->uri('/user/' . $user['userName'] . '/event/')?>"><?=$this->_('Event')?></a></li>
                <li class="" data-highlight-url="^/user/\w+/group/?"><a href="<?=$this->uri('/user/' . $user['userName'] . '/group/')?>"><?=$this->_('Group')?></a></li>
            </ul>
            <p class="profile-url"><a href="<?=$this->serverUrl() . '/user/' . $user['userName']?>"><?=$this->serverUrl() . '/user/' . $user['userName']?></a></p>
        </div>
    </div><!-- above container end -->
    <div class="container">
        <div class="profile-main">
            <div class="row">
                <div class="span8">
                    <div class="thumbnail profile-face">
                        <img alt="userface" src="<?=$this->gravatar($user['email'], 175)?>" width="175" height="175">
                        <div class="caption">
                            <a class="highlight highlight-large" href="#">123</a> Friends
                        </div>
                    </div>
                    <div class="profile-intro">
                        <div class="profile-title">
                            <h2><?=$user['userName']?></h2>
                            <small class="profile-level">Professional  <a href="#" title="VIP User"><i class="icon-trophy"></i></a></small>
                        </div>

                        <table class="table-condensed">
                            <tbody>
                                <tr>
                                    <td>Title: Miss</td>
                                    <td colspan="2">Profession : Food Critic</td>
                                </tr>
                                <tr>
                                    <td>Location : Lanzhou, China</td>
                                    <td>Birthday : 1980-10-01</td>
                                    <td>Events : <a href="">3</a> Times</td>
                                </tr>
                                <tr>
                                    <td colspan="3">Tags : 
                                        <a href="#">Wine</a>
                                        <a href="#">Wine</a>
                                        <a href="#">Wine</a>
                                        <a href="#">Wine</a>
                                        <a href="#">Wine</a>
                                        <a href="#">Wine</a>
                                        <a href="#">Wine</a>
                                        <a href="#">Wine</a>
                                        <a href="#">Wine</a>
                                        <a href="#">Wine</a></td>
                                </tr>
                                <tr>
                                    <td colspan="2">
                                        <a class="btn btn-brown btn-mini" href="#"><i class="icon-mini icon-plus"></i> Add Friend</a>
                                        <a class="btn btn-gray btn-mini" href="#"><i class="icon-mini icon-envelope-alt"></i> Send Message</a>
                                    </td>
                                    <td class="social">
                                        Social Networking : 
                                        <a href="#"><i class="icon-facebook-sign"></i></a>
                                        <a href="#"><i class="icon-pinterest"></i></a>
                                        <a href="#"><i class="icon-twitter"></i></a>
                                        <a href="#"><i class="icon-google-plus"></i></a>
                                    </td>
                                </tr>
                            </tbody>
                        </table>
                    </div><!--profile-intro end-->

                    <div class="profile-activities">

                        <?if(!$viewAsGuest):?>
                        <div class="row">
                            <form id="activity-form" <?=$this->formAttr($form)?> class="activity-box span7">
                                <?=$form->helper('messageType', 'formHidden', array('class' => ''))?>        
                                <?=$form->helper('reference_id', array('class' => ''))?>
                                <?=$form->helper(array('MessageFile', 'file_id'), 'formHidden', array('class' => ''))?>
                                <input name="callback" type="hidden" value="<?=$this->uri('/home/')?>" />
                                <div class="page-header">
                                    <h3>Say something...</h3>
                                </div>
                                <fieldset class="form">
                                    <div class="activity-box-wrap">
                                        <div class="activity-box-content">
                                            <?=$form->helper('content', 'formTextarea', array('class' => '', 'rows' => 5))?>        
                                        </div>
                                        <div class="activity-box-buttons">
                                            <a id="activity-box-image-button" class="activity-box-func activity-box-text" href="javascript:;" data-activity-text="Share Photo."><i class="icon-mini icon-picture"></i> Photo</a>
                                            <a id="activity-box-video-button" class="activity-box-func" href="#"><i class="icon-mini icon-facetime-video"></i> Video</a>
                                            There are <span class="highlight highlight-large activity-box-count">140</span> letters left <button type="submit" class="btn btn-light-brown btn-large">Submit</button>
                                        </div>
                                    </div>
                                </fieldset>
                            </form>
                        </div>
                        <?endif?>

                        <div class="page-header border-header">
                            <h3>New Activities</h3>
                        </div>

                        <div class="activity-list vlist">
                            <?foreach($items as $item):?>
                            <div class="item">
                                <a href="<?=$this->uri('/user/' . $item['user_id'])?>" title="" class="item-absolute item-userface"><img src="<?=$this->gravatar($item['User']['email'])?>" alt="" class="img-rounded" width="60" height="60" /></a>
                                <div class="item-inline item-text span6">
                                    <div class="item-content">
                                        <div class="item-title"><a href="<?=$this->uri('/user/' . $item['user_id'])?>" class="item-user"><?=$item['User']['userName']?></a> Said:</div>
                                        <p><?=$item['ContentHtml']?></p>
                                        <?if($item['File']):?>
                                        <div class="item-image">
                                            <p><a href="<?=$item['File'][0]['Thumb']?>"><img src="<?=$this->thumb($item['File'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                                        </div>
                                        <?endif?>

                                        <?if(isset($item['ForwardActivity']) && $item['ForwardActivity']): $subItem = $item['ForwardActivity'];?>
                                        <div class="well">
                                            <p><?=$subItem['ContentHtml']?></p>
                                            <?if($subItem['File']):?>
                                            <div class="item-image">
                                                <p><a href="<?=$subItem['File'][0]['Thumb']?>"><img src="<?=$this->thumb($subItem['File'][0]['Thumb'], array('w_200'))?>" alt="" class="img-polaroid" /></a></p>
                                            </div>
                                            <?endif?>
                                            <div class="item-action">
                                                <p class="pull-right"><a href="<?=$this->uri('/feed/' . $subItem['messageHash'])?>" class="" data-activity-comment="<?=$subItem['id']?>"><i class="icon-comment"></i> Comments (<span class="highlight"><?=$subItem['commentedCount']?></span>)</a></p>
                                                <p class="pull-left">
                                                <a href="<?=$this->uri('/feed/' . $subItem['messageHash'])?>"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($subItem['createTime'])?>" datetime="<?=$this->datetime()->isoTime($subItem['createTime'])?>"><?=$this->datetime($subItem['createTime'])?></time></a>
                                                </p>
                                            </div>
                                        </div>
                                        <?endif?>

                                        <div class="item-action">
                                            <p class="pull-right"><a href="javascript:;" class="item-func comment" data-activity-comment="<?=$item['id']?>"><i class="icon-comment"></i> Comments (<span class="highlight"><?=$item['commentedCount']?></span>)</a></p>
                                            <p class="pull-right hide"><a href="#activity-form" class="item-func reference" data-activity-reference="<?=$item['id']?>" data-activity-text="@<?=$item['User']['userName']?> "><i class="icon-share-alt"></i> RT (<span class="highlight"><?=$item['transferredCount']?></span>)</a></p>
                                            <p class="pull-left">
                                            <a href="<?=$this->uri('/feed/' . $item['messageHash'])?>" class="item-id"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['createTime'])?>" datetime="<?=$this->datetime()->isoTime($item['createTime'])?>"><?=$this->datetime($item['createTime'])?></time></a>
                                            </p>
                                        </div>
                                    </div>

                                    <div class="item-sub-ajax">
                                    </div>
                                </div>
                            </div>
                            <?endforeach?>
                        </div><!--activity-list end-->


                    </div><!--profile-activities end-->
                </div><!--left span8 end-->
                <div class="span4">
                    <div class="profile-side">
                        <div class="calendar calendar-mini">
                            <div class="calendar-wrap">

                            </div>
                            <div class="calendar-caption">
                                <i class="icon-stop green"></i> Coming Event
                                <i class="icon-stop orange"></i> Today
                            </div>
                        </div><!--calendar end-->

                        <div class="subscription">
                            <button class="btn"><i class="icon-mini icon-envelope-alt"></i> Subscription Epicurissimo Newsletters</button>
                        </div>


                        <div class="page-header border-header">
                            <small class="pull-right"><a href="#">View All</a></small>
                            <h4>My Friends (123)</h4>
                        </div>
                        <div class="side-user-list">
                            <ul class="thumbnails">
                                <?for($i = 0; $i < 16; $i++):?>
                                <li>
                                <a class="thumbnail" href="#">
                                    <img src="<?=$this->link('/src/epic/css/img/face-04.jpg')?>" alt="" class="img-rounded" width="30" height="30" />
                                </a>
                                </li>
                                <?endfor;?>
                            </ul>
                        </div>

                        <div class="page-header border-header">
                            <small class="pull-right"><a href="#">View All</a></small>
                            <h4>My Blog (123)</h4>
                        </div>
                        <div class="side-blog-list">
                            <?for($i = 0; $i < 10; $i++):?>
                            <div class="item ">
                                <a href="" title="" class="item-absolute imgdelay figure userface"><img src="<?=$this->link('/src/epic/css/img/face-01.jpg')?>" alt="" class="img-rounded" width="50" height="50" /></a>
                                <div class="item-inline item-text">
                                    <div class="text-content">
                                        <div class="item-title">
                                            <a href="#">Blog title test
                                                Blog title test</a>
                                        </div>
                                        <p>Post content test</p>
                                    </div>
                                </div>
                            </div>
                            <?endfor?>
                        </div><!--activity-list end-->
                        <div class="page-header border-header">
                            <small class="pull-right"><a href="#">View All</a></small>
                            <h4>My Events (123)</h4>
                        </div>
                        <div class="side-blog-list">
                            <?for($i = 0; $i < 10; $i++):?>
                            <div class="item ">
                                <a href="" title="" class="item-absolute imgdelay figure userface"><img src="<?=$this->link('/src/epic/css/img/face-01.jpg')?>" alt="" class="img-rounded" width="50" height="50" /></a>
                                <div class="item-inline item-text">
                                    <div class="text-content">
                                        <div class="item-title">
                                            <a href="#">Event title test</a>
                                        </div>
                                        <p>Event Members: 50</p>
                                        <p>Event Time: <?=$this->datetime(time())?></p>
                                    </div>
                                </div>
                            </div>
                            <?endfor?>
                        </div><!--activity-list end-->

                        <div class="page-header border-header">
                            <small class="pull-right"><a href="#">View All</a></small>
                            <h4>Albums</h4>
                        </div>
                        <div class="side-album-list">
                            <ul class="thumbnails">
                                <?for($i = 0; $i < 8; $i++):?>
                                <li>
                                <a class="thumbnail" href="#">
                                    <img src="<?=$this->link('/src/epic/css/img/food.jpg')?>" alt="" class="img-rounded" width="70" height="70" />
                                </a>
                                </li>
                                <?endfor;?>
                            </ul>
                        </div>

                        <div class="page-header border-header">
                            <small class="pull-right"><a href="#">View All</a></small>
                            <h4>My Groups</h4>
                        </div>
                        <div class="side-group-list">
                            <ul class="thumbnails">
                                <?for($i = 0; $i < 5; $i++):?>
                                <li>
                                <a class="thumbnail" href="#">
                                    <img src="<?=$this->link('/src/epic/css/img/group.jpg')?>" alt="" class="img-rounded" width="50" height="50" />
                                </a>
                                </li>
                                <?endfor;?>
                            </ul>
                        </div>

                        <div class="side-ad-list">
                            <a href="#" class="pull-right"><img src="<?=$this->link('/src/epic/css/img/ad-2.jpg')?>" alt=""></a>
                            <a href="#" class="pull-left"><img src="<?=$this->link('/src/epic/css/img/ad-1.jpg')?>" alt=""></a>
                        </div>

                    </div><!--profile-side end-->
                </div><!--right span4 end-->
            </div><!--row end-->
        </div><!--profil-main end-->
    </div><!--container end-->
</div><!--page inner end-->

<?=$this->widget('File', 'file/index')?>

<script>
    var calendarUrl = eva.d('/event/calendar/');
    $('.calendar-wrap').load(calendarUrl);
    $('.calendar-wrap thead a').live("click", function(){
            $('.calendar-wrap').load($(this).attr('href'));
            return false;
    });

    var modal = $("#fileupload-modal");
    modal.hide();
    eva.loader(eva.s('/static/eva/js/eva.jquery.evaTip.js'), function(){
            modal.hide();
            $('#activity-box-image-button').on('click', function() {
                    $(this).evaTip("show", {
                            'tip' : modal,
                            'offsetX' : -75,
                            'offsetY' : 30,
                            'direction' : 'bottom'			
                    });
                    return false;
            });

            modal.find(".close").on("click", function(){
                    modal.hide();
            });
    });

    var modal = $("#fileupload-modal");
    modal.hide();
    eva.loader(eva.s('/static/eva/js/eva.jquery.evaTip.js'), function(){
            modal.hide();
            $('#activity-box-image-button').on('click', function() {
                    $(this).evaTip("show", {
                            'tip' : modal,
                            'offsetX' : -75,
                            'offsetY' : 30,
                            'direction' : 'bottom'			
                    });
                    return false;
            });

            modal.find(".close").on("click", function(){
                    modal.hide();
            });
    });

    var uploader = $('#singlefileupload');
    var form = $("#activity-form");
    var textarea = form.find('textarea');
    uploader.bind('fileuploaddone', function (e, data) {
            var file = data.result[0];
            form.find('input[name="MessageFile[file_id]"]').val(file.id);
            modal.find(".close").hide();
    });

    $(".activity-box-text").live('click', function(){
            textarea.val(textarea.val() + $(this).attr('data-activity-text'));
            return false;
    });

    $(".item-func.reference").live('click', function(){
            textarea.val(textarea.val() + $(this).attr('data-activity-text'));
            form.find('input[name="reference_id"]').val($(this).attr('data-activity-reference'));
            form.find('input[name="messageType"]').val('forward');
    });

    $(".item-func.comment").live('click', function(){
            var item = $(this).parentsUntil('.item').parent();
            var idUrl = item.find('.item-id').attr('href');
            item.find('.item-sub-ajax').load(idUrl + ' .item-sub-wrap', function(){
                    $(this).show();
            });
    });

    var maxMessage = 140;
    var countHandler = $('.activity-box-count');
    var messageLetterCount = function(){
            countHandler.html(maxMessage - textarea.val().length);
        }

        textarea.live('keyup', function(){
                messageLetterCount();
        });
    </script>

