<?
$this->headTitle($this->category['categoryName'], 'SET');
?>


<div id="left">
    <div class="interior-header">
        <h2><a href="<?=$this->uri('/category/' . $this->category['urlName'])?>"><?=$this->category['categoryName']?></a></h2>
        <p class="intheader-paragraph">
        <?=$this->category['description']?>
        </p>
    </div>
    <div class="interior-content">

        <?if($this->posts):?>

        <ul class="newslist-wrapper">
            <?foreach($this->posts as $key => $post):?>
            <li>
            <a href="<?=$this->uri('/pages/' . $post['urlName'])?>"><img src="<?=$this->link('/src/aier/images/post.png')?>" width="72" height="72" alt="" class="news-img" /></a>
            <h4><a href="<?=$this->uri('/pages/' . $post['urlName'])?>"><?=$post['title']?></a></h4>
            <span class="newslist-date">发布时间： <?=$post['createTime']?></span>
            <p><?=$post['preview']?>
            </p>                	
            </li>
            <?endforeach;?>
        </ul>
        <?else:?>
        <?endif;?>

        <?if($this->paginator):?>
        <?=$this->paginator->setPath('/category/' . $this->category['urlName'])->setBaseQuery($this->query);?>
        <?$paginator = $this->paginator;
        if($paginator){
            $path = $paginator->getPath();
            $queryKey = $paginator->getPageQueryKey();
            $baseQuery = $paginator->getBaseQuery();
            $paginator = $paginator->toArray();
        }?>
        <div class="pagination"><!-- generic pagination, copy/paste this block wherever you like -->
            <?if($paginator['prevPage']):?>
            <div class="reverse-arrow"><a href="<?=$this->uri($path, 'dq', array('Q' => $baseQuery, 'q' => array($queryKey => $paginator['prevPage'])))?>">上页</a></div>
            <?endif?>
            <?if($paginator['nextPage']):?>
            <div class="body-rm"><a href="<?=$this->uri($path, 'dq', array('Q' => $baseQuery, 'q' => array($queryKey => $paginator['nextPage'])))?>">下页</a></div>   
            <?endif?>
            <span class="page-number">当前在： <?=$paginator['pageNumber']?> / <?=$paginator['pageCount']?>页</span>             
        </div>  
        <li></li>
        <?endif;?>



    </div>

</div>
<div id="right">
    <?=$this->widget('Aier', 'widgets/side', $this->vars())?>
</div>  
