<!DOCTYPE html>
<!-- Variation 1 -->
<!--[if (gte IE 9)|!(IE)]><!--><html lang="en"> <!--<![endif]-->
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta charset="utf-8" />
        <?=$this->headTitle()?>
        <!--[if lt IE 9]>
        <meta http-equiv="PRAGMA" content="NO-CACHE" />
        <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
        <link rel="stylesheet" href="assets/css/ie.css" />
        <![endif]-->
        <?=$this->headMeta()?>

        <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
        <script type="text/javascript" src="<?=$this->link('/src/epic/js/placeholder.js')?>"></script>  
        <script type="text/javascript" src="<?=$this->link('/src/epic/js/supersized.3.2.7.min.js')?>"></script>
        <script type="text/javascript" src="<?=$this->link('/src/epic/js/form.js')?>"></script>
        <script type="text/javascript" src="<?=$this->link('/src/epic/js/subscribe.js')?>"></script>

        <link href='http://fonts.googleapis.com/css?family=Philosopher' rel='stylesheet' type='text/css'>
        <link href="<?=$this->link('/src/epic/css/coming.css')?>" media="all" rel="stylesheet" type="text/css" />
        <?=$this->evajs()?>

        <script type="text/javascript">
            jQuery(function($){
                    jQuery.supersized({
                            slides:
                            [	
                            {image:'<?=$this->link('/src/epic/img/bg.jpg')?>'}
                            ]
                    });
            });
        </script>

        <script type="text/javascript">
            //Animate Pull Down Content
            $(function() {
                    $('#open').click(function(){
                            $('#pull_down_content').animate({'top':'0px'},1000);
                            $('#open').fadeTo('slow', 0); 
                    });
                    $('#close').click(function(){
                            $('#pull_down_content').animate({'top':'-800px'},1000);
                            $('#open').fadeTo('slow', 1);
                    });

                    $('.h1, .h2, .heading').click(function(){
                            $('#pull_down_content').animate({'top':'0px'},1000);
                            $('#open').fadeTo('slow', 0); 
                    });
            });
        </script>
    </head>

    <body>
        <div id="container">
            <!-- Pull Down -->
            <div id="pull_down_content">
                <div class="about">
                    <div class="dropdown_heading">About Us</div>
                    <!-- About Us -->
                    <p>
                    Epicurissimo is a private network and online publication, a trusted place for professionals and connoisseurs of gastronomy and fine drinks to meet, connect, stay informed, showcase their work, find experts, share ideas, ask questions, find jobs and make business.</p>

                    <div class="nav">
                        <a href="<?=$this->uri('/pages/terms')?>"><?=$this->_('Terms & Conditions')?></a> |
                        <a href="<?=$this->uri('/pages/privacy')?>"><?=$this->_('Privacy Policy')?></a> |
                        <a href="<?=$this->uri('/pages/contact')?>"><?=$this->_('Contact')?></a>
                    </div>
                    <div class="social">
                            <!-- Social Links -->
                            <ul id="social">
                                <li class="facebook">
                                <a href="#" title="Facebook"></a>
                                </li>
                                <li class="twitter">
                                <a href="#" title="Twitter"></a>
                                </li>
                                <li class="google">
                                <a href="#" title="Google+"></a>
                                </li>

                                <li class="vimeo">
                                <a href="#" title="Vimeo"></a>
                                </li>

                    <li class="skype">
						<a href="#" title="Skype"></a>
					</li>

                            </ul>
                    </div>
                </div>

                <div id="contactForm" class="contact">
                    <!-- Contact Us -->
                    <div class="dropdown_heading">Contact Us</div>

                    <form class="pulldowncontact" method="post" action="<?=$this->link('/src/epic/php/submit-form.php')?>">
                        <input type="text" id="email" class="text-input" name="email" placeholder="your email address" />
                        <br />
                        <span id="errorEmail" class="formError"></span>

                        <textarea name="message" placeholder="type your message here" id="message" class="message"></textarea>
                        <span id="errorMessage" class="formError"></span>
                        <div class="complete">
                            <input type="submit" value="Send" name="submit" id="submit" class="submit" />
                            <span id="formProgress" class="formProgress"></span>
                        </div>
                    </form>

                </div>

                <!-- Close Pull Down -->
                <a href="#" class="button_up" id="close"></a>
            </div>
            <!-- End Drop Down -->
            <!-- Open Pull Down-->
            <a href="#" class="button_down" id="open"></a>
        </div>
        <!-- Black Horizontal Banner -->
        <div id="banner">
            <div id="wrapper">
                <!-- White Horizontal Rule -->
                <div class="rule"></div>

                <!-- Left block information -->
                <div class="leftinfo">
                </div>
                <!-- Right block information -->
                <div class="rightinfo">
                    <?if(isset($_GET['reg']) && $_GET['reg']):?>
                    <a href="<?=$this->uri('/')?>">Back</a>
                    <?endif?>
                </div>

                <div class="heading">
                    <!-- Coming soon main text -->
                        <img src="<?=$this->link('/src/epic/css/img/logofull.png')?>" height="90"  />    
                </div>

                <div id="countdown">
                    <!-- Countdown -->
                </div>

                <div class="signup_wrap">
                    <?if(isset($_GET['reg']) && $_GET['reg']):?>
                    <div class="signup">
                        <a href="<?=$this->uri('/reg/connoisseur')?>">
                            Sign Up as<br >
                            <span>Connoisseur Member</span>
                            <small>Share Inspire Connect Inform Enjoy</small>
                        </a>
                    </div>
                    <div class="signup last">
                        <a href="<?=$this->uri('/reg/professional')?>">
                            Sign Up as <br >
                            <span>Professional Member</span>
	
<!--<small>Show Your Works, Exchange Ideas, Get Connected, Develop Your Career</small>-->
                            <small>You work in relevant domains.</small>
                        </a>
                    </div>
                    <?else:?>
                    <div class="signup">
                        <a href="<?=$this->uri('/?reg=1')?>">
                            Sign Up as<br >
                            <span>Individual Member</span>
                        </a>
                    </div>
                    <div class="signup last">
                        <a href="<?=$this->uri('/reg/corporate')?>">
                            Sign Up as <br >
                            <span>Corporate Member</span>
                        </a>
                    </div>
                    <?endif?>
                    <!--
                    <div class="signup last"><a href="<?=$this->uri('/reg/corporate')?>">
                            Pre Sign Up as <br >
                            <span>Corporate</span>
                    </a></div>
                    -->
                </div>
                <div class="rule2">
                    <!-- Bottom White horizontal rule -->
                </div>
            </div>
        </div>
    </body>
</html>
