<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?=$this->language?>" lang="<?=$this->language?>">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
    <?=$this->headTitle()?>
	<!--[if lt IE 9]>
	<meta http-equiv="PRAGMA" content="NO-CACHE" />
    <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
	<![endif]-->
    <?=$this->headMeta()?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='http://fonts.googleapis.com/css?family=Philosopher' rel='stylesheet' type='text/css'>
    <link href="<?=$this->link('/src/epic/css/epic.css')?>" media="all" rel="stylesheet" type="text/css" />
    <?=$this->evajs()?>
</head>

<body class="prereg">


    <header id="header">
    <div class="container">
        <div class="navbar navbar-inverse"><div class="navbar-inner">
                <?$view =$this->layout()->getChildren();$id = $view[0]->id;?>
                <!--<a class="brand" href="/">Epicurissimo</a>-->
                <a class="brand" href="/"><img src="<?=$this->link('/src/epic/css/img/logo.png')?>" alt="logo"></a>	
                <ul class="nav nav-main">
                    <li><a href="/"><?=$this->_('Home')?><small>Epicurissimo</small></a></li>
                    <li class="<?=$id == 'connoisseur' ? 'active' : ''?>"><a href="/reg/connoisseur"><?=$this->_('Connoisseur')?><small>Pre Sign Up</small></a></li>
                    <li class="<?=$id == 'professional' ? 'active' : ''?>"><a href="/reg/professional"><?=$this->_('Professional')?><small>Pre Sign Up</small></a></li>
                    <li class="<?=$id == 'corporate' ? 'active' : ''?>"><a href="/reg/corporate"><?=$this->_('Corporate')?><small>Pre Sign Up</small></a></li>
                    <li class="<?=$id ? '' : 'active'?>"><a href="/pages/about"><?=$this->_('About Us')?><small>Who We Are</small></a></li>
                </ul>
        </div></div>
    </div>
    </header>

    <div id="page" class="page">
        <?=$this->layout()->content;?>
    </div><!-- #page end-->

    <footer id="footer" class="footer"><div class="container">
        <nav id="navbar_footer" class="">
        <ul class="nav pull-right">
            <li>
            Copyright 2012 Epicurissimo | 
            <select id="lang">
                <option value="">Language</option>
                <option value="<?=$this->uri('/language/en')?>">English</option>
                <option value="<?=$this->uri('/language/fr')?>">Française</option>
                <option value="<?=$this->uri('/language/zh')?>">中文</option>
                <option value="<?=$this->uri('/language/zh-TW')?>">繁体中文</option>
            </select>
            </li>
        </ul>
        </nav>
        <nav class="">
        <ul class="nav pull-left">
            <li class="first"><a href="<?=$this->uri('/')?>"><?=$this->_('Home')?></a>|</li><li>
            <a href="<?=$this->uri('/pages/terms')?>"><?=$this->_('Terms & Conditions')?></a>|</li><li>
            <a href="<?=$this->uri('/pages/privacy')?>"><?=$this->_('Privacy Policy')?></a>|</li><li>
            <a href="<?=$this->uri('/pages/contact')?>" class="last"><?=$this->_('Contact')?></a>|</li><li>
            <a href="#" class="last"><?=$this->_('Your City')?> : <?=$this->action('Epic\Controller\LocalController', 'indexAction',array('city' => 1));?></a></li>
        </ul>
        </nav>
        <div class="clearfix"></div>
        <p>
        </p>
    </div></footer><!-- #footer end-->


    <script src="<?=$this->link('/lib/js/jquery/jquery.min.js')?>"></script>
    <script src="<?=$this->link('/lib/js/bootstrap/bootstrap.min.js')?>"></script>
    <script src="<?=$this->link('/eva/js/core.js')?>"></script>
    <script src="<?=$this->link('/lib/js/jquery/jquery.easing.1.3.js')?>"></script>
    <script src="<?=$this->link('/eva/js/eva.jquery.evaSlider.js')?>"></script>
    <script src="<?=$this->link('/src/epic/js/jquery.stepy.min.js')?>"></script>
    <script src="<?=$this->link('/src/epic/js/init.js')?>"></script>

    <script>
        eva.init(eva_config);
        $('#signupform').stepy({
                description:  false,
                legend:       false,
                block:          false,
                titleClick: false,
                nextLabel:      '<?=$this->_('Next')?> >', 
                backLabel:      '<<?=$this->_('Previous')?>',
                finishButton: false
        }); 
        $("#signupform-titles").hide();
        $(".button-next").addClass('btn').css("margin-left", "160px");
        $(".button-back").addClass('btn').css("margin-left", "270px").css("margin-top", "-90px");
        $("input[type='checkbox']").css("margin-right", "5px");
    </script>
</body>
</html>
