<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?=$this->language?>" lang="<?=$this->language?>">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
    <?=$this->headTitle()?>
	<!--[if lt IE 9]>
	<meta http-equiv="PRAGMA" content="NO-CACHE" />
    <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
	<![endif]-->
    <?=$this->headMeta()?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="<?=$this->link('/src/epic/css/epic.css')?>" media="all" rel="stylesheet" type="text/css" />
    <?//=$this->evajs()?>
</head>

<body class="">

	<div class="navbar"><div class="navbar-inner"><div class="container">
                <a class="brand" href="/">Epicurissimo</a>	
    <ul class="nav">
        <li class="active"><a href="/"><?=$this->_('Home')?></a></li>
        <?if($this->hasModule('Blog')):?>
        <li><a href="/blog/"><?=$this->_('Blog')?></a></li>
        <?endif?>
        <?if($this->hasModule('User')):?>
        <li><a href="/user/"><?=$this->_('User')?></a></li>
        <?endif?>
	</ul>
    <ul class="nav pull-right">
        <li><a href="/admin/"><?=$this->_('Admin')?></a></li>
    </ul>
    </div></div></div>


<div id="page" class="page">
<?=$this->layout()->content;?>
</div><!-- #page end-->

<footer id="footer" class="footer"><div class="container">
			<nav id="navbar_footer" class="">
			<ul class="nav">
				<li><a href="<?=$this->uri('/')?>" class="first">首页</a></li><li>
				<a href="<?=$this->uri('/pages/about-yangs')?>">杨氏介绍</a></li><li>
				<a href="<?=$this->uri('/themes')?>">主题摄影</a></li><li>
				<a href="<?=$this->uri('/category/events')?>">最新活动</a></li><li>
				<a href="<?=$this->uri('/pages/franchise')?>">加盟连锁</a></li><li>
				<a href="<?=$this->uri('/contact/order/')?>">在线订单</a></li><li>
				<a href="<?=$this->uri('/pages/joinus')?>">人才招聘</a></li><li>
				<a href="<?=$this->uri('/pages/contact')?>" class="last">联系我们</a></li>
			</ul>
			</nav>
    <p>
    Copyright 2009 - 2012 A8国际婚纱电影会馆  All Rights Reserved
    </p>
    <p>电话：0931-8477000 13919002602
    </p>
    <p>邮箱：1095813029@qq.com | QQ：1095813029/1355246279</p>
    <p>地址：甘肃省兰州市张掖路231号民基大厦A座5楼
    </p>
    <p><a href="http://www.miibeian.gov.cn" target="_blank">陇ICP备7546564588号</a>　|　技术支持：<a href="http://www.easthv.cc/" target="_blank">兰州东方惠梵软件科技有限公司</a>
    </p>
</div></footer><!-- #footer end-->


<script src="<?=$this->link('/lib/js/jquery/jquery.min.js')?>"></script>
    <script src="<?=$this->link('/lib/js/bootstrap/bootstrap.min.js')?>"></script>
    <script src="<?=$this->link('/eva/js/core.js')?>"></script>
    <script src="<?=$this->link('/lib/js/jquery/jquery.easing.1.3.js')?>"></script>
    <script src="<?=$this->link('/eva/js/eva.jquery.evaSlider.js')?>"></script>
    <script src="<?=$this->link('/src/epic/js/init.js')?>"></script>
</body>
</html>
