<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?=$this->language?>" lang="<?=$this->language?>">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
    <?=$this->headTitle()?>
	<!--[if lt IE 9]>
	<meta http-equiv="PRAGMA" content="NO-CACHE" />
    <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
	<![endif]-->
    <?=$this->headMeta()?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='http://fonts.googleapis.com/css?family=Philosopher' rel='stylesheet' type='text/css'>
    <link href="<?=$this->link('/lib/css/fontawesome/css/font-awesome.css')?>" media="all" rel="stylesheet" type="text/css" />
    <link href="<?=$this->link('/src/epic/css/main.css')?>" media="all" rel="stylesheet" type="text/css" />

    <?=$this->evajs()?>

    <script src="<?=$this->link('/lib/js/labjs/labjs.min.js')?>"></script>
    <script src="<?=$this->link('/lib/js/jquery/jquery.js')?>"></script>
    <script src="<?=$this->link('/lib/js/jquery/jquery.validationEngine.js')?>"></script>
    <script src="<?=$this->link('/eva/js/core.js')?>"></script>
    <script src="<?=$this->link('/eva/js/ui.js')?>"></script>
    <script src="<?=$this->link('/src/epic/js/init.js')?>"></script>
</head>

<body class="prereg">


    <header id="header">
    <div class="navbar navbar-inverse">
        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <a class="brand pull-left" href="/"><img src="<?=$this->link('/src/epic/css/img/logo.png')?>" alt="logo"></a>	
                <div class="nav-collapse">
                    <ul class="nav nav-main">
                        <li data-highlight-url="^/home/?$"><a href="<?=$this->url('home')?>"><?=$this->_('Home')?></a></li>
                        <li class="" data-highlight-url="^/pages/magazine/?$"><a href="<?=$this->uri('/pages/magazine/')?>"><?=$this->_('Magazine')?></a></li>
                        <li class="" data-highlight-url="^/events/?"><a href="<?=$this->uri('/events/')?>"><?=$this->_('Events')?></a></li>
                        <li class="" data-highlight-url="^/pages/?$"><a href="<?=$this->uri('/pages/')?>"><?=$this->_('Topics')?></a></li>
                        <li class="" data-highlight-url="^/user.*"><a href="<?=$this->uri('/user/')?>"><?=$this->_('Members')?></a></li>
                        <li class="" data-highlight-url="^/share.*$"><a href="<?=$this->uri('/share/')?>"><?=$this->_('Share')?></a></li>
                    </ul>
                    <ul class="nav pull-right">
                        <li>
                        <form action="<?=$this->uri('/user/')?>" class="form form-search">
                            <div class="input-append">
                                <input name="keyword" type="text" class="input-mini search-query">
                                <button type="submit" class="btn"><i class="icon-search"></i></button>
                            </div>
                        </form>
                        </li>
                        <?if($this->hasModule('User')):?>
                        <?if($this->loginUser):?>
                       <li>
                       <a href="<?=$this->uri('/messages/')?>" class="nav-icon message-notice-count"><i class="icon-envelope-alt"></i><span class="count-number badge badge-important hide"></span></a>
                        </li>
                        <li class="dropdown">
                        <a href="#" class="dropdown-toggle nav-last" data-toggle="dropdown"><?=$this->loginUser['userName']?> <b class="caret"></b></a>
                        <ul class="dropdown-menu">
                            <li><a href="<?=$this->uri('/account/profile/')?>">Profile</a></li>
                            <li><a href="<?=$this->uri('/account/setting/')?>">Setting</a></li>
                            <li><a href="<?=$this->uri('/account/membership/')?>">Membership</a></li>
                            <li class="divider"></li>
                            <li><a href="<?=$this->uri('/logout/?callback=/login/')?>">Logout</a></li>
                        </ul>
                        </li>
                        <?else:?>
                        <li data-highlight-url="/register/*"><a href="/register/"><?=$this->_('Register')?></a></li>
                        <li data-highlight-url="/login/*"><a href="/login/"><?=$this->_('Login')?></a></li>
                        <?endif?>
                        <?endif?>

                    </ul>
                </div><!-- /.nav-collapse -->
            </div>
        </div><!-- /navbar-inner -->
    </div><!-- /navbar -->

    </header>

    <div id="page" class="page">
        <?=$this->layout()->content;?>
    </div><!-- #page end-->

    <footer id="footer" class="footer"><div class="container">
        <nav id="navbar_footer" class="">
        <ul class="nav pull-right">
            <li>
            Copyright 2012 Epicurissimo　| 　 
            <div class="btn-group dropup pull-right">
                <a class="btn dropdown-toggle btn-small btn-inverse" data-toggle="dropdown" href="#">Language
                    <span class="caret"></span>
                </a>
                <ul class="dropdown-menu pull-right">
                    <li><a href="<?=$this->uri('/language/en')?>">English</a></li>
                    <li><a href="<?=$this->uri('/language/fr')?>">Français</a></li>
                    <li><a href="<?=$this->uri('/language/zh')?>">中文</a></li>
                    <li><a href="<?=$this->uri('/language/zh-TW')?>">繁体中文</a></li>
                </ul>
            </div>

            </li>
        </ul>
        </nav>
        <nav class="">
        <ul class="nav pull-left">
            <li class="first"><a href="<?=$this->uri('/')?>"><?=$this->_('Home')?></a>|</li><li>
            <a href="<?=$this->uri('/pages/terms')?>"><?=$this->_('Terms & Conditions')?></a>|</li><li>
            <a href="<?=$this->uri('/pages/privacy')?>"><?=$this->_('Privacy Policy')?></a>|</li><li>
            <a href="<?=$this->uri('/pages/contact')?>" class="last"><?=$this->_('Contact')?></a>|</li><li>
            　<?=$this->_('Your City')?> : <?=$this->action('Epic\Controller\LocalController', 'indexAction',array('city' => 1));?> </li>
        </ul>
        </nav>
        <div class="clearfix"></div>
        <p>
        </p>
    </div></footer><!-- #footer end-->



    <script>
        eva.init(eva_config);
        eva.ui.init();
    </script>
</body>
</html>
