
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="<?=$this->language?>" lang="<?=$this->language?>">
<head>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<meta charset="utf-8" />
    <?=$this->headTitle()?>
	<!--[if lt IE 9]>
	<meta http-equiv="PRAGMA" content="NO-CACHE" />
    <script src="<?=$this->link('/lib/js/html5shiv/html5shiv.min.js')?>"></script>
	<![endif]-->
    <?=$this->headMeta()?>

    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href='http://fonts.googleapis.com/css?family=Philosopher' rel='stylesheet' type='text/css'>
    <link href="<?=$this->link('/src/epic/css/epic.css')?>" media="all" rel="stylesheet" type="text/css" />
    <?=$this->evajs()?>
</head>
<?
$form = new User\Form\AdminLoginForm();
$form->setView($this)
    ->setAction('#');
?>
<body class="scrolling">
    <div id="loginheader" class="navbar navbar-inverse navbar-fixed-top"><div class="navbar-inner">
            <div class="container">
                <a class="brand" href="/"><img src="<?=$this->link('/src/epic/img/logo.jpg')?>" alt="logo" height="60"></a>	
                <ul class="nav nav-main pull-right">
                    <li class=""><a href="#bg-0"><?=$this->_('GASTRONOMY')?></a></li>
                    <li class=""><a href="#bg-1"><?=$this->_('WINE')?></a></li>
                    <li class=""><a href="#bg-2"><?=$this->_('SPIRIT & COCKTAIL')?></a></li>
                    <li class=""><a href="#bg-3"><?=$this->_('HOTEL & RESORT')?></a></li>
                    <li class=""><a href="#bg-4"><?=$this->_('ART & DESIGN')?></a></li>
                    <li class=""><a href="#bg-5"><?=$this->_('EVENT')?></a></li>
                </ul>
                <div id="loginform" class="">
                    <form class="form form-inline span4" <?=$this->formAttr($form)?> >
                        <a href="/">Membership Request</a> or
                        <?=$form->restful();?>
                        <?=$form->helper('userName', array('class' => 'input-small', 'placeholder' => 'Email' ))?>
                        <?=$form->helper('password', array('class' => 'input-small', 'placeholder' => 'Password'))?>
                        <input name="callback" type="hidden" value="<?=$this->callback?>" />
                        <button class="btn btn-inverse" type="submit"><?=$this->_('Login')?></button>
                    </form>
                </div>
            </div>
    </div></div>

    <?=$this->layout()->content;?>

    <footer id="loginfooter" class="navbar navbar-fixed-bottom"><div class="container">
        <nav id="navbar_footer" class="">

        <ul class="nav pull-right">
            <li>
            Copyright 2012 Epicurissimo | 
            <select id="lang">
                <option value="">Language</option>
                <option value="<?=$this->uri('/language/en')?>">English</option>
                <option value="<?=$this->uri('/language/fr')?>">Française</option>
                <option value="<?=$this->uri('/language/zh')?>">中文</option>
                <option value="<?=$this->uri('/language/zh-TW')?>">繁体中文</option>
            </select>
            </li>
        </ul>
        <ul class="nav pull-left">
            <li class="first"><a href="<?=$this->uri('/')?>"><?=$this->_('Membership Information')?></a>|</li>
            <li><a href="<?=$this->uri('/pages/terms')?>"><?=$this->_('Terms & Conditions')?></a>|</li>
            <li><a href="<?=$this->uri('/pages/contact')?>" class="last"><?=$this->_('Contact')?></a></li>
            <li id="social">
            <a href="https://www.facebook.com/pages/Epicurissimo-Compass/478175602201443" title="Facebook" class="facebook"></a>
            <a href="https://twitter.com/Epicurissimo" title="Twitter" class="twitter"></a>
            <a href="https://plus.google.com/102220617896813322867" title="Google+" class="google"></a>
            <a href="http://pinterest.com/pin/524739794052354407/" title="Pinterest" class="vimeo"></a>
            <a href="http://weibo.com/2936625884" title="Weibo" class="skype"></a>
            </li>
            <li> | <?=$this->_('Your City')?> : <a href="#" class="last"><?=$this->action('Epic\Controller\LocalController', 'indexAction',array('city' => 1));?></a></li>
        </ul>

        </nav>
    </div></footer><!-- #footer end-->


    <script src="<?=$this->link('/lib/js/labjs/labjs.min.js')?>"></script>
    <script src="<?=$this->link('/lib/js/jquery/jquery.js')?>"></script>
    <script src="<?=$this->link('/lib/js/jquery/jquery.easing.1.3.js')?>"></script>
    <script src="<?=$this->link('/lib/js/jquery/jquery.validationEngine.js')?>"></script>
    <script src="<?=$this->link('/src/epic/js/jquery.parallax-1.1.3.js')?>"></script>
    <script src="<?=$this->link('/eva/js/core.js')?>"></script>
    <script src="<?=$this->link('/eva/js/ui.js')?>"></script>
    <script src="<?=$this->link('/src/epic/js/init.js')?>"></script>

    <script>
        eva.init(eva_config);
        $("#header .nav a").on('click', function(e){
                var to = $(this).attr("href");
                var pos = $(to).offset();
                $('body,html').animate({
                        scrollTop:pos.top
                    }, {
                        duration: 2000, 
                        specialEasing: {
                                scrollTop:'easeOutExpo'
                        } 
                });
                return false;
        });
        $('.loginblock').parallax("100%", 0.3);
    </script>
</body>
</html>
