<?
$this->headTitle($this->category['categoryName'], 'SET');

$gonggao = $this->action('Gwa\Api\Controller\FrontendController', 'postlistAction',array('category' => 'gonggao', 'rows' => 7));
$zhuanti = $this->action('Gwa\Api\Controller\FrontendController', 'postlistAction',array('category' => 'zhuanti', 'rows' => 7));
?>
<div class="container">
<ul class="breadcrumb">
	<li>您的位置：</li>
	<li class="">
		<a href="<?=$this->uri('/')?>">首页</a>
		<span class="divider">››</span>
	</li>
	<li class="">
	<a href="<?=$this->uri('/category/' . $this->category['urlName'])?>"><?=$this->category['categoryName']?></a>
	</li>
</ul>
</div>


<div class="page">
<!-- #body start-->
<article id="body" class="body grid-s7m0">

	<!-- #main start-->
	<section id="main-wrap" class="main-wrap"><article id="main" class="main">

		<?if($this->posts):?>
		<div class="vlist posts">
			<?foreach($this->posts as $key => $post):?>
			<div class="item <?=$key == 0 ? 'first' : ''?>">
				<div class="item-inline item_title">
					<h3><a href="<?=$this->uri('/pages/' . $post['urlName'])?>"><?=$post['title']?></a></h3>
					<p class="info">发布时间： <?=$post['createTime']?></p>
					<p class="description"><?=$post['preview']?></p>
				</div>
			</div>
			<?endforeach;?>
		</div>
		<?=$this->pager ? $this->partial('pager.phtml', $this) : ''?>

		<?else:?>
		<?endif;?>

        <?if($this->paginator):?>
        <?=$this->paginator->setPath('/category/' . $this->category['urlName'])->setBaseQuery($this->query);?>
        <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
        <?endif;?>

	</article></section>
	<!-- #main end-->

    <section id="sidebar" class="sidebar">

    <div class="article-menu">
        <ul>
            <li>
            <h3><a href="<?=$this->uri('/category/news')?>">
                    最新动态
                    <span class="divider">›</span>
            </a></h3>
            </li>
            <li>
            <h3><a href="<?=$this->uri('/category/jiudian')?>">
                    婚庆酒店
                    <span class="divider">›</span>
            </a></h3>
            </li>
            <li>
            <h3><a href="<?=$this->uri('/category/sheying')?>">
                    婚庆摄影
                    <span class="divider">›</span>
            </a></h3>
            </li>
            <li>
            <h3><a href="<?=$this->uri('/order/')?>">
                    在线订单
                    <span class="divider">›</span>
            </a></h3>
            </li>
        </ul>
    </div>

    <hr class="white">

    <div class="">
        <?=$this->widget('Gwa', 'components/adside')?>
        <div class="box-container-t15">
            <div class="tab-box square split3">
                <ul class="nav nav-tabs" id="side-news-tab">
                    <li class="active"><a href="#home">公告</a></li>
                    <li><a href="#profile">专题</a></li>
                    <li><a href="#messages">论坛</a></li>
                </ul>
                <div class="tab-content">
                    <div class="tab-pane active" id="home"><div class="box-container-v15">
                        <?if($gonggao):?>        
                            <ul class="vlist textlist">
                                <?foreach($gonggao as $post):?>
                                    <li><a href="<?=$this->uri('/pages/' . $post['urlName'])?>" target="_blank" title=""><?=$post['title']?></a></li>
                                <?endforeach;?>    
                            </ul>
                        <?endif;?>
                    </div></div>
                    <div class="tab-pane" id="profile"><div class="box-container-v15">
                        <?if($zhuanti):?>        
                            <ul class="vlist textlist">
                                <?foreach($zhuanti as $post):?>
                                    <li><a href="<?=$this->uri('/pages/' . $post['urlName'])?>" target="_blank" title=""><?=$post['title']?></a></li>
                                <?endforeach;?>    
                            </ul>
                        <?endif;?>
                    </div></div>
                    <div class="tab-pane" id="messages">...</div>
                </div>
            </div>
        </div>
    </div><!--span3 end-->


    </section>

    <!-- #body end-->
    </article>
</div>

