<?
$this->headTitle($this->post['title'], 'SET');
?>
<div class="container">
    <div id="singletitle" class="page-header typo">
        <h1><?=$post['title']?></h1>
    </div>
</div>
<div class="container">
    <div class="row">
        <div class="span12">
            <div class="well">
                <div class="hero-unit typo">
                    <?=$post['Text']['content'];?>
                </div>
            </div>
        </div>

    </div>
</div>
