<?
$this->headTitle('Epicurissimo compass | communauté privé pour les pros et les connaisseur du gastronomie et vin', 'SET');
$form = new Epic\Form\UserForm();
$form->useSubFormGroup()->setView($this);
?>
<div class="container"><div class="row">
        <div class="span12">
            <div id="myCarousel" class="carousel slide">
                <!-- Carousel items -->
                <div class="carousel-inner">
                    <div class="active item">
                        <img src="http://www.epicurissimo.net/wp-content/uploads/2012/09/Cocktails1.jpg" alt="" width="">
                        <div class="carousel-caption">
                            <p>The gentle art of gastronomy is a friendly one. It hurdles the language barrier, makes friends among civilized people, and warms the heart.</p>
                            <p>--- Samuel Chamberlain</p>
                        </div>
                    </div>
                    <div class="item">
                        <img src="http://www.epicurissimo.net/wp-content/uploads/2012/09/collage-e1346636318811.jpg" alt="">
                        <div class="carousel-caption">
                            <p>If there are gastronomes by predestination, then there are also some by circumstance.</p>
                            <p>---Brillat-Savarin</p>
                        </div>
                    </div>
                </div>
                <!-- Carousel nav -->
                <a class="carousel-control left" href="#myCarousel" data-slide="prev">&lsaquo;</a>
                <a class="carousel-control right" href="#myCarousel" data-slide="next">&rsaquo;</a>
            </div>

        </div><!--span4 end-->
</div></div><!--row container end-->
<div class="clearfix"></div>

<div class="container">
    <div class="row">
        <div class="span5">
            <form id="signupform" <?=$this->formAttr($form)?> class="form well">
                <div class="page-header typo">
                    <h1>Sign Up <span class="highlight">Connoisseur</span></h1>
                </div>
                <?=$form->restful();?>
                <?=$form->helper('id');?>
                <fieldset class="form-horizontal">
                    <div class="control-group <?=$form->isError('firstName') ? 'error' : '';?>">
                        <?=$form->helper('firstName', 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper('firstName', array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper('firstName', 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError('lastName') ? 'error' : '';?>">
                        <?=$form->helper('lastName', 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper('lastName', array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper('lastName', 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError('gender') ? 'error' : '';?>">
                        <?=$form->helper('gender', 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper('gender', 'formSelect', array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper('gender', 'formElementErrors')?></div>
                        </div>
                    </div>

                   <div class="control-group <?=$form->isError('email') ? 'error' : '';?>">
                        <?=$form->helper('email', 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper('email', array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper('email', 'formElementErrors')?></div>
                        </div>
                    </div>

                    <div class="control-group <?=$form->isError(array('Profile', 'birthday')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'birthday'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'birthday'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'birthday'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'height')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'height'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'height'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'height'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'weight')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'weight'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'weight'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'weight'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'country')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'country'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'country'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'country'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'address')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'address'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'address'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'address'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'addressMore')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'addressMore'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'addressMore'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'addressMore'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'city')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'city'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'city'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'city'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'province')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'province'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'province'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'province'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'state')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'state'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'state'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'state'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'zipcode')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'zipcode'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'zipcode'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'zipcode'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'phoneBusiness')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'phoneBusiness'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'phoneBusiness'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'phoneBusiness'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'phoneMobile')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'phoneMobile'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'phoneMobile'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'phoneMobile'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'phoneHome')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'phoneHome'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'phoneHome'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'phoneHome'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'fax')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'fax'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'fax'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'fax'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'signature')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'signature'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'signature'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'signature'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'location')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'location'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'location'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'location'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'bio')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'bio'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'bio'), 'formTextarea', array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'bio'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'localIm')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'localIm'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'localIm'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'localIm'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'internalIm')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'internalIm'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'internalIm'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'internalIm'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group <?=$form->isError(array('Profile', 'otherIm')) ? 'error' : '';?>">
                        <?=$form->helper(array('Profile', 'otherIm'), 'label', array('class' => 'control-label'))?>
                        <div class="controls">
                            <?=$form->helper(array('Profile', 'otherIm'), array('class' => ''))?>        
                            <div class="help-block"><?=$form->helper(array('Profile', 'otherIm'), 'formElementErrors')?></div>
                        </div>
                    </div>
                    <div class="control-group">
                        <div class="controls">
                            <label class="checkbox">
                                <input type="checkbox"> <?=$this->_('By clicking Sign Up, you agree to our')?> <a href=""><?=$this->_('Terms &amp; Conditions')?></a>.
                            </label>
                            <button type="submit" class="btn btn-large"><?=$this->_('Sign Up')?></button>
                        </div>
                    </div>

                </fieldset>
            </form>
        </div>

        <div class="span7">
            <div class="hero-unit typo">
                <div class="page-header">
                    <h1>Sign Up <span class="highlight">Professional</span></h1>
                </div>
                <h2>You Are</h2>
                <ul>
                    <li style="text-align: left;">Chefs, sommeliers, mixologists and other Practitioners in Hospitality Industry</li>
                    <li>Food and Wine critiques, journalists, etc.</li>
                    <li>Designers of Kitchen, culinary utensils, food stylists, photographs.</li>
                    <li>Other Professionals</li>
                </ul>
                <h2>Benefit</h2>
                <ul>
                    <li>Showcase your work and achievement</li>
                    <li>Career Opportunities: search for your perfect niche</li>
                    <li>Access to 100 000+ decision makers</li>
                    <li>Participate in International Events</li>
                    <li>Share experiences and Exchange ideas</li>
                    <li>Contact us for professional and personal support</li>
                </ul>

                <p class="centeralign"><a href="#" class="btn btn-large btn-info"><?=$this->_('Sign Up Now')?></a>
                </p>
            </div>
            <div class="hero-unit typo">
                <div class="page-header">
                    <h1>Sign Up <span class="highlight">Corporate</span></h1>
                </div>
                <h2>Your Are</h2>
                <ul>
                    <li>Restauranteurs</li>
                    <li>Houses of Fine Drinks (wine, spirit, gourmet beverage…)</li>
                    <li>High-end Resorts and Luxury Hotel</li>
                    <li>Other upscale Food and Drink establishment</li>
                </ul>
                <h2>Benefit</h2>
                <ul>
                    <li>Interact with customers and build business alliance globally</li>
                    <li>Featuring your service and products on your corporate profile</li>
                    <li>Host Events and invite guests within our gourmet circles</li>
                    <li>Post jobs and recruiting talents</li>
                    <li>Update your audience of company news</li>
                    <li>Offer access of your employees to our exclusive club</li>
                </ul>
                <p class="centeralign"><a href="#" class="btn btn-large btn-info"><?=$this->_('Sign Up Now')?></a>
                </p>
            </div>
        </div>

    </div>
</div>


