<?
$item = $this->item;
$formAction = $this->formAction;
$form = $this->form;
if(!$formAction){
    $formAction = $item['id'] ? $this->uri('/albums/edit/') : $this->uri('/albums/create/');
}
$method = $item['id'] ? 'put' : 'post';
$formExt = $this->formExt;

if(!$form) {
    $form = $item['id'] ? new Epic\Form\AlbumEditForm() : new Epic\Form\AlbumCreateForm();
}
$form->setAction($formAction)
->useSubFormGroup()
->setMethod($method)
->setView($this)
->bind($item)
->prepare();
$tags = isset($item['Tags']) ? $item['Tags'] : array();
?>

<form <?=$this->formAttr($form)?> class="form album-create-form">
    <?=$form->restful();?>
    <?=$form->helper('id');?>
    <?=$formExt?>
    <?if($this->callbackInput):?>
    <?=$this->callbackInput;?>
    <?endif;?>
    <fieldset class="">
        <div class="control-group <?=$form->isError('title') ? 'error' : '';?>">
            <?=$form->helper('title', 'label', array('class' => 'control-label'))?>
            <div class="controls docs-input-sizes">
                <?=$form->helper('title', array('class' => 'input-block-level'))?>
                <div class="help-block"><?=$form->helper('title', 'formElementErrors')?></div>
            </div>
        </div>

        <div class="control-group <?=$form->isError('urlName') ? 'error' : '';?> hide">
            <?=$form->helper('urlName', 'label', array('class' => 'control-label'))?>
            <div class="controls">
                <div class="input-prepend input-append">
                    <span class="add-on"><?=$this->serverUrl() . '/album/'?></span><?=$form->helper('urlName', array('class' => 'span6'))?><span class="add-on">/</span>
                </div>
                <div class="help-block"><?=$this->_('No input will create a random url')?></div>
                <div class="help-block"><?=$form->helper('urlName', 'formElementErrors')?></div>
            </div>
        </div>

        <div class="control-group <?=$form->isError('description') ? 'error' : '';?>">
            <div id="editor-left" class="controls">
                <?=$form->helper('description', 'formTextarea', array('class' => 'input-block-level', 'rows' => '15',))?>
            </div>
            <div id="editor-right" class="markdown-preview"></div>
            <div class="help-block"><?=$form->helper('description', 'formElementErrors')?></div>

        </div>
    </fieldset>
    <div class="form-actions">
        <button type="submit" class="btn btn-info btn-large"><?=$this->_('Publish');?></button>
    </div>
</form>
