<?
$item = $this->item;
$title = 'Notifications';
$title = $this->_($title);
$this->headTitle($title, 'SET');
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span6">
                                
                                <div class="page-main-header">
                                    <h3><?=$this->_($title)?> (<?=$this->paginator ? $this->paginator['rowCount'] : count($items)?>)</h3>
                                </div>

                                <div class="user-list vlist">
                                    <?foreach($items as $item):?>
                                    <div class="item">
                                        <div class="item-inline item-text span4">
                                            <div class="item-content">
                                                <?=$item['content']?>
                                            </div>
                                            <div class="item-action">
                                                <p class="pull-right"><a href="<?=$this->uri('/notifications/remove/' . $item['message_id'], 'c', array('c' => $this->uri('/notifications/')))?>" title="" class="highlight">Remove</a></p>
                                                <p class="pull-left">
                                                <time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['createTime'])?>" datetime="<?=$this->datetime()->isoTime($item['createTime'])?>"><?=$this->datetime($item['createTime'])?></time>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <?endforeach?>

                                    <?if($this->paginator):?>
                                    <?=$this->paginator->setPath('/notifications/')->setBaseQuery($this->query);?>
                                    <?=$this->widget('Core', 'widgets/paginator', $this->vars())?>
                                    <?endif;?>
                                </div><!--activity-list end-->
                            </div><!--page main left end-->
                            <div class="span3">
                                <div class="page-extra">
                                    <?=$this->widget('Epic', 'widgets/userextra', $this->vars())?>
                                </div>
                            </div><!--page main right end-->
                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside')?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->

