<?
$title = $this->user['userName'];
$title = $this->_($title);
$this->headTitle($title, 'SET');
$items = $this->items;
$message = $this->item;

if($this->form){
	$form = $this->form;
} else {
    $form = new Message\Form\MessageReplyForm();
}
$form->useSubFormGroup()
     ->setMethod('post')
     ->setView($this)
     ->setAction($this->uri('/message/'))
     ->bind($message)
     ->prepare();
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span6">
                                <div class="page-main-header">
                                    <h3><?=$this->_($title)?></h3>
                                </div>

                                <div class="activity-list vlist">
                                <?foreach($items as $item):?>
                                    <div class="item">
                                        <a href="<?=$this->uri('/user/' . $item['Sender']['userName'])?>" title="" class="item-absolute item-userface"><img src="<?=$this->gravatar($item['Sender']['email'])?>" alt="" class="img-rounded" width="60" height="60" /></a>
                                        <div class="item-inline item-text span5">
                                        <div class="item-content">
                                            <div class="item-title"><a href="<?=$this->uri('/user/' . $item['Sender']['userName'])?>" class="item-user"><?=$item['Sender']['userName']?></a> Said:</div>
                                            <p><?=$item['Message']['body']?></p>

                                            <div class="item-action">
                                                <p class="pull-right">
                                                    <a href="<?=$this->uri('/messages/remove/' . $item['id'], 'c', array('c' => $this->uri('/messages/' . $this->user['userName']))); ?>" class="btn btn-small btn-danger"><?=$this->_('Delete')?></a>
                                                </p>
                                                <p class="pull-left">
                                                    <time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['createTime'])?>" datetime="<?=$this->datetime()->isoTime($item['createTime'])?>"><?=$this->datetime($item['createTime'])?></time>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <?endforeach?>
                                </div><!--activity-list end-->
                                    
                                         <div class="item-sub-form">
                                             <form <?=$this->formAttr($form)?> class="activity-box span5">
                                             <?=$form->restful();?>
                                                <?=$form->helper(array('Conversation', 'recipient_id'), array('class' => ''))?>        
                                                <fieldset class="form">
                                                    <div class="item-sub-textarea">
                                                        <?=$form->helper('body', 'formTextarea', array('rows' => 5, 'placeholder' => 'Write a replay..'))?>        
                                                    </div>
                                                    <div class="item-absolute item-sub-submit">
                                                    <?if($items):?>
                                                        <button type="submit" class="btn btn-light-brown btn-large"><?=$this->_('Replay')?></button>
                                                    <?else:?>
                                                        <button type="submit" class="btn btn-light-brown btn-large"><?=$this->_('Submit')?></button>
                                                    <?endif;?>
                                                    </div>
                                                </fieldset>
                                                <input name="callback" type="hidden" value="<?=$this->uri('/messages/' . $this->user['userName'])?>" />
                                            </form>
                                        </div>
                            </div><!--page main left end-->
                            <div class="span3">
                                <div class="page-extra">
                                    <?=$this->widget('Epic', 'widgets/userextra')?>
                                </div>
                            </div><!--page main right end-->
                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside')?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->

