<?
$item = $this->item;
$title = 'Messages';
$title = $this->_($title);
$this->headTitle($title, 'SET');

if($this->form){
	$form = $this->form;
} else {
    $form = new Message\Form\MessageForm();
}
$form->useSubFormGroup()
     ->setMethod('post')
     ->setView($this)
     ->setAction($this->uri('/message/'))
     ->bind($item)
     ->prepare();
?>

<div class="container">
    <div class="normal-page">
        <div class="body grid-s5m0">

            <div class="main-wrap"><div id="main" class="main">
                    <div class="page-main">
                        <div class="row">
                            <div class="span6">
                                
                                <div class="row">
                                <form id="activity-form" <?=$this->formAttr($form)?> class="activity-box span6">
                                    <?=$form->restful();?>
                                    <input name="callback" type="hidden" value="<?=$this->uri('/messages/')?>" />
                                    <div class="page-header">
                                        <h3><?=$this->_('New Message')?></h3>
                                    </div>
                                    <fieldset class="form">
                                        <div class="activity-box-wrap">
                                            <div class="activity-box-content">
                                                <?=$form->helper(array('Conversation', 'recipient_id'), array('placeholder' => 'User Name', 'value' => isset($this->to) ? $this->to : null))?>
                                                <?=$form->helper('body', 'formTextarea', array('class' => '', 'rows' => 5))?>       
                                            </div>
                                            
                                            <div class="activity-box-buttons">
                                                <button type="submit" class="btn btn-light-brown btn-large"><?=$this->_('Send')?></button>
                                            </div>
                                        </div>
                                    </fieldset>
                                </form>
                                </div>


                                <div class="page-main-header">
                                    <h3><?=$this->_($title)?></h3>
                                </div>

                                <div class="activity-list vlist">
                                <?foreach($items as $item):?>
                                <div class="item">
                                <a href="<?=$this->uri('/messages/' . $item['User']['userName'])?>" title="" class="item-absolute item-userface"><img src="<?=$this->gravatar($item['User']['email'])?>" alt="" class="img-rounded" width="60" height="60" /></a>
                                <div class="item-inline item-text span5">
                                    <div class="item-content">
                                        <div class="item-title"><a href="<?=$this->uri('/messages/' . $item['User']['userName'])?>" class="item-user"><?=$item['User']['userName']?></a> Said:</div>
                                        <p><a href="<?=$this->uri('/messages/' . $item['User']['userName'])?>" class="item-user"><?=$item['Conversation']['Message']['body']?></a></p>

                                        <div class="item-action">
                                            <?if($item['messageCount'] > 0):?>
                                            <p class="pull-right">(<span class="highlight"><?=$item['messageCount']?></span>)</p>
                                            <?endif;?>
                                            <p class="pull-left">
                                            <a href="<?=$this->uri('/messages/' . $item['User']['userName'])?>" class="item-id"><time class="agotime" data-jstime="<?=$this->datetime()->jsTime($item['messageTime'])?>" datetime="<?=$this->datetime()->isoTime($item['messageTime'])?>"><?=$this->datetime($item['messageTime'])?></time></a>
                                            </p>
                                        </div>
                                    </div>

                                </div>
                                </div>
                                <?endforeach?>
                                </div><!--activity-list end-->
                            </div><!--page main left end-->
                            <div class="span3">
                                <div class="page-extra">
                                    <?=$this->widget('Epic', 'widgets/userextra')?>
                                </div>
                            </div><!--page main right end-->
                        </div>

                    </div><!--page-main end-->
            </div></div><!-- #main end-->

            <div class="sidebar">
                <div class="page-side">
                    <?=$this->widget('Epic', 'widgets/userside')?>
                </div>
            </div><!--sider end-->

        </div><!-- #body end-->
    </div><!-- normal end-->
</div><!--container end-->

