<div class="container">
    <div class="row">
        <div class="span12">
            <div class="well typo">
                <div class="">
                    <div class="page-header">
                        <h1>Paypal Test</h1>
                    </div>
                    <ul>
                        <li>$0.01 <a href="<?=$this->uri('/pay/paypal?p=0.01')?>"><?=$this->_('Click Here To Pay.')?></a></li>
                        <li>$0.02 <a href="<?=$this->uri('/pay/paypal?p=0.02')?>"><?=$this->_('Click Here To Pay.')?></a></li>
                        <li>$0.03 <a href="<?=$this->uri('/pay/paypal?p=0.03')?>"><?=$this->_('Click Here To Pay.')?></a></li>
                    </ul>
                    <div class="page-header">
                        <h1>Alipay Test</h1>
                    </div>
                    <ul>
                        <li>¥0.01 <a href="<?=$this->uri('/pay/alipay?p=0.01')?>"><?=$this->_('Click Here To Pay.')?></a></li>
                        <li>¥0.02 <a href="<?=$this->uri('/pay/alipay?p=0.02')?>"><?=$this->_('Click Here To Pay.')?></a></li>
                        <li>¥0.03 <a href="<?=$this->uri('/pay/alipay?p=0.03')?>"><?=$this->_('Click Here To Pay.')?></a></li>
                    </ul>
                    <p></p>
                </div>
            </div>
        </div>

    </div>
</div>
