<div class="container">
    <div id="singletitle" class="page-header typo">
        <h1>Payment Demo</h1>
    </div>
</div>

<div class="container">
    <div class="row">
        <div class="span12">
            <div class="well typo">
                <div class="row">
                    <div class="page-header">
                        <h1>Paypal Test</h1>
                    </div>
                    <div class="span3">$0.01
                            <div>
                                <a href="<?=$this->uri('/pay/paypal?p=0.01')?>"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/C2/i/btn/btn_buynowCC_LG.gif"></a>
                            </div>
                    </div>
                   <div class="span3">$0.02
                            <div>
                                <a href="<?=$this->uri('/pay/paypal?p=0.02')?>"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/C2/i/btn/btn_buynowCC_LG.gif"></a>
                            </div>
                        </div>
                   <div class="span4">$0.03 
                            <div>
                                <a href="<?=$this->uri('/pay/paypal?p=0.03')?>"><img alt="" border="0" src="https://www.paypalobjects.com/en_US/C2/i/btn/btn_buynowCC_LG.gif"></a>
                            </div>
                    </div>
                 
                </div>
                <div class="row">
                    <div class="page-header">
                        <h1>Alipay Test</h1>
                    </div>
                    <div class="span3">¥0.01
                            <div>
                                <a href="<?=$this->uri('/pay/alipay?p=0.01')?>"><?=$this->_('Click Here To Pay.')?></a>
                            </div>
                    </div>
                   <div class="span3">¥0.02
                            <div>
                                <a href="<?=$this->uri('/pay/alipay?p=0.02')?>"><?=$this->_('Click Here To Pay.')?></a>
                            </div>
                        </div>
                   <div class="span4">¥0.03 
                            <div>
                                <a href="<?=$this->uri('/pay/alipay?p=0.03')?>"><?=$this->_('Click Here To Pay.')?></a>
                            </div>
                    </div>
                    <p></p>
                </div>
            </div>
        </div>

    </div>
</div>
